<a href="https://colab.research.google.com/github/LSRajan/valley-outfitters-analysis/blob/main/01_Profiling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/LSRajan/valley-outfitters-analysis.git
%cd valley-outfitters-analysis

import pandas as pd
pd.set_option("display.max_columns", None)

Cloning into 'valley-outfitters-analysis'...
remote: Enumerating objects: 14, done.
remote: Counting objects: 100% (14/14), done.
remote: Compressing objects: 100% (11/11), done.
remote: Total 14 (delta 0), reused 10 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (14/14), 2.21 MiB | 13.46 MiB/s, done.
/content/valley-outfitters-analysis

In [2]:
orders = pd.read_csv("data/raw/orders.csv")
customers = pd.read_csv("data/raw/customers.csv")
order_items = pd.read_csv("data/raw/order_items.csv")
products = pd.read_csv("data/raw/products.csv")
returns = pd.read_csv("data/raw/returns.csv")
web_sessions = pd.read_csv("data/raw/web_sessions.csv")

#1. Orders

In [3]:
orders.head()

,order_id,customer_id,order_date,ship_date,status,payment_method,channel,discount_code,discount_amount,shipping_cost,order_total
0,ORD-223969,C3054,2025-09-24,2025-09-26,delivered,klarna,Web,NaN,0.00,0.0,208.08
1,ORD-221807,C1857,2026-01-28,NaN,Cancelled,Gift Card,Marketplace,NaN,0.00,0.0,223.48
2,ORD-210560,C5105,2025-12-18,2025-12-24,Delivered,Card,App,NaN,0.00,0.0,109.14
3,ORD-209414,C4333,2024-07-01,2024-07-06,Delivered,Card,app,welcome10,30.17,0.0,271.56
4,ORD-219246,C5677,27.06.24,"July 01, 2024",Delivered,Apple Pay,Web,NaN,0.00,0.0,591.92

In [4]:
orders.isna().sum()

order_id               0
customer_id          383
order_date           346
ship_date           3257
status                 0
payment_method         0
channel                0
discount_code      19138
discount_amount        0
shipping_cost          0
order_total          264
dtype: int64

###Issue 01 : Duplicate rows in orders table

In [5]:
orders.duplicated().sum()

np.int64(90)

### Proposed Fix 01: There are 90 duplicated rows in the table. Solve by dropping duplicated rows.

In [6]:
orders_temp = orders.drop_duplicates()

##1.1 order_id

In [7]:
orders["order_id"].head()

0    ORD-223969
1    ORD-221807
2    ORD-210560
3    ORD-209414
4    ORD-219246
Name: order_id, dtype: object

###Check: order_id should be unique with no duplicates

In [8]:
orders_temp["order_id"].duplicated().sum()

np.int64(0)

###Check: order_id should be in the format "ORD-[id number]"

In [9]:
pattern = r"ORD-\d+"
check = orders_temp["order_id"].str.fullmatch(pattern, na = False)
check.all()

np.True_

##1.2 customer_id

###Issue 02 : customer_id contains missing values.

In [10]:
print(orders_temp["customer_id"].isna().sum())
print(str(round(orders["customer_id"].isna().sum() / orders["customer_id"].count()*100, 2)) + "% of customer ids are missing")

382
1.55% of customer ids are missing

### Proposed Fix 02: A missing customer_id row does not make the order itself invalid, but it does break the relationship between the orders table and customers table. Any calculations involving this relationship should take this discrepancy into account, otherwise the order information can still be used without a customer id, so these rows will not be removed.

###Issue 03 : customer_id has inconsistent formatting

In [11]:
pattern = r"C\d+"
check = orders_temp["customer_id"].str.fullmatch(pattern, na = True)
check.all()

np.False_

In [12]:
orders_temp.loc[~check, "customer_id"]

96       c1730
293      c5806
1141     c5622
1418     c5260
1951     c2060
         ...
24282    c1545
24347    c5689
24780    c3382
24943    c5117
25014    c3578
Name: customer_id, Length: 123, dtype: object

### Proposed Fix 03: The customer ids that do not match the format just have a lowercase prefix. To solve, capitalize all customer IDs

In [13]:
orders_temp["customer_id"] = orders_temp["customer_id"].str.upper()

/tmp/ipykernel_477/1568589473.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orders_temp["customer_id"] = orders_temp["customer_id"].str.upper()

In [14]:
pattern = r"C\d+"
check = orders_temp["customer_id"].str.fullmatch(pattern, na = True)
check.all()
# There are no remaining formatting issues after capitalising.

np.True_

###Issue 04 : All customer ids in the orders table should exist inside of the customers table, but many do not.

In [15]:
customers["customer_id"].head()

0    C3082
1    C5810
2    C6231
3    C5373
4    C3666
Name: customer_id, dtype: object

In [16]:
pattern = r"C\d+"
check = customers["customer_id"].str.fullmatch(pattern, na = True)
check.all()
#all customer ids in the customers table fit the pattern, so can be compared directly

np.True_

In [17]:
check = orders_temp["customer_id"].isin(customers["customer_id"])
check.all()

np.False_

In [18]:
not_present = orders_temp.loc[~check & orders_temp["customer_id"].notna(), "customer_id"]
print(not_present.count())
print(not_present.nunique())

266
236

### Proposed Fix 04: There are 266 customer ids (236 unique) that are valid in format but do not match a customer id in the customers table. To keep consistency, they can be replaced by an NA value since they do not provide any information. However, this id can still be kept to keep a record and as it may be useful if more data was provided.

##1.3 order_date

###Issue 05 : There are missing order dates

In [19]:
orders_temp["order_date"].isna().sum()

np.int64(344)

###Proposed Fix 05: Similar to before, individual missing values do not lose too much information and the row remains useable. These values/rows do not need adjustment.

###Issue 06 : Order date should have consistent formatting. Instead it has several values representing missing values, date-time instead of just date, and different representations of dates. Standard date should be YYYY-MM-DD.

In [20]:
orders_temp["order_date"].value_counts()

order_date
2026-09-30             103
0000-00-00              66
TBC                     65
unknown                 62
2026-09-14              44
                      ...
2026-03-13 15:45:56      1
2026-08-21 11:20:12      1
2025-12-28 17:24:58      1
2025-04-30 15:08:17      1
2025-03-06 10:32:42      1
Name: count, Length: 9940, dtype: int64

###(Partial) Proposed Fix 06: There are several non-missing NA values that can be replaced with NA. This would keep the values in order date as date types and keep consistent formatting for unknown order dates.

In [21]:
non_missing_na = ["TBC", "unknown", "0000-00-00"]
orders_temp["order_date"] = orders_temp["order_date"].replace(non_missing_na, pd.NA)

/tmp/ipykernel_477/2450328662.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orders_temp["order_date"] = orders_temp["order_date"].replace(non_missing_na, pd.NA)

In [22]:
with pd.option_context("display.max_rows", None):
    display(orders_temp["order_date"].value_counts())

order_date
2026-09-30             103
2026-09-14              44
2026-07-29              35
2025-12-25              35
2026-09-21              35
2026-09-10              35
2026-07-31              33
2025-11-09              32
2025-11-12              32
2026-05-20              32
2026-07-03              32
2026-09-15              32
2026-09-19              32
2026-06-29              31
2026-07-13              30
2026-09-24              30
2025-12-09              30
2025-11-16              30
2025-11-05              30
2026-07-22              30
2026-08-10              30
2026-04-26              29
2026-06-24              29
2025-11-22              29
2025-11-21              29
2025-11-27              29
2025-11-25              29
2026-06-16              28
2026-07-17              28
2026-09-13              28
2025-11-17              28
2026-05-27              28
2026-06-06              28
2025-12-15              28
2025-11-14              28
2025-10-11              28
2025-11-03              28
2026-06-01              28
2026-06-26              28
2026-04-05              27
2025-11-23              27
2026-08-07              27
2025-12-22              27
2026-06-23              27
2025-12-21              27
2025-11-01              27
2026-05-22              27
2025-12-08              27
2025-11-30              27
2026-06-25              27
2026-07-26              27
2025-11-07              27
2026-08-15              27
2025-12-01              27
2026-09-25              27
2025-11-10              27
2026-07-30              26
2025-12-20              26
2026-09-03              26
2026-07-16              26
2025-11-19              26
2026-07-21              26
2026-09-08              26
2026-07-14              26
2026-04-09              26
2026-09-17              26
2026-07-04              26
2025-12-31              26
2026-08-14              25
2025-12-27              25
2026-03-19              25
2025-12-23              25
2026-09-09              25
2025-11-04              25
2025-12-14              25
2026-06-28              25
2025-12-05              25
2026-07-07              25
2025-12-30              25
2026-03-21              25
2026-09-12              25
2026-06-03              25
2026-09-05              25
2026-05-19              25
2025-11-28              24
2025-12-29              24
2026-05-16              24
2026-03-31              24
2025-11-08              24
2026-04-02              24
2025-11-06              24
2025-11-24              24
2025-11-15              24
2026-03-12              23
2026-05-11              23
2026-04-21              23
2026-06-18              23
2026-03-13              23
2026-05-21              23
2026-08-29              23
2026-07-12              23
2026-06-22              23
2026-09-16              23
2025-12-03              23
2026-05-13              23
2026-05-30              23
2026-03-22              23
2026-08-01              23
2026-05-09              23
2026-08-16              23
2026-04-06              23
2026-03-02              23
2026-08-18              23
2026-08-24              23
2025-12-06              23
2026-09-07              23
2026-08-05              23
2026-03-14              23
2026-03-27              23
2025-12-18              23
2026-07-11              22
2026-08-06              22
2026-05-24              22
2026-08-11              22
2026-03-18              22
2025-11-13              22
2026-05-01              22
2026-06-09              22
2026-04-22              22
2025-11-18              22
2026-09-02              22
2025-12-02              22
2026-04-28              22
2026-05-23              22
2026-05-05              22
2026-07-01              22
2026-06-08              22
2026-05-12              22
2026-07-09              22
2025-09-21              22
2025-12-12              22
2026-05-06              22
2026-07-10              22
2026-03-25              21
2026-08-13              21
2026-09-01              21
2025-09-15              21
2026-09-26              21
2025-12-13              21
2026-06-13              21
2026-03-29              21
2026-07-15              21
2026-04-03              21
2025-12-17              21
2025-09-06              21
2026-05-29              21
2026-09-18              21
2025-09-10              20
2026-06-12              20
2026-05-07              20
2025-07-09              20
2026-08-31              20
2026-09-04              20
2026-03-26              20
2026-07-20              20
2025-08-31              20
2026-08-22              20
2025-12-11              20
2026-03-30              20
2026-05-17              20
2026-04-25              20
2026-04-19              20
2026-07-28              20
2025-07-06              20
2025-12-19              20
2026-03-11              20
2026-04-15              20
2024-12-16              20
2026-07-19              20
2026-04-11              20
2026-09-28              20
2026-06-14              20
2026-06-02              20
2026-06-10              20
2026-05-02              20
2025-11-20              20
2025-11-02              20
2026-07-02              20
2026-07-27              19
2026-08-19              19
2025-05-02              19
2026-08-21              19
2025-09-17              19
2026-09-20              19
2026-02-21              19
2026-07-05              19
2026-04-24              19
2026-04-29              19
2025-10-26              19
2026-06-20              19
2026-09-22              19
2025-12-07              19
2026-03-07              19
2025-09-30              19
2026-03-23              19
2026-03-16              19
2026-04-07              19
2026-01-05              19
2026-03-15              19
2025-11-11              19
2025-07-26              19
2025-10-23              19
2026-08-09              19
2026-06-19              19
2026-03-10              19
2026-07-18              19
2025-09-27              19
2025-06-01              18
2026-05-25              18
2025-07-22              18
2026-05-14              18
2025-12-10              18
2026-08-28              18
2026-01-06              18
2026-08-30              18
2026-02-10              18
2025-06-24              18
2025-07-17              18
2026-06-05              18
2026-02-17              18
2025-07-16              18
2026-03-04              18
2026-08-08              18
2025-09-28              18
2026-08-17              18
2025-12-16              18
2026-06-15              18
2026-08-23              18
2025-06-22              18
2026-05-03              18
2026-04-23              18
2026-07-24              18
2025-11-29              18
2026-02-04              18
2026-04-08              18
2025-10-13              17
2026-09-11              17
2026-06-30              17
2026-05-10              17
2025-06-12              17
2025-07-08              17
2026-04-30              17
2025-06-10              17
2026-05-08              17
2025-10-27              17
2025-08-06              17
2026-08-04              17
2026-09-29              17
2025-10-02              17
2026-04-17              17
2026-02-28              17
2026-06-04              17
2025-12-24              17
2026-02-03              17
2026-02-07              17
2026-03-01              17
2025-08-16              17
2025-05-14              17
2026-06-17              17
2025-07-21              17
2025-07-13              17
2025-10-07              17
2026-09-27              17
2026-01-30              17
2026-07-25              17
2025-10-16              16
2026-08-27              16
2026-07-08              16
2025-10-25              16
2025-04-28              16
2025-06-26              16
2024-11-20              16
2025-01-23              16
2026-06-27              16
2026-09-23              16
2026-01-31              16
2026-08-02              16
2026-02-14              16
2025-12-28              16
2025-09-14              16
2025-07-14              16
2025-10-08              16
2025-05-16              16
2025-09-20              16
2026-04-13              16
2025-09-05              16
2025-09-13              16
2026-04-12              16
2024-12-17              16
2026-02-15              16
2025-08-14              16
2026-03-28              16
2025-09-22              16
2026-02-19              16
2025-08-03              16
2026-02-11              16
2026-01-18              16
2026-01-28              16
2024-12-04              15
2026-08-03              15
2024-11-28              15
2025-07-03              15
2026-04-27              15
2026-01-10              15
2025-07-20              15
2026-01-17              15
2025-09-16              15
2026-02-26              15
2024-12-05              15
2026-07-23              15
2025-05-07              15
2026-02-02              15
2024-12-26              15
2026-05-15              15
2025-07-01              15
2025-09-08              15
2026-09-06              15
2026-01-19              15
2026-06-11              15
2025-08-29              15
2026-05-31              15
2026-06-07              15
2025-07-23              15
2026-03-06              15
2026-03-08              15
2025-12-04              15
2025-06-30              15
2025-07-07              15
2024-12-15              15
2024-12-20              15
2025-06-20              15
2025-06-19              15
2026-03-09              15
2026-08-20              15
2026-04-20              15
2026-04-04              15
2026-05-26              15
2026-07-06              15
2025-06-28              15
2025-05-17              15
2026-03-03              15
2025-10-04              15
2026-03-24              15
2025-09-07              14
2025-08-26              14
30.09.26                14
2024-11-04              14
2026-01-12              14
2026-04-10              14
2025-06-23              14
2025-08-07              14
2026-02-25              14
2025-07-29              14
2025-12-26              14
2025-05-21              14
2025-03-17              14
2024-12-31              14
2025-07-30              14
2026-06-21              14
2025-10-17              14
2024-11-03              14
2025-05-31              14
2026-03-05              14
2026-01-26              14
2025-07-11              14
2024-11-11              14
2026-08-25              14
2025-10-06              14
2026-03-17              14
2025-09-11              14
2025-10-28              14
30 Sep 2026             14
2025-08-04              14
2024-12-27              14
2025-08-23              13
2025-03-14              13
2025-08-20              13
2025-10-15              13
2024-11-22              13
2026-02-18              13
2025-05-06              13
2025-07-24              13
2025-09-24              13
2024-12-29              13
2025-05-30              13
2024-12-25              13
2025-05-28              13
2024-12-03              13
2025-08-22              13
2024-11-08              13
2026-02-22              13
2026-05-04              13
2024-11-21              13
2025-10-03              13
2025-07-10              13
2025-09-29              13
2026-01-16              13
2026-01-21              13
2024-12-13              13
2025-08-17              13
2026-01-14              13
2025-08-21              13
2024-12-06              13
2024-12-09              13
2026-04-16              13
2025-10-01              13
2025-06-18              13
2025-08-18              13
2025-04-29              13
2025-08-01              13
2026-02-01              13
2026-03-20              13
2026-05-28              13
2025-10-10              12
2024-11-13              12
2025-06-02              12
2025-10-30              12
2024-11-24              12
2026-01-07              12
2025-06-16              12
2025-10-14              12
2026-01-29              12
2025-11-26              12
2025-08-10              12
2025-07-02              12
2025-06-08              12
2026-01-23              12
2025-06-29              12
2025-10-21              12
2025-08-05              12
2025-09-12              12
2024-12-23              12
2024-12-18              12
2025-09-04              12
2025-08-28              12
2025-04-24              12
2025-09-09              12
2026-04-18              12
2025-07-31              12
2025-05-27              12
2026-01-03              12
2025-09-02              12
2025-06-21              12
2025-01-15              12
2025-05-09              12
2026-01-24              12
2025-05-24              12
2026-02-16              12
2026-01-22              12
2024-12-01              12
2025-03-02              11
2026-01-15              11
2025-09-03              11
September 30, 2026      11
2024-10-08              11
2025-09-19              11
2026-04-01              11
2025-08-13              11
2025-03-31              11
2025-09-18              11
2024-11-09              11
2024-11-30              11
2025-04-27              11
2025-10-31              11
2025-06-15              11
2025-05-23              11
2026-05-18              11
2025-03-01              11
2024-11-17              11
2026-01-11              11
2026-01-27              11
2025-04-07              11
2024-11-16              11
2025-06-17              11
2025-07-18              11
2024-12-08              11
2026-02-20              11
2026-02-09              11
2025-05-11              11
2024-11-05              11
2024-12-14              11
2025-07-28              11
2025-06-09              11
2025-03-06              11
2025-08-25              11
2024-12-12              11
2025-03-26              11
2025-08-11              11
2024-11-27              11
2024-12-10              11
2025-04-08              11
2025-09-23              11
2026-08-26              11
2024-11-02              11
2025-01-26              11
2026-02-12              10
2024-07-07              10
2025-03-15              10
2025-03-22              10
2024-07-10              10
2025-04-01              10
2025-03-29              10
2026-02-08              10
2026-08-12              10
2026-01-25              10
2024-11-25              10
2025-06-14              10
2024-11-14              10
2025-10-18              10
2025-03-11              10
2025-08-09              10
09-30-2026              10
2025-04-15              10
2025-04-17              10
2024-10-28              10
2025-09-26              10
2025-01-28              10
2025-10-24              10
2025-08-27              10
2024-11-06              10
2025-04-02              10
2025-03-12              10
2025-02-11              10
2025-02-13              10
2025-02-23              10
2025-10-09              10
2026-02-13              10
2025-03-25              10
2026-01-04              10
2025-10-12              10
2025-01-12              10
2026-01-13              10
2025-02-24              10
2024-12-21              10
2024-11-19              10
2025-04-12              10
2025-06-27              10
2025-06-07              10
2025-06-05              10
2025-07-05              10
2024-11-10              10
2025-08-19              10
2025-07-12              10
2025-05-01              10
2024-09-11              10
2025-10-05              10
2025-10-20              10
2026-01-08              10
2025-05-08               9
2025-08-08               9
2025-04-22               9
2025-03-21               9
2026-02-24               9
2025-03-18               9
2025-05-05               9
2024-06-27               9
2025-03-16               9
2025-07-04               9
2026/09/30               9
2024-12-22               9
2026-01-01               9
2026-02-05               9
2025-04-04               9
2024-12-24               9
2025-02-14               9
30/09/2026               9
2025-02-26               9
2025-07-25               9
2025-02-20               9
2025-06-25               9
2025-03-20               9
2026-01-02               9
2025-05-25               9
2025-02-21               9
2025-06-06               9
2025-02-28               9
2025-10-19               9
2025-02-16               9
2025-04-30               9
2025-03-19               9
2024-08-31               8
2025-05-13               8
2025-05-29               8
2024-06-23               8
2025-02-25               8
2024-07-14               8
2024-12-28               8
2026-01-20               8
2025-04-20               8
2025-04-26               8
2025-01-14               8
2025-05-22               8
2024-09-16               8
September 03, 2025       8
2024-11-23               8
2025-08-02               8
2024-12-07               8
05/11/2025               8
2026/07/16               8
2024-10-04               8
2025-06-03               8
2024-11-12               8
2025-02-17               8
2024-07-11               8
2025-08-12               8
2026-04-14               8
2024-12-19               8
2025-04-18               8
2025-01-20               8
2025-04-09               8
2025-08-15               8
2024-07-17               8
2025-01-16               8
August 15, 2026          8
2025-04-06               8
2025-09-25               8
2025-05-04               8
2025-05-15               8
2025-01-03               8
2024-11-15               8
2024-08-27               8
2025-03-05               8
2025-05-12               8
2024-09-13               8
2025-03-03               8
2025-05-03               8
2024-07-08               8
2024-09-26               8
2025-08-24               8
2024-06-13               8
2024-09-19               7
2025-04-10               7
12-31-2025               7
2024-09-29               7
2024-09-23               7
2026-02-27               7
2026-01-09               7
2024-06-26               7
2024-09-14               7
November 25, 2025        7
2025-01-29               7
2025-05-19               7
2025-02-19               7
21 Dec 2025              7
2024-11-01               7
September 27, 2026       7
2025-10-22               7
2025-04-14               7
2025-04-21               7
May 10, 2026             7
2024-10-23               7
2025-02-27               7
2025-03-27               7
2025-03-24               7
May 30, 2026             7
29/06/2026               7
2025-01-24               7
06/07/2026               7
26.11.25                 7
2025-10-29               7
2025-07-19               7
2025/11/29               7
2024-10-11               7
2025-03-13               7
2024-08-13               7
2024-11-26               7
2025-03-30               7
2026-02-23               7
2025-06-11               7
2025-05-20               7
17.09.26                 7
2025-01-06               7
2025-06-13               7
2024-11-29               7
2025-01-04               7
2025-04-03               7
2024-12-02               7
2025-01-22               7
2025-06-04               7
2025-02-06               7
2024-07-22               7
2024-12-11               7
2024-07-04               7
23/06/2025               7
2024-07-30               7
2025-01-27               7
2025-02-05               6
2024-11-18               6
2024-06-01               6
2024-12-30               6
30 Jun 2025              6
2026/09/03               6
2024-09-07               6
2024-08-20               6
2024-07-27               6
31 Jul 2026              6
07-31-2026               6
2025-04-05               6
2025-09-01               6
November 17, 2025        6
19.08.26                 6
2024-09-08               6
2025-01-13               6
2024-06-15               6
31/12/2025               6
09-11-2026               6
2025-04-13               6
November 13, 2025        6
12-16-2025               6
08-09-2026               6
22 Dec 2025              6
November 08, 2025        6
2026/08/08               6
2025-02-08               6
2024-07-12               6
03 Aug 2025              6
21/09/2026               6
2024-08-07               6
2026/09/15               6
2024-06-08               6
2024-07-13               6
09 Jul 2026              6
2024-07-18               6
03.03.26                 6
2024-07-16               6
2025-02-09               6
09-06-2026               6
20.07.26                 6
2024-07-19               6
07 May 2025              6

In [23]:
pattern = r"\d{4}-\d{2}-\d{2}"
check = orders_temp["order_date"].str.fullmatch(pattern, na=False)
incorrect_dates = orders_temp.loc[~check & orders_temp["order_date"].notna(), "order_date"]
incorrect_dates.value_counts()

order_date
30 Sep 2026            14
30.09.26               14
September 30, 2026     11
09-30-2026             10
30/09/2026              9
                       ..
2024-09-25 17:20:35     1
2026-02-05 15:12:27     1
31.10.24                1
May 08, 2024            1
2026-05-09 14:56:41     1
Name: count, Length: 8954, dtype: int64

###Proposed Fix 06: The remaining values are just in the wrong time formats. Get the values by their format and convert those into the correct format. Any remaining values not in a given format can be handled manually.

##1.4 ship_date

###Issue 07 : (Same issues as order date) Ship date should have consistent formatting. Instead it has several values representing missing values, date-time instead of just date, and different representations of dates. Standard date should be YYYY-MM-DD.

In [24]:
orders_temp["ship_date"].value_counts()

ship_date
TBC               52
0000-00-00        50
2025-11-09        49
2026-07-23        48
unknown           45
                  ..
15.05.25           1
March 31, 2024     1
July 01, 2024      1
06-07-2025         1
12-23-2024         1
Name: count, Length: 4505, dtype: int64

##1.5 status

###Issue 08 : While status has a fixed set of possible values, the rows contain many variations, mispellings, or capitalisations of the same value.

In [25]:
orders["status"].value_counts()

status
Delivered      14956
Cancelled       1352
completed       1039
DELIVERED       1019
Complete         998
delivered        993
Returned         991
Deliverd         987
Shipped          776
Pending          389
Processing       332
cancelled        129
RETURNED         118
CANCELLED        113
cancled          112
Return           108
Canceled         108
returned         100
SHIPPED           84
In transit        80
shipped           67
processing        59
In progress       52
Pending           46
PENDING           41
pending           41
Name: count, dtype: int64

In [26]:
orders["status"].str.strip().str.lower().value_counts()

status
delivered      16968
cancelled       1594
returned        1209
completed       1039
complete         998
deliverd         987
shipped          927
pending          517
processing       391
cancled          112
return           108
canceled         108
in transit        80
in progress       52
Name: count, dtype: int64

###Proposed Fix 08: These values can be stripped and lowered, followed by manually fixing spelling errors and ensuring one consistent label rather than several labels for the same underlying meaning.

##1.6 payment_method

###Issue 09 : While payment method has a fixed set of possible values, the rows contain many variations, mispellings, or capitalisations of the same value. There are also different versions for abbreviated or spaced values.

In [27]:
orders["payment_method"].value_counts()

payment_method
PayPal         4056
Apple Pay      4048
Gift Card      4020
Klarna         3980
Card           3945
klarna          510
Giftcard        506
ApplePay        502
apple pay       495
gift card       491
KLARNA          460
Paypal          358
paypal          331
PP              311
Debit card      292
card            265
CARD            264
Credit Card     256
Name: count, dtype: int64

###Proposed Fix 09: These values can be stripped and lowered, followed by manually fixing spelling errors and ensuring one consistent label rather than several labels for the same underlying meaning.

##1.7 channel

###Issue 10 : While channel has a fixed set of possible values, the rows contain many variations, mispellings, or capitalisations of the same value. There are also different versions for abbreviated or spaced values.

In [28]:
orders["channel"].value_counts()

channel
Web            11266
App             5550
Marketplace     2690
In-store        1149
web              815
WEB              806
Online           801
Phone            661
APP              381
app              352
MARKETPLACE      189
marketplace      176
IN-STORE          87
in-store          79
phone             49
PHONE             39
Name: count, dtype: int64

###Proposed Fix 10: These values can be stripped and lowered, followed by manually fixing spelling errors and ensuring one consistent label rather than several labels for the same underlying meaning.

##1.8 discount_code

###Issue 11 : The discount code column appears to have many different variations of the same discount code. For example, 'welcome10', 'Welcome10', 'WELCOME10'. The reasonable assumption is that discount codes are not case sensitive and that these are all the same code. However it should be noted that they might actually be distinct, and that might cause an error later on.

In [29]:
orders["discount_code"].value_counts()

discount_code
WELCOME10     1718
SUMMER20      1301
FREESHIP      1025
LOYAL15        873
BF25           130
welcome10      110
Welcome10      102
WELCOME10      101
Summer20        76
SUMMER20        74
summer20        71
Freeship        70
freeship        67
LOYAL15         62
FREESHIP        55
loyal15         52
Loyal15         41
BF25             8
Bf25             8
bf25             8
Name: count, dtype: int64

###Proposed Fix 11: These values can be stripped and lowered, followed by manually fixing spelling errors and ensuring one consistent label rather than several labels for the same underlying discount code. Possible downstream errors should be considered if an issue arises.

##1.9 discount_amount

###Check: discount amount should be float values to two decimal points

In [30]:
with pd.option_context("display.max_rows", None):
    display(orders_temp["discount_amount"].value_counts())

discount_amount
0.00      20278
9.76         12
1.96         11
4.55         11
4.54         10
0.72         10
18.56        10
8.30          9
20.65         9
15.01         9
51.21         9
7.62          9
5.46          9
4.23          8
35.49         8
9.08          8
11.88         8
9.15          8
13.58         8
16.28         8
8.95          8
34.23         8
7.66          8
3.93          8
8.63          7
2.27          7
15.56         7
19.52         7
19.98         7
13.92         7
4.61          7
10.34         7
21.39         7
5.83          7
20.02         7
19.49         7
55.33         7
4.27          7
18.50         7
19.81         7
26.61         7
8.21          7
3.65          7
16.71         6
20.28         6
25.60         6
8.97          6
20.36         6
22.02         6
9.77          6
10.04         6
26.79         6
13.32         6
9.72          6
15.52         6
62.44         6
26.63         6
8.98          6
15.53         6
26.57         6
12.19         6
3.26          6
27.85         6
5.17          6
4.75          6
1.22          6
9.94          6
34.66         6
38.42         6
9.51          6
8.96          6
34.08         6
12.55         6
31.22         6
4.97          6
13.46         6
11.74         6
7.33          6
19.54         6
49.18         6
4.26          5
9.67          5
5.25          5
6.81          5
37.78         5
5.01          5
10.22         5
7.31          5
5.06          5
13.28         5
8.14          5
10.74         5
18.29         5
7.97          5
3.28          5
60.90         5
22.35         5
27.53         5
15.32         5
31.12         5
47.89         5
44.04         5
2.90          5
7.50          5
8.86          5
4.33          5
5.61          5
59.19         5
3.56          5
27.15         5
16.83         5
9.48          5
17.92         5
12.43         5
6.73          5
2.96          5
6.45          5
13.38         5
11.69         5
31.71         5
7.44          5
7.12          5
49.25         5
23.32         5
3.47          5
7.45          5
6.54          5
8.54          5
14.88         5
38.30         5
8.37          5
13.77         5
40.41         5
5.84          5
9.37          5
24.86         5
12.44         5
20.98         5
4.48          4
40.11         4
27.66         4
5.11          4
28.52         4
11.65         4
19.44         4
30.17         4
31.62         4
17.30         4
16.13         4
3.37          4
5.92          4
31.01         4
2.63          4
23.71         4
2.51          4
13.31         4
13.29         4
13.37         4
1.11          4
11.67         4
12.20         4
37.13         4
10.33         4
10.67         4
23.16         4
18.74         4
35.92         4
4.86          4
30.02         4
4.15          4
15.00         4
2.22          4
8.07          4
45.95         4
113.33        4
7.76          4
29.01         4
24.38         4
5.34          4
1.72          4
6.32          4
19.21         4
24.62         4
15.47         4
28.72         4
3.94          4
38.06         4
27.59         4
7.25          4
4.45          4
8.52          4
26.29         4
6.75          4
7.79          4
42.78         4
6.07          4
22.51         4
3.04          4
5.97          4
63.40         4
11.23         4
1.75          4
10.91         4
6.64          4
20.85         4
3.32          4
6.56          4
16.80         4
45.15         4
15.59         4
36.94         4
22.82         4
3.98          4
5.48          4
6.10          4
22.46         4
13.02         3
12.12         3
50.56         3
30.50         3
41.30         3
28.94         3
17.50         3
4.92          3
13.41         3
12.60         3
44.60         3
4.88          3
61.10         3
7.72          3
27.67         3
71.44         3
16.89         3
7.74          3
22.44         3
9.22          3
15.54         3
21.92         3
20.21         3
57.44         3
63.35         3
17.82         3
4.58          3
5.94          3
45.26         3
74.01         3
15.25         3
35.72         3
24.24         3
10.93         3
19.03         3
5.78          3
10.49         3
19.79         3
27.96         3
11.16         3
62.18         3
64.86         3
19.15         3
51.89         3
33.52         3
41.43         3
20.88         3
7.13          3
27.57         3
0.88          3
24.47         3
12.63         3
5.87          3
11.09         3
20.47         3
14.23         3
18.20         3
10.43         3
8.16          3
6.68          3
30.36         3
45.68         3
11.00         3
1.69          3
43.50         3
25.01         3
14.52         3
27.62         3
34.94         3
4.67          3
5.37          3
3.95          3
33.86         3
4.47          3
3.33          3
24.85         3
17.77         3
25.10         3
33.36         3
38.83         3
27.83         3
17.33         3
18.45         3
0.98          3
27.84         3
16.36         3
15.55         3
58.08         3
36.90         3
4.31          3
8.36          3
37.51         3
43.24         3
9.75          3
42.90         3
29.04         3
9.89          3
29.60         3
22.97         3
12.80         3
3.38          3
17.95         3
110.66        3
14.63         3
35.83         3
1.66          3
41.85         3
18.46         3
2.92          3
8.73          3
16.74         3
43.79         3
23.30         3
13.21         3
37.00         3
5.90          3
34.88         3
49.13         3
6.49          3
8.75          3
38.40         3
18.54         3
6.71          3
5.82          3
6.13          3
42.81         3
32.32         3
16.00         3
17.66         3
13.91         3
45.53         2
27.82         2
30.45         2
29.34         2
38.63         2
46.52         2
21.21         2
13.14         2
19.80         2
24.67         2
47.42         2
44.29         2
41.94         2
30.85         2
55.06         2
30.07         2
35.31         2
41.96         2
72.46         2
7.52          2
8.46          2
9.27          2
13.47         2
45.59         2
69.84         2
33.39         2
69.41         2
107.31        2
67.25         2
16.31         2
66.04         2
83.18         2
45.64         2
7.42          2
6.51          2
15.81         2
39.04         2
130.11        2
49.66         2
15.86         2
26.74         2
18.65         2
33.40         2
66.91         2
41.08         2
70.01         2
18.83         2
23.29         2
9.23          2
72.06         2
50.92         2
73.87         2
122.94        2
23.78         2
30.26         2
75.02         2
34.74         2
37.29         2
15.06         2
53.65         2
11.49         2
55.18         2
5.79          2
33.04         2
42.70         2
12.89         2
61.15         2
30.63         2
56.85         2
19.97         2
11.89         2
28.28         2
22.30         2
78.03         2
73.48         2
24.45         2
12.23         2
54.15         2
35.82         2
32.84         2
14.24         2
43.56         2
42.60         2
45.65         2
22.21         2
26.00         2
5.20          2
13.88         2
42.06         2
82.99         2
4.59          2
55.51         2
31.40         2
14.47         2
9.65          2
48.76         2
59.87         2
6.35          2
27.14         2
23.81         2
21.46         2
7.32          2
31.05         2
42.12         2
31.09         2
69.14         2
65.85         2
20.07         2
10.10         2
33.08         2
75.91         2
1.07          2
24.25         2
23.98         2
9.25          2
6.82          2
10.78         2
97.59         2
72.89         2
18.05         2
71.62         2
36.88         2
12.95         2
110.48        2
26.47         2
43.91         2
51.38         2
13.63         2
38.34         2
63.53         2
94.23         2
61.95         2
39.08         2
77.63         2
14.67         2
13.80         2
17.68         2
18.30         2
37.14         2
71.86         2
28.47         2
26.33         2
27.44         2
20.27         2
69.85         2
36.08         2
4.98          2
3.06          2
21.48         2
48.09         2
55.24         2
32.74         2
12.62         2
37.31         2
55.87         2
43.52         2
3.11          2
10.88         2
65.75         2
35.45         2
40.14         2
52.58         2
3.36          2
9.10          2
5.93          2
77.53         2
23.34         2
47.97         2
15.44         2
67.82         2
76.35         2
22.29         2
9.64          2
82.53         2
120.11        2
8.71          2
9.19          2
32.19         2
19.41         2
46.46         2
5.18          2
37.62         2
44.26         2
61.24         2
79.50         2
4.34          2
37.21         2
55.49         2
11.78         2
49.72         2
39.78         2
26.30         2
59.69         2
45.38         2
40.80         2
35.60         2
17.04         2
28.40         2
38.52         2
60.35         2
15.34         2
55.86         2
14.62         2
67.43         2
54.89         2
82.64         2
26.22         2
12.47         2
12.10         2
53.74         2
18.15         2
20.87         2
62.03         2
6.53          2
107.69        2
29.23         2
58.20         2
8.25          2
20.42         2
44.88         2
22.34         2
45.98         2
33.74         2
6.39          2
40.42         2
24.59         2
30.76         2
48.24         2
75.56         2
7.90          2
65.95         2
143.68        2
3.76          2
18.13         2
37.09         2
31.81         2
30.74         2
59.65         2
24.72         2
22.55         2
4.49          2
2.97          2
31.82         2
52.99         2
53.58         2
10.40         2
20.48         2
49.88         2
67.72         2
109.11        2
65.57         2
19.57         2
33.89         2
34.04         2
36.40         2
43.74         2
33.43         2
70.03         2
10.65         2
43.29         2
86.01         2
10.23         2
5.81          2
14.36         2
6.23          2
35.74         2
22.59         2
34.95         2
28.33         2
93.53         2
20.83         2
32.26         2
53.80         2
21.57         2
86.62         2
5.96          2
29.24         2
29.84         2
37.71         2
32.23         2
66.06         2
54.05         2
23.22         2
39.76         2
32.39         2
29.47         2
71.79         2
1.32          2
33.34         2
44.99         2
11.25         2
71.25         2
10.61         2
119.64        2
23.95         2
53.02         2
44.70         2
63.00         2
42.66         2
35.90         2
22.88         2
46.31         2
8.90          2
18.68         2
43.28         2
45.12         2
124.05        2
57.51         2
42.77         2
46.20         2
13.18         2
20.70         2
36.33         2
18.82         2
26.73         2
23.58         2
10.21         2
38.92         2
15.21         2
2.93          2
61.56         2
76.68         2
42.28         2
44.69         2
55.97         2
18.25         2
61.93         2
44.25         2
20.30         2
37.49         2
113.13        2
15.91         2
0.86          2
40.79         2
35.51         2
27.19         2
47.01         2
18.22         2
32.82         2
26.52         2
26.06         2
31.17         2
36.89         2
19.78         2
64.06         2
28.50         2
23.62         2
171.14        2
25.92         2
45.69         2
6.69          2
113.60        2
34.45         2
88.79         2
34.48         2
3.91          2
41.45         2
6.92          2
16.03         2
72.55         2
46.64         2
25.06         2
14.50         2
57.11         2
48.56         2
65.21         2
35.56         2
36.61         2
55.14         2
37.28         2
30.31         2
17.86         2
102.22        2
30.98         2
19.72         2
13.09         2
35.57         2
1.83          2
69.19         2
63.96         2
36.91         2
33.00         2
76.60         2
30.43         2
57.08         2
24.88         2
30.03         2
64.01         2
25.11         2
111.35        2
24.40         2
12.90         2
15.64         2
25.34         2
19.51         2
23.07         2
73.10         2
27.30         2
35.80         2
35.25         2
37.23         2
49.29         2
55.41         2
69.89         2
61.07         2
64.35         2
16.53         2
12.31         2
14.64         2
88.08         2
55.08         2
73.90         2
26.17         2
73.77         2
35.73         2
3.29          2
21.33         2
15.45         2
19.34         2
2.24          2
31.74         2
59.27         2
9.33          2
1.98          2
54.50         2
53.83         2
56.94         2
3.40          2
19.30         2
26.80         2
6.40          2
9.01          2
44.90         2
27.60         2
11.62         2
63.16         2
41.27         2
48.35         2
37.47         2
20.05         2
88.76         2
28.67         2
40.68         2
65.17         2
25.33         2
1.43          2
44.43         2
118.32        2
29.59         2
30.21         1
177.58        1
23.73         1
58.91         1
39.41         1
83.80         1
148.55        1
87.64         1
25.08         1
76.27         1
16.96         1
105.57        1
28.41         1
73.85         1
38.87         1
98.04         1
199.42        1
91.24         1
44.53         1
20.17         1
55.88         1
124.83        1
5.69          1
55.65         1
34.54         1
121.81        1
33.80         1
21.52         1
62.55         1
70.30         1
79.04         1
147.94        1
108.43        1
60.55         1
54.42         1
83.05         1
82.33         1
27.05         1
15.19         1
99.65         1
40.52         1
39.33         1
56.80         1
5.07          1
239.87        1
38.46         1
24.97         1
76.33         1
10.73         1
110.51        1
143.60        1
27.36         1
45.01         1
58.66         1
79.66         1
8.47          1
36.26         1
35.16         1
26.68         1
61.81         1
32.52         1
79.95         1
64.76         1
54.14         1
100.97        1
7.87          1
138.06        1
16.22         1
137.42        1
79.20         1
53.14         1
93.80         1
155.80        1
59.50         1
47.29         1
92.64         1
106.72        1
90.14         1
111.67        1
117.25        1
112.39        1
13.60         1
87.28         1
182.71        1
69.75         1
138.37        1
79.16         1
50.00         1
33.81         1
71.72         1
12.46         1
41.15         1
100.74        1
103.81        1
56.36         1
133.73        1
39.42         1
21.67         1
99.13         1
108.57        1
42.99         1
123.56        1
28.81         1
41.48         1
134.09        1
76.22         1
73.95         1
33.46         1
147.61        1
150.78        1
231.61        1
104.56        1
65.91         1
20.46         1
46.04         1
12.75         1
6.86          1
55.05         1
19.14         1
62.73         1
27.28         1
46.26         1
84.41         1
56.55         1
198.71        1
68.69         1
20.08         1
94.77         1
78.23         1
131.35        1
57.79         1
48.48         1
78.61         1
27.94         1
166.85        1
46.48         1
15.29         1
60.73         1
4.41          1
110.29        1
26.24         1
48.98         1
101.20        1
59.36         1
27.08         1
19.67         1
33.88         1
217.95        1
28.27         1
61.96         1
46.99         1
69.36         1
25.25         1
56.72         1
54.90         1
32.33         1
157.49        1
80.40         1
17.93         1
20.93         1
215.14        1
1.47          1
107.15        1
18.18         1
43.38         1
29.68         1
22.42         1
53.93         1
228.49        1
122.53        1
44.20         1
29.37         1
33.55         1
274.10        1
21.83         1
79.43         1
22.77         1
75.74         1
23.60         1
12.83         1
31.11         1
7.51          1
46.30         1
52.79         1
28.02         1
75.55         1
17.23         1
35.36         1
61.90         1
88.74         1
119.83        1
123.74        1
26.39         1
170.34        1
40.45         1
7.60          1
19.06         1
49.65         1
49.61         1
21.61         1
23.26         1
38.01         1
40.89         1
48.37         1
225.88        1
66.87         1
49.37         1
95.25         1
23.28         1
83.23         1
62.29         1
63.54         1
52.47         1
199.71        1
61.52         1
469.31        1
31.20         1
25.39         1
38.96         1
45.37         1
27.78         1
19.75         1
23.10         1
28.11         1
110.89        1
23.61         1
88.44         1
139.65        1
310.68        1
55.15         1
49.48         1
290.89        1
109.47        1
59.20         1
131.13        1
18.81         1
62.62         1
52.24         1
200.11        1
44.30         1
2.91          1
81.16         1
33.67         1
59.35         1
213.21        1
13.20         1
33.45         1
26.71         1
23.05         1
67.56         1
115.70        1
35.42         1
136.81        1
50.22         1
30.59         1
68.56         1
30.64         1
159.28        1
66.73         1
51.91         1
33.29         1
233.59        1
30.71         1
12.66         1
19.08         1
215.89        1
56.54         1
75.22         1
76.85         1
30.11         1
79.84         1
80.18         1
77.41         1
42.91         1
27.34         1
34.78         1
27.38         1
155.46        1
43.22         1
44.23         1
6.22          1
18.51         1
57.99         1
101.85        1
165.76        1
80.28         1
135.24        1
58.26         1
40.74         1
53.19         1
21.43         1
14.65         1
64.44         1
123.33        1
56.41         1
57.30         1
48.79         1
149.13        1
10.90         1
45.52         1
14.04         1
52.68         1
45.07         1
23.46         1
55.31         1
42.27         1
10.98         1
41.76         1
53.72         1
30.24         1
46.41         1
30.22         1
17.74         1
43.75         1
47.05         1
61.48         1
136.27        1
41.68         1
104.16        1
80.77         1
12.79         1
73.06         1
24.58         1
59.29         1
31.76         1
61.16         1
148.65        1
56.48         1
44.01         1
79.86         1
72.08         1
109.42        1
102.64        1
38.88         1
34.59         1
41.90         1
36.21         1
94.41         1
54.18         1
37.45         1
70.70         1
87.60         1
46.38         1
143.89        1
49.01         1
75.78         1
202.72        1
84.40         1
228.61        1
44.16         1
36.30         1
44.00         1
59.74         1
39.58         1
84.97         1
17.88         1
45.73         1
33.18         1
37.46         1
60.40         1
33.83         1
70.26         1
37.90         1
67.99         1
57.13         1
27.29         1
24.68         1
22.75         1
70.49         1
56.22         1
117.51        1
94.30         1
238.13        1
8.13          1
47.92         1
29.28         1
105.53        1
95.50         1
12.28         1
17.00         1
44.02         1
258.87        1
23.88         1
173.82        1
19.77         1
68.41         1
35.10         1
43.90         1
25.07         1
63.31         1
60.45         1
7.56          1
103.22        1
170.73        1
16.75         1
65.42         1
101.43        1
79.85         1
208.65        1
174.57        1
106.22        1
52.03         1
83.77         1
16.16         1
86.28         1
11.13         1
78.02         1
111.51        1
81.94         1
17.58         1
179.50        1
34.44         1
8.45          1
63.95         1
77.00         1
109.43        1
67.44         1
4.64          1
44.05         1
143.93        1
10.66         1
262.91        1
70.98         1
51.30         1
54.63         1
101.57        1
17.57         1
28.65         1
60.71         1
93.46         1
110.58        1
78.05         1
89.39         1
75.01         1
11.85         1
23.38         1
25.54         1
165.18        1
49.80         1
25.56         1
37.88         1
57.41         1
23.53         1
14.08         1
68.01         1
81.78         1
208.81        1
63.67         1
9.31          1
71.50         1
9.11          1
139.75        1
32.46         1
52.74         1

In [31]:
orders["discount_amount"].astype(float)

0         0.00
1         0.00
2         0.00
3        30.17
4         0.00
         ...
25085     0.00
25086     0.00
25087     0.00
25088     0.00
25089    86.25
Name: discount_amount, Length: 25090, dtype: float64

In [44]:
check = (orders["discount_amount"].round(2) != orders["discount_amount"]) & orders["discount_amount"].notna()
orders.loc[check, "discount_amount"]

Series([], Name: discount_amount, dtype: float64)

###Check Finding: discount amount column is already a float and checks show that no values are over 2 decimal places. Manual checks show there are no other issues.

###Check: There are no missing discount amounts

In [34]:
orders["discount_amount"].isna().sum()

np.int64(0)

##1.10 shipping_cost

###Check and Finding: Shipping costs are one of four values, each of which are valid. There are no missing values either

In [36]:
orders["shipping_cost"].value_counts(dropna=False)

shipping_cost
0.00    20949
3.99     2480
4.99     1261
6.99      400
Name: count, dtype: int64

##1.11 order_total

In [38]:
orders["order_total"].value_counts()

order_total
131.45     48
88.57      47
83.64      46
181.99     46
285.23     45
           ..
422.10      1
377.67      1
111.95      1
259.93      1
1157.59     1
Name: count, Length: 15122, dtype: int64

###Issue 12 : order_total should be float values to two decimal places. However, there are values using the prefix of "£".

In [41]:
#orders["order_total"].astype(float) generates error due to "£" sign

ValueError: could not convert string to float: '£118.81'

###Proposed Fix 12 : Replace the "£" symbol with empty string directly

In [42]:
orders_temp["order_total"] = orders_temp["order_total"].str.replace("£", "")

/tmp/ipykernel_477/2771962025.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  orders_temp["order_total"] = orders_temp["order_total"].str.replace("£", "")

In [43]:
orders_temp["order_total"].astype(float)

0        208.08
1        223.48
2        109.14
3        271.56
4        591.92
          ...
25084    378.52
25085    357.98
25087    465.40
25088    391.11
25089    344.99
Name: order_total, Length: 25000, dtype: float64

In [46]:
check = (orders_temp["order_total"].round(2) != orders_temp["order_total"]) & orders_temp["order_total"].notna()
orders_temp.loc[check, "order_total"]

Series([], Name: order_total, dtype: object)

###Check Finding: order_total column is already a float and checks show that no values are over 2 decimal places. Manual checks show there are no other issues.