Disclaimer: None of this is real data, is was generated by Claude AI and is intended to simulate real world messy data. The data does not represent any real individuals and any resemblance is purely coincidence.

In [2]:
%cd /content
import os
if not os.path.exists("valley-outfitters-analysis"):
    !git clone https://github.com/LSRajan/valley-outfitters-analysis.git
%cd valley-outfitters-analysis

import pandas as pd
pd.set_option("display.max_columns", None)

/content
Cloning into 'valley-outfitters-analysis'...
remote: Enumerating objects: 60, done.
remote: Counting objects: 100% (60/60), done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 60 (delta 16), reused 49 (delta 10), pack-reused 0 (from 0)
Receiving objects: 100% (60/60), 3.90 MiB | 14.32 MiB/s, done.
Resolving deltas: 100% (16/16), done.
/content/valley-outfitters-analysis

In [3]:
orders = pd.read_csv("data/raw/orders.csv")
customers = pd.read_csv("data/raw/customers.csv")
order_items = pd.read_csv("data/raw/order_items.csv")
products = pd.read_csv("data/raw/products.csv")
returns = pd.read_csv("data/raw/returns.csv")
web_sessions = pd.read_csv("data/raw/web_sessions.csv")

# 1. Orders

In [4]:
orders.head()

,order_id,customer_id,order_date,ship_date,status,payment_method,channel,discount_code,discount_amount,shipping_cost,order_total
0,ORD-223969,C3054,2025-09-24,2025-09-26,delivered,klarna,Web,NaN,0.00,0.0,208.08
1,ORD-221807,C1857,2026-01-28,NaN,Cancelled,Gift Card,Marketplace,NaN,0.00,0.0,223.48
2,ORD-210560,C5105,2025-12-18,2025-12-24,Delivered,Card,App,NaN,0.00,0.0,109.14
3,ORD-209414,C4333,2024-07-01,2024-07-06,Delivered,Card,app,welcome10,30.17,0.0,271.56
4,ORD-219246,C5677,27.06.24,"July 01, 2024",Delivered,Apple Pay,Web,NaN,0.00,0.0,591.92

In [5]:
orders.isna().sum()

order_id               0
customer_id          383
order_date           346
ship_date           3257
status                 0
payment_method         0
channel                0
discount_code      19138
discount_amount        0
shipping_cost          0
order_total          264
dtype: int64

### Issue 01 : Duplicate rows in orders table

In [6]:
orders.duplicated().sum()

np.int64(90)

### Proposed Fix 01: There are 90 duplicated rows in the table. Solve by dropping duplicated rows.

In [7]:
orders_temp = orders.drop_duplicates().copy()

## 1.1 order_id

In [8]:
orders["order_id"].head()

0    ORD-223969
1    ORD-221807
2    ORD-210560
3    ORD-209414
4    ORD-219246
Name: order_id, dtype: object

### Check: order_id should be unique with no duplicates

In [9]:
orders_temp["order_id"].duplicated().sum()

np.int64(0)

### Check: order_id should be in the format "ORD-[id number]"

In [10]:
pattern = r"ORD-\d+"
check = orders_temp["order_id"].str.fullmatch(pattern, na = False)
check.all()

np.True_

## 1.2 customer_id

### Issue 02 : customer_id contains missing values.

In [11]:
print(orders_temp["customer_id"].isna().sum())
print(str(round(orders["customer_id"].isna().mean()*100, 2)) + "% of customer ids are missing")

382
1.53% of customer ids are missing

### Proposed Fix 02: A missing customer_id row does not make the order itself invalid, but it does break the relationship between the orders table and customers table. Any calculations involving this relationship should take this discrepancy into account, otherwise the order information can still be used without a customer id, so these rows will not be removed.

### Issue 03 : customer_id has inconsistent formatting

In [12]:
pattern = r"C\d+"
check = orders_temp["customer_id"].str.fullmatch(pattern, na = True)
check.all()

np.False_

In [13]:
orders_temp.loc[~check, "customer_id"]

96       c1730
293      c5806
1141     c5622
1418     c5260
1951     c2060
         ...
24282    c1545
24347    c5689
24780    c3382
24943    c5117
25014    c3578
Name: customer_id, Length: 123, dtype: object

### Proposed Fix 03: The customer ids that do not match the format just have a lowercase prefix. To solve, capitalize all customer IDs

In [14]:
orders_temp["customer_id"] = orders_temp["customer_id"].str.upper()

In [15]:
pattern = r"C\d+"
check = orders_temp["customer_id"].str.fullmatch(pattern, na = True)
check.all()
# There are no remaining formatting issues after capitalising.

np.True_

### Issue 04 : All customer ids in the orders table should exist inside of the customers table, but many do not.

In [16]:
customers["customer_id"].head()

0    C3082
1    C5810
2    C6231
3    C5373
4    C3666
Name: customer_id, dtype: object

In [17]:
pattern = r"C\d+"
check = customers["customer_id"].str.fullmatch(pattern, na = True)
check.all()
#all customer ids in the customers table fit the pattern, so can be compared directly

np.True_

In [18]:
check = orders_temp["customer_id"].isin(customers["customer_id"])
check.all()

np.False_

In [19]:
not_present = orders_temp.loc[~check & orders_temp["customer_id"].notna(), "customer_id"]
print(not_present.count())
print(not_present.nunique())

266
236

### Proposed Fix 04: There are 266 customer ids (236 unique) that are valid in format but do not match a customer id in the customers table. These ids can still be kept to keep a record and as it may be useful if more data was provided. However, these inconsistencies should be accounted for during exploration.

## 1.3 order_date

### Issue 05 : There are missing order dates (more are missing after replacing non-missing NA values with NA)

In [20]:
orders_temp["order_date"].isna().sum()

np.int64(344)

### Proposed Fix 05: Similar to before, individual missing values do not lose too much information and the row remains useable. These values/rows do not need adjustment.

### Issue 06 : Order date should have consistent formatting. Instead it has several values representing missing values, date-time instead of just date, and different representations of dates. Standard date should be YYYY-MM-DD.

In [21]:
orders_temp["order_date"].value_counts()

order_date
2026-09-30             103
0000-00-00              66
TBC                     65
unknown                 62
2026-09-14              44
                      ...
2026-03-13 15:45:56      1
2026-08-21 11:20:12      1
2025-12-28 17:24:58      1
2025-04-30 15:08:17      1
2025-03-06 10:32:42      1
Name: count, Length: 9940, dtype: int64

### (Partial) Proposed Fix 06: There are several non-missing NA values that can be replaced with NA. This would keep the values in order date as date types and keep consistent formatting for unknown order dates.

In [22]:
non_missing_na = ["TBC", "unknown", "0000-00-00"]
orders_temp["order_date"] = orders_temp["order_date"].replace(non_missing_na, pd.NA)

In [23]:
with pd.option_context("display.max_rows", None):
    display(orders_temp["order_date"].value_counts())

order_date
2026-09-30             103
2026-09-14              44
2026-07-29              35
2025-12-25              35
2026-09-21              35
2026-09-10              35
2026-07-31              33
2025-11-09              32
2025-11-12              32
2026-05-20              32
2026-07-03              32
2026-09-15              32
2026-09-19              32
2026-06-29              31
2026-07-13              30
2026-09-24              30
2025-12-09              30
2025-11-16              30
2025-11-05              30
2026-07-22              30
2026-08-10              30
2026-04-26              29
2026-06-24              29
2025-11-22              29
2025-11-21              29
2025-11-27              29
2025-11-25              29
2026-06-16              28
2026-07-17              28
2026-09-13              28
2025-11-17              28
2026-05-27              28
2026-06-06              28
2025-12-15              28
2025-11-14              28
2025-10-11              28
2025-11-03              28
2026-06-01              28
2026-06-26              28
2026-04-05              27
2025-11-23              27
2026-08-07              27
2025-12-22              27
2026-06-23              27
2025-12-21              27
2025-11-01              27
2026-05-22              27
2025-12-08              27
2025-11-30              27
2026-06-25              27
2026-07-26              27
2025-11-07              27
2026-08-15              27
2025-12-01              27
2026-09-25              27
2025-11-10              27
2026-07-30              26
2025-12-20              26
2026-09-03              26
2026-07-16              26
2025-11-19              26
2026-07-21              26
2026-09-08              26
2026-07-14              26
2026-04-09              26
2026-09-17              26
2026-07-04              26
2025-12-31              26
2026-08-14              25
2025-12-27              25
2026-03-19              25
2025-12-23              25
2026-09-09              25
2025-11-04              25
2025-12-14              25
2026-06-28              25
2025-12-05              25
2026-07-07              25
2025-12-30              25
2026-03-21              25
2026-09-12              25
2026-06-03              25
2026-09-05              25
2026-05-19              25
2025-11-28              24
2025-12-29              24
2026-05-16              24
2026-03-31              24
2025-11-08              24
2026-04-02              24
2025-11-06              24
2025-11-24              24
2025-11-15              24
2026-03-12              23
2026-05-11              23
2026-04-21              23
2026-06-18              23
2026-03-13              23
2026-05-21              23
2026-08-29              23
2026-07-12              23
2026-06-22              23
2026-09-16              23
2025-12-03              23
2026-05-13              23
2026-05-30              23
2026-03-22              23
2026-08-01              23
2026-05-09              23
2026-08-16              23
2026-04-06              23
2026-03-02              23
2026-08-18              23
2026-08-24              23
2025-12-06              23
2026-09-07              23
2026-08-05              23
2026-03-14              23
2026-03-27              23
2025-12-18              23
2026-07-11              22
2026-08-06              22
2026-05-24              22
2026-08-11              22
2026-03-18              22
2025-11-13              22
2026-05-01              22
2026-06-09              22
2026-04-22              22
2025-11-18              22
2026-09-02              22
2025-12-02              22
2026-04-28              22
2026-05-23              22
2026-05-05              22
2026-07-01              22
2026-06-08              22
2026-05-12              22
2026-07-09              22
2025-09-21              22
2025-12-12              22
2026-05-06              22
2026-07-10              22
2026-03-25              21
2026-08-13              21
2026-09-01              21
2025-09-15              21
2026-09-26              21
2025-12-13              21
2026-06-13              21
2026-03-29              21
2026-07-15              21
2026-04-03              21
2025-12-17              21
2025-09-06              21
2026-05-29              21
2026-09-18              21
2025-09-10              20
2026-06-12              20
2026-05-07              20
2025-07-09              20
2026-08-31              20
2026-09-04              20
2026-03-26              20
2026-07-20              20
2025-08-31              20
2026-08-22              20
2025-12-11              20
2026-03-30              20
2026-05-17              20
2026-04-25              20
2026-04-19              20
2026-07-28              20
2025-07-06              20
2025-12-19              20
2026-03-11              20
2026-04-15              20
2024-12-16              20
2026-07-19              20
2026-04-11              20
2026-09-28              20
2026-06-14              20
2026-06-02              20
2026-06-10              20
2026-05-02              20
2025-11-20              20
2025-11-02              20
2026-07-02              20
2026-07-27              19
2026-08-19              19
2025-05-02              19
2026-08-21              19
2025-09-17              19
2026-09-20              19
2026-02-21              19
2026-07-05              19
2026-04-24              19
2026-04-29              19
2025-10-26              19
2026-06-20              19
2026-09-22              19
2025-12-07              19
2026-03-07              19
2025-09-30              19
2026-03-23              19
2026-03-16              19
2026-04-07              19
2026-01-05              19
2026-03-15              19
2025-11-11              19
2025-07-26              19
2025-10-23              19
2026-08-09              19
2026-06-19              19
2026-03-10              19
2026-07-18              19
2025-09-27              19
2025-06-01              18
2026-05-25              18
2025-07-22              18
2026-05-14              18
2025-12-10              18
2026-08-28              18
2026-01-06              18
2026-08-30              18
2026-02-10              18
2025-06-24              18
2025-07-17              18
2026-06-05              18
2026-02-17              18
2025-07-16              18
2026-03-04              18
2026-08-08              18
2025-09-28              18
2026-08-17              18
2025-12-16              18
2026-06-15              18
2026-08-23              18
2025-06-22              18
2026-05-03              18
2026-04-23              18
2026-07-24              18
2025-11-29              18
2026-02-04              18
2026-04-08              18
2025-10-13              17
2026-09-11              17
2026-06-30              17
2026-05-10              17
2025-06-12              17
2025-07-08              17
2026-04-30              17
2025-06-10              17
2026-05-08              17
2025-10-27              17
2025-08-06              17
2026-08-04              17
2026-09-29              17
2025-10-02              17
2026-04-17              17
2026-02-28              17
2026-06-04              17
2025-12-24              17
2026-02-03              17
2026-02-07              17
2026-03-01              17
2025-08-16              17
2025-05-14              17
2026-06-17              17
2025-07-21              17
2025-07-13              17
2025-10-07              17
2026-09-27              17
2026-01-30              17
2026-07-25              17
2025-10-16              16
2026-08-27              16
2026-07-08              16
2025-10-25              16
2025-04-28              16
2025-06-26              16
2024-11-20              16
2025-01-23              16
2026-06-27              16
2026-09-23              16
2026-01-31              16
2026-08-02              16
2026-02-14              16
2025-12-28              16
2025-09-14              16
2025-07-14              16
2025-10-08              16
2025-05-16              16
2025-09-20              16
2026-04-13              16
2025-09-05              16
2025-09-13              16
2026-04-12              16
2024-12-17              16
2026-02-15              16
2025-08-14              16
2026-03-28              16
2025-09-22              16
2026-02-19              16
2025-08-03              16
2026-02-11              16
2026-01-18              16
2026-01-28              16
2024-12-04              15
2026-08-03              15
2024-11-28              15
2025-07-03              15
2026-04-27              15
2026-01-10              15
2025-07-20              15
2026-01-17              15
2025-09-16              15
2026-02-26              15
2024-12-05              15
2026-07-23              15
2025-05-07              15
2026-02-02              15
2024-12-26              15
2026-05-15              15
2025-07-01              15
2025-09-08              15
2026-09-06              15
2026-01-19              15
2026-06-11              15
2025-08-29              15
2026-05-31              15
2026-06-07              15
2025-07-23              15
2026-03-06              15
2026-03-08              15
2025-12-04              15
2025-06-30              15
2025-07-07              15
2024-12-15              15
2024-12-20              15
2025-06-20              15
2025-06-19              15
2026-03-09              15
2026-08-20              15
2026-04-20              15
2026-04-04              15
2026-05-26              15
2026-07-06              15
2025-06-28              15
2025-05-17              15
2026-03-03              15
2025-10-04              15
2026-03-24              15
2025-09-07              14
2025-08-26              14
30.09.26                14
2024-11-04              14
2026-01-12              14
2026-04-10              14
2025-06-23              14
2025-08-07              14
2026-02-25              14
2025-07-29              14
2025-12-26              14
2025-05-21              14
2025-03-17              14
2024-12-31              14
2025-07-30              14
2026-06-21              14
2025-10-17              14
2024-11-03              14
2025-05-31              14
2026-03-05              14
2026-01-26              14
2025-07-11              14
2024-11-11              14
2026-08-25              14
2025-10-06              14
2026-03-17              14
2025-09-11              14
2025-10-28              14
30 Sep 2026             14
2025-08-04              14
2024-12-27              14
2025-08-23              13
2025-03-14              13
2025-08-20              13
2025-10-15              13
2024-11-22              13
2026-02-18              13
2025-05-06              13
2025-07-24              13
2025-09-24              13
2024-12-29              13
2025-05-30              13
2024-12-25              13
2025-05-28              13
2024-12-03              13
2025-08-22              13
2024-11-08              13
2026-02-22              13
2026-05-04              13
2024-11-21              13
2025-10-03              13
2025-07-10              13
2025-09-29              13
2026-01-16              13
2026-01-21              13
2024-12-13              13
2025-08-17              13
2026-01-14              13
2025-08-21              13
2024-12-06              13
2024-12-09              13
2026-04-16              13
2025-10-01              13
2025-06-18              13
2025-08-18              13
2025-04-29              13
2025-08-01              13
2026-02-01              13
2026-03-20              13
2026-05-28              13
2025-10-10              12
2024-11-13              12
2025-06-02              12
2025-10-30              12
2024-11-24              12
2026-01-07              12
2025-06-16              12
2025-10-14              12
2026-01-29              12
2025-11-26              12
2025-08-10              12
2025-07-02              12
2025-06-08              12
2026-01-23              12
2025-06-29              12
2025-10-21              12
2025-08-05              12
2025-09-12              12
2024-12-23              12
2024-12-18              12
2025-09-04              12
2025-08-28              12
2025-04-24              12
2025-09-09              12
2026-04-18              12
2025-07-31              12
2025-05-27              12
2026-01-03              12
2025-09-02              12
2025-06-21              12
2025-01-15              12
2025-05-09              12
2026-01-24              12
2025-05-24              12
2026-02-16              12
2026-01-22              12
2024-12-01              12
2025-03-02              11
2026-01-15              11
2025-09-03              11
September 30, 2026      11
2024-10-08              11
2025-09-19              11
2026-04-01              11
2025-08-13              11
2025-03-31              11
2025-09-18              11
2024-11-09              11
2024-11-30              11
2025-04-27              11
2025-10-31              11
2025-06-15              11
2025-05-23              11
2026-05-18              11
2025-03-01              11
2024-11-17              11
2026-01-11              11
2026-01-27              11
2025-04-07              11
2024-11-16              11
2025-06-17              11
2025-07-18              11
2024-12-08              11
2026-02-20              11
2026-02-09              11
2025-05-11              11
2024-11-05              11
2024-12-14              11
2025-07-28              11
2025-06-09              11
2025-03-06              11
2025-08-25              11
2024-12-12              11
2025-03-26              11
2025-08-11              11
2024-11-27              11
2024-12-10              11
2025-04-08              11
2025-09-23              11
2026-08-26              11
2024-11-02              11
2025-01-26              11
2026-02-12              10
2024-07-07              10
2025-03-15              10
2025-03-22              10
2024-07-10              10
2025-04-01              10
2025-03-29              10
2026-02-08              10
2026-08-12              10
2026-01-25              10
2024-11-25              10
2025-06-14              10
2024-11-14              10
2025-10-18              10
2025-03-11              10
2025-08-09              10
09-30-2026              10
2025-04-15              10
2025-04-17              10
2024-10-28              10
2025-09-26              10
2025-01-28              10
2025-10-24              10
2025-08-27              10
2024-11-06              10
2025-04-02              10
2025-03-12              10
2025-02-11              10
2025-02-13              10
2025-02-23              10
2025-10-09              10
2026-02-13              10
2025-03-25              10
2026-01-04              10
2025-10-12              10
2025-01-12              10
2026-01-13              10
2025-02-24              10
2024-12-21              10
2024-11-19              10
2025-04-12              10
2025-06-27              10
2025-06-07              10
2025-06-05              10
2025-07-05              10
2024-11-10              10
2025-08-19              10
2025-07-12              10
2025-05-01              10
2024-09-11              10
2025-10-05              10
2025-10-20              10
2026-01-08              10
2025-05-08               9
2025-08-08               9
2025-04-22               9
2025-03-21               9
2026-02-24               9
2025-03-18               9
2025-05-05               9
2024-06-27               9
2025-03-16               9
2025-07-04               9
2026/09/30               9
2024-12-22               9
2026-01-01               9
2026-02-05               9
2025-04-04               9
2024-12-24               9
2025-02-14               9
30/09/2026               9
2025-02-26               9
2025-07-25               9
2025-02-20               9
2025-06-25               9
2025-03-20               9
2026-01-02               9
2025-05-25               9
2025-02-21               9
2025-06-06               9
2025-02-28               9
2025-10-19               9
2025-02-16               9
2025-04-30               9
2025-03-19               9
2024-08-31               8
2025-05-13               8
2025-05-29               8
2024-06-23               8
2025-02-25               8
2024-07-14               8
2024-12-28               8
2026-01-20               8
2025-04-20               8
2025-04-26               8
2025-01-14               8
2025-05-22               8
2024-09-16               8
September 03, 2025       8
2024-11-23               8
2025-08-02               8
2024-12-07               8
05/11/2025               8
2026/07/16               8
2024-10-04               8
2025-06-03               8
2024-11-12               8
2025-02-17               8
2024-07-11               8
2025-08-12               8
2026-04-14               8
2024-12-19               8
2025-04-18               8
2025-01-20               8
2025-04-09               8
2025-08-15               8
2024-07-17               8
2025-01-16               8
August 15, 2026          8
2025-04-06               8
2025-09-25               8
2025-05-04               8
2025-05-15               8
2025-01-03               8
2024-11-15               8
2024-08-27               8
2025-03-05               8
2025-05-12               8
2024-09-13               8
2025-03-03               8
2025-05-03               8
2024-07-08               8
2024-09-26               8
2025-08-24               8
2024-06-13               8
2024-09-19               7
2025-04-10               7
12-31-2025               7
2024-09-29               7
2024-09-23               7
2026-02-27               7
2026-01-09               7
2024-06-26               7
2024-09-14               7
November 25, 2025        7
2025-01-29               7
2025-05-19               7
2025-02-19               7
21 Dec 2025              7
2024-11-01               7
September 27, 2026       7
2025-10-22               7
2025-04-14               7
2025-04-21               7
May 10, 2026             7
2024-10-23               7
2025-02-27               7
2025-03-27               7
2025-03-24               7
May 30, 2026             7
29/06/2026               7
2025-01-24               7
06/07/2026               7
26.11.25                 7
2025-10-29               7
2025-07-19               7
2025/11/29               7
2024-10-11               7
2025-03-13               7
2024-08-13               7
2024-11-26               7
2025-03-30               7
2026-02-23               7
2025-06-11               7
2025-05-20               7
17.09.26                 7
2025-01-06               7
2025-06-13               7
2024-11-29               7
2025-01-04               7
2025-04-03               7
2024-12-02               7
2025-01-22               7
2025-06-04               7
2025-02-06               7
2024-07-22               7
2024-12-11               7
2024-07-04               7
23/06/2025               7
2024-07-30               7
2025-01-27               7
2025-02-05               6
2024-11-18               6
2024-06-01               6
2024-12-30               6
30 Jun 2025              6
2026/09/03               6
2024-09-07               6
2024-08-20               6
2024-07-27               6
31 Jul 2026              6
07-31-2026               6
2025-04-05               6
2025-09-01               6
November 17, 2025        6
19.08.26                 6
2024-09-08               6
2025-01-13               6
2024-06-15               6
31/12/2025               6
09-11-2026               6
2025-04-13               6
November 13, 2025        6
12-16-2025               6
08-09-2026               6
22 Dec 2025              6
November 08, 2025        6
2026/08/08               6
2025-02-08               6
2024-07-12               6
03 Aug 2025              6
21/09/2026               6
2024-08-07               6
2026/09/15               6
2024-06-08               6
2024-07-13               6
09 Jul 2026              6
2024-07-18               6
03.03.26                 6
2024-07-16               6
2025-02-09               6
09-06-2026               6
20.07.26                 6
2024-07-19               6
07 May 2025              6

In [24]:
pattern = r"\d{4}-\d{2}-\d{2}"
check = orders_temp["order_date"].str.fullmatch(pattern, na=False)
incorrect_dates = orders_temp.loc[~check & orders_temp["order_date"].notna(), "order_date"]
incorrect_dates.value_counts()

order_date
30 Sep 2026            14
30.09.26               14
September 30, 2026     11
09-30-2026             10
30/09/2026              9
                       ..
2024-09-25 17:20:35     1
2026-02-05 15:12:27     1
31.10.24                1
May 08, 2024            1
2026-05-09 14:56:41     1
Name: count, Length: 8954, dtype: int64

### Proposed Fix 06: The remaining values are just in the wrong time formats. Get the values by their format and convert those into the correct format. Any remaining values not in a given format can be handled manually.

## 1.4 ship_date

### Issue 07 : (Same issues as order date) Ship date should have consistent formatting. Instead it has several values representing missing values, date-time instead of just date, and different representations of dates. Standard date should be YYYY-MM-DD. Many dates are invalid too.

In [25]:
orders_temp["ship_date"].value_counts()

ship_date
TBC               52
0000-00-00        50
2025-11-09        49
2026-07-23        48
unknown           45
                  ..
15.05.25           1
March 31, 2024     1
July 01, 2024      1
06-07-2025         1
12-23-2024         1
Name: count, Length: 4505, dtype: int64

### Proposed Fix 07 : Same fix as previous date fixes. Replace invalid dates with NA.

## 1.5 status

### Issue 08 : While status has a fixed set of possible values, the rows contain many variations, mispellings, or capitalisations of the same value.

In [26]:
orders_temp["status"].value_counts()

status
Delivered      14899
Cancelled       1348
completed       1036
DELIVERED       1016
Complete         991
Returned         988
Deliverd         987
delivered        986
Shipped          775
Pending          386
Processing       332
cancelled        129
RETURNED         118
CANCELLED        113
cancled          112
Return           108
Canceled         108
returned         100
SHIPPED           84
In transit        80
shipped           67
processing        59
In progress       52
Pending           45
pending           41
PENDING           40
Name: count, dtype: int64

In [27]:
orders_temp["status"].str.strip().str.lower().value_counts()

status
delivered      16901
cancelled       1590
returned        1206
completed       1036
complete         991
deliverd         987
shipped          926
pending          512
processing       391
cancled          112
return           108
canceled         108
in transit        80
in progress       52
Name: count, dtype: int64

### Proposed Fix 08: These values can be stripped and lowered, followed by manually fixing spelling errors and ensuring one consistent label rather than several labels for the same underlying meaning.

## 1.6 payment_method

### Issue 09 : While payment method has a fixed set of possible values, the rows contain many variations, mispellings, or capitalisations of the same value. There are also different versions for abbreviated or spaced values.

In [28]:
orders_temp["payment_method"].value_counts()

payment_method
PayPal         4041
Apple Pay      4035
Gift Card      4003
Klarna         3968
Card           3927
klarna          508
Giftcard        506
ApplePay        501
apple pay       492
gift card       487
KLARNA          457
Paypal          357
paypal          331
PP              310
Debit card      292
card            265
CARD            264
Credit Card     256
Name: count, dtype: int64

### Proposed Fix 09: These values can be stripped and lowered, followed by manually fixing spelling errors and ensuring one consistent label rather than several labels for the same underlying meaning.

## 1.7 channel

### Issue 10 : While channel has a fixed set of possible values, the rows contain many variations, mispellings, or capitalisations of the same value. There are also different versions for abbreviated or spaced values.

In [29]:
orders_temp["channel"].value_counts()

channel
Web            11216
App             5529
Marketplace     2685
In-store        1148
web              811
WEB              804
Online           797
Phone            660
APP              379
app              352
MARKETPLACE      189
marketplace      176
IN-STORE          87
in-store          79
phone             49
PHONE             39
Name: count, dtype: int64

### Proposed Fix 10: These values can be stripped and lowered, followed by manually fixing spelling errors and ensuring one consistent label rather than several labels for the same underlying meaning.

## 1.8 discount_code

### Issue 11 : The discount code column appears to have many different variations of the same discount code. For example, 'welcome10', 'Welcome10', 'WELCOME10'. The reasonable assumption is that discount codes are not case sensitive and that these are all the same code. However it should be noted that they might actually be distinct, and that might cause an error later on.

In [30]:
orders_temp["discount_code"].value_counts()

discount_code
WELCOME10     1709
SUMMER20      1301
FREESHIP      1024
LOYAL15        872
BF25           128
welcome10      110
WELCOME10      101
Welcome10      101
Summer20        76
SUMMER20        74
summer20        71
Freeship        68
freeship        65
LOYAL15         62
FREESHIP        55
loyal15         52
Loyal15         41
BF25             8
Bf25             8
bf25             8
Name: count, dtype: int64

### Proposed Fix 11: These values can be stripped and lowered, followed by manually fixing spelling errors and ensuring one consistent label rather than several labels for the same underlying discount code. Possible downstream errors should be considered if an issue arises.

## 1.9 discount_amount

### Check: discount amount should be float values to two decimal points

In [31]:
with pd.option_context("display.max_rows", None):
    display(orders_temp["discount_amount"].value_counts())

discount_amount
0.00      20278
9.76         12
1.96         11
4.55         11
4.54         10
0.72         10
18.56        10
8.30          9
20.65         9
15.01         9
51.21         9
7.62          9
5.46          9
4.23          8
35.49         8
9.08          8
11.88         8
9.15          8
13.58         8
16.28         8
8.95          8
34.23         8
7.66          8
3.93          8
8.63          7
2.27          7
15.56         7
19.52         7
19.98         7
13.92         7
4.61          7
10.34         7
21.39         7
5.83          7
20.02         7
19.49         7
55.33         7
4.27          7
18.50         7
19.81         7
26.61         7
8.21          7
3.65          7
16.71         6
20.28         6
25.60         6
8.97          6
20.36         6
22.02         6
9.77          6
10.04         6
26.79         6
13.32         6
9.72          6
15.52         6
62.44         6
26.63         6
8.98          6
15.53         6
26.57         6
12.19         6
3.26          6
27.85         6
5.17          6
4.75          6
1.22          6
9.94          6
34.66         6
38.42         6
9.51          6
8.96          6
34.08         6
12.55         6
31.22         6
4.97          6
13.46         6
11.74         6
7.33          6
19.54         6
49.18         6
4.26          5
9.67          5
5.25          5
6.81          5
37.78         5
5.01          5
10.22         5
7.31          5
5.06          5
13.28         5
8.14          5
10.74         5
18.29         5
7.97          5
3.28          5
60.90         5
22.35         5
27.53         5
15.32         5
31.12         5
47.89         5
44.04         5
2.90          5
7.50          5
8.86          5
4.33          5
5.61          5
59.19         5
3.56          5
27.15         5
16.83         5
9.48          5
17.92         5
12.43         5
6.73          5
2.96          5
6.45          5
13.38         5
11.69         5
31.71         5
7.44          5
7.12          5
49.25         5
23.32         5
3.47          5
7.45          5
6.54          5
8.54          5
14.88         5
38.30         5
8.37          5
13.77         5
40.41         5
5.84          5
9.37          5
24.86         5
12.44         5
20.98         5
4.48          4
40.11         4
27.66         4
5.11          4
28.52         4
11.65         4
19.44         4
30.17         4
31.62         4
17.30         4
16.13         4
3.37          4
5.92          4
31.01         4
2.63          4
23.71         4
2.51          4
13.31         4
13.29         4
13.37         4
1.11          4
11.67         4
12.20         4
37.13         4
10.33         4
10.67         4
23.16         4
18.74         4
35.92         4
4.86          4
30.02         4
4.15          4
15.00         4
2.22          4
8.07          4
45.95         4
113.33        4
7.76          4
29.01         4
24.38         4
5.34          4
1.72          4
6.32          4
19.21         4
24.62         4
15.47         4
28.72         4
3.94          4
38.06         4
27.59         4
7.25          4
4.45          4
8.52          4
26.29         4
6.75          4
7.79          4
42.78         4
6.07          4
22.51         4
3.04          4
5.97          4
63.40         4
11.23         4
1.75          4
10.91         4
6.64          4
20.85         4
3.32          4
6.56          4
16.80         4
45.15         4
15.59         4
36.94         4
22.82         4
3.98          4
5.48          4
6.10          4
22.46         4
13.02         3
12.12         3
50.56         3
30.50         3
41.30         3
28.94         3
17.50         3
4.92          3
13.41         3
12.60         3
44.60         3
4.88          3
61.10         3
7.72          3
27.67         3
71.44         3
16.89         3
7.74          3
22.44         3
9.22          3
15.54         3
21.92         3
20.21         3
57.44         3
63.35         3
17.82         3
4.58          3
5.94          3
45.26         3
74.01         3
15.25         3
35.72         3
24.24         3
10.93         3
19.03         3
5.78          3
10.49         3
19.79         3
27.96         3
11.16         3
62.18         3
64.86         3
19.15         3
51.89         3
33.52         3
41.43         3
20.88         3
7.13          3
27.57         3
0.88          3
24.47         3
12.63         3
5.87          3
11.09         3
20.47         3
14.23         3
18.20         3
10.43         3
8.16          3
6.68          3
30.36         3
45.68         3
11.00         3
1.69          3
43.50         3
25.01         3
14.52         3
27.62         3
34.94         3
4.67          3
5.37          3
3.95          3
33.86         3
4.47          3
3.33          3
24.85         3
17.77         3
25.10         3
33.36         3
38.83         3
27.83         3
17.33         3
18.45         3
0.98          3
27.84         3
16.36         3
15.55         3
58.08         3
36.90         3
4.31          3
8.36          3
37.51         3
43.24         3
9.75          3
42.90         3
29.04         3
9.89          3
29.60         3
22.97         3
12.80         3
3.38          3
17.95         3
110.66        3
14.63         3
35.83         3
1.66          3
41.85         3
18.46         3
2.92          3
8.73          3
16.74         3
43.79         3
23.30         3
13.21         3
37.00         3
5.90          3
34.88         3
49.13         3
6.49          3
8.75          3
38.40         3
18.54         3
6.71          3
5.82          3
6.13          3
42.81         3
32.32         3
16.00         3
17.66         3
13.91         3
45.53         2
27.82         2
30.45         2
29.34         2
38.63         2
46.52         2
21.21         2
13.14         2
19.80         2
24.67         2
47.42         2
44.29         2
41.94         2
30.85         2
55.06         2
30.07         2
35.31         2
41.96         2
72.46         2
7.52          2
8.46          2
9.27          2
13.47         2
45.59         2
69.84         2
33.39         2
69.41         2
107.31        2
67.25         2
16.31         2
66.04         2
83.18         2
45.64         2
7.42          2
6.51          2
15.81         2
39.04         2
130.11        2
49.66         2
15.86         2
26.74         2
18.65         2
33.40         2
66.91         2
41.08         2
70.01         2
18.83         2
23.29         2
9.23          2
72.06         2
50.92         2
73.87         2
122.94        2
23.78         2
30.26         2
75.02         2
34.74         2
37.29         2
15.06         2
53.65         2
11.49         2
55.18         2
5.79          2
33.04         2
42.70         2
12.89         2
61.15         2
30.63         2
56.85         2
19.97         2
11.89         2
28.28         2
22.30         2
78.03         2
73.48         2
24.45         2
12.23         2
54.15         2
35.82         2
32.84         2
14.24         2
43.56         2
42.60         2
45.65         2
22.21         2
26.00         2
5.20          2
13.88         2
42.06         2
82.99         2
4.59          2
55.51         2
31.40         2
14.47         2
9.65          2
48.76         2
59.87         2
6.35          2
27.14         2
23.81         2
21.46         2
7.32          2
31.05         2
42.12         2
31.09         2
69.14         2
65.85         2
20.07         2
10.10         2
33.08         2
75.91         2
1.07          2
24.25         2
23.98         2
9.25          2
6.82          2
10.78         2
97.59         2
72.89         2
18.05         2
71.62         2
36.88         2
12.95         2
110.48        2
26.47         2
43.91         2
51.38         2
13.63         2
38.34         2
63.53         2
94.23         2
61.95         2
39.08         2
77.63         2
14.67         2
13.80         2
17.68         2
18.30         2
37.14         2
71.86         2
28.47         2
26.33         2
27.44         2
20.27         2
69.85         2
36.08         2
4.98          2
3.06          2
21.48         2
48.09         2
55.24         2
32.74         2
12.62         2
37.31         2
55.87         2
43.52         2
3.11          2
10.88         2
65.75         2
35.45         2
40.14         2
52.58         2
3.36          2
9.10          2
5.93          2
77.53         2
23.34         2
47.97         2
15.44         2
67.82         2
76.35         2
22.29         2
9.64          2
82.53         2
120.11        2
8.71          2
9.19          2
32.19         2
19.41         2
46.46         2
5.18          2
37.62         2
44.26         2
61.24         2
79.50         2
4.34          2
37.21         2
55.49         2
11.78         2
49.72         2
39.78         2
26.30         2
59.69         2
45.38         2
40.80         2
35.60         2
17.04         2
28.40         2
38.52         2
60.35         2
15.34         2
55.86         2
14.62         2
67.43         2
54.89         2
82.64         2
26.22         2
12.47         2
12.10         2
53.74         2
18.15         2
20.87         2
62.03         2
6.53          2
107.69        2
29.23         2
58.20         2
8.25          2
20.42         2
44.88         2
22.34         2
45.98         2
33.74         2
6.39          2
40.42         2
24.59         2
30.76         2
48.24         2
75.56         2
7.90          2
65.95         2
143.68        2
3.76          2
18.13         2
37.09         2
31.81         2
30.74         2
59.65         2
24.72         2
22.55         2
4.49          2
2.97          2
31.82         2
52.99         2
53.58         2
10.40         2
20.48         2
49.88         2
67.72         2
109.11        2
65.57         2
19.57         2
33.89         2
34.04         2
36.40         2
43.74         2
33.43         2
70.03         2
10.65         2
43.29         2
86.01         2
10.23         2
5.81          2
14.36         2
6.23          2
35.74         2
22.59         2
34.95         2
28.33         2
93.53         2
20.83         2
32.26         2
53.80         2
21.57         2
86.62         2
5.96          2
29.24         2
29.84         2
37.71         2
32.23         2
66.06         2
54.05         2
23.22         2
39.76         2
32.39         2
29.47         2
71.79         2
1.32          2
33.34         2
44.99         2
11.25         2
71.25         2
10.61         2
119.64        2
23.95         2
53.02         2
44.70         2
63.00         2
42.66         2
35.90         2
22.88         2
46.31         2
8.90          2
18.68         2
43.28         2
45.12         2
124.05        2
57.51         2
42.77         2
46.20         2
13.18         2
20.70         2
36.33         2
18.82         2
26.73         2
23.58         2
10.21         2
38.92         2
15.21         2
2.93          2
61.56         2
76.68         2
42.28         2
44.69         2
55.97         2
18.25         2
61.93         2
44.25         2
20.30         2
37.49         2
113.13        2
15.91         2
0.86          2
40.79         2
35.51         2
27.19         2
47.01         2
18.22         2
32.82         2
26.52         2
26.06         2
31.17         2
36.89         2
19.78         2
64.06         2
28.50         2
23.62         2
171.14        2
25.92         2
45.69         2
6.69          2
113.60        2
34.45         2
88.79         2
34.48         2
3.91          2
41.45         2
6.92          2
16.03         2
72.55         2
46.64         2
25.06         2
14.50         2
57.11         2
48.56         2
65.21         2
35.56         2
36.61         2
55.14         2
37.28         2
30.31         2
17.86         2
102.22        2
30.98         2
19.72         2
13.09         2
35.57         2
1.83          2
69.19         2
63.96         2
36.91         2
33.00         2
76.60         2
30.43         2
57.08         2
24.88         2
30.03         2
64.01         2
25.11         2
111.35        2
24.40         2
12.90         2
15.64         2
25.34         2
19.51         2
23.07         2
73.10         2
27.30         2
35.80         2
35.25         2
37.23         2
49.29         2
55.41         2
69.89         2
61.07         2
64.35         2
16.53         2
12.31         2
14.64         2
88.08         2
55.08         2
73.90         2
26.17         2
73.77         2
35.73         2
3.29          2
21.33         2
15.45         2
19.34         2
2.24          2
31.74         2
59.27         2
9.33          2
1.98          2
54.50         2
53.83         2
56.94         2
3.40          2
19.30         2
26.80         2
6.40          2
9.01          2
44.90         2
27.60         2
11.62         2
63.16         2
41.27         2
48.35         2
37.47         2
20.05         2
88.76         2
28.67         2
40.68         2
65.17         2
25.33         2
1.43          2
44.43         2
118.32        2
29.59         2
30.21         1
177.58        1
23.73         1
58.91         1
39.41         1
83.80         1
148.55        1
87.64         1
25.08         1
76.27         1
16.96         1
105.57        1
28.41         1
73.85         1
38.87         1
98.04         1
199.42        1
91.24         1
44.53         1
20.17         1
55.88         1
124.83        1
5.69          1
55.65         1
34.54         1
121.81        1
33.80         1
21.52         1
62.55         1
70.30         1
79.04         1
147.94        1
108.43        1
60.55         1
54.42         1
83.05         1
82.33         1
27.05         1
15.19         1
99.65         1
40.52         1
39.33         1
56.80         1
5.07          1
239.87        1
38.46         1
24.97         1
76.33         1
10.73         1
110.51        1
143.60        1
27.36         1
45.01         1
58.66         1
79.66         1
8.47          1
36.26         1
35.16         1
26.68         1
61.81         1
32.52         1
79.95         1
64.76         1
54.14         1
100.97        1
7.87          1
138.06        1
16.22         1
137.42        1
79.20         1
53.14         1
93.80         1
155.80        1
59.50         1
47.29         1
92.64         1
106.72        1
90.14         1
111.67        1
117.25        1
112.39        1
13.60         1
87.28         1
182.71        1
69.75         1
138.37        1
79.16         1
50.00         1
33.81         1
71.72         1
12.46         1
41.15         1
100.74        1
103.81        1
56.36         1
133.73        1
39.42         1
21.67         1
99.13         1
108.57        1
42.99         1
123.56        1
28.81         1
41.48         1
134.09        1
76.22         1
73.95         1
33.46         1
147.61        1
150.78        1
231.61        1
104.56        1
65.91         1
20.46         1
46.04         1
12.75         1
6.86          1
55.05         1
19.14         1
62.73         1
27.28         1
46.26         1
84.41         1
56.55         1
198.71        1
68.69         1
20.08         1
94.77         1
78.23         1
131.35        1
57.79         1
48.48         1
78.61         1
27.94         1
166.85        1
46.48         1
15.29         1
60.73         1
4.41          1
110.29        1
26.24         1
48.98         1
101.20        1
59.36         1
27.08         1
19.67         1
33.88         1
217.95        1
28.27         1
61.96         1
46.99         1
69.36         1
25.25         1
56.72         1
54.90         1
32.33         1
157.49        1
80.40         1
17.93         1
20.93         1
215.14        1
1.47          1
107.15        1
18.18         1
43.38         1
29.68         1
22.42         1
53.93         1
228.49        1
122.53        1
44.20         1
29.37         1
33.55         1
274.10        1
21.83         1
79.43         1
22.77         1
75.74         1
23.60         1
12.83         1
31.11         1
7.51          1
46.30         1
52.79         1
28.02         1
75.55         1
17.23         1
35.36         1
61.90         1
88.74         1
119.83        1
123.74        1
26.39         1
170.34        1
40.45         1
7.60          1
19.06         1
49.65         1
49.61         1
21.61         1
23.26         1
38.01         1
40.89         1
48.37         1
225.88        1
66.87         1
49.37         1
95.25         1
23.28         1
83.23         1
62.29         1
63.54         1
52.47         1
199.71        1
61.52         1
469.31        1
31.20         1
25.39         1
38.96         1
45.37         1
27.78         1
19.75         1
23.10         1
28.11         1
110.89        1
23.61         1
88.44         1
139.65        1
310.68        1
55.15         1
49.48         1
290.89        1
109.47        1
59.20         1
131.13        1
18.81         1
62.62         1
52.24         1
200.11        1
44.30         1
2.91          1
81.16         1
33.67         1
59.35         1
213.21        1
13.20         1
33.45         1
26.71         1
23.05         1
67.56         1
115.70        1
35.42         1
136.81        1
50.22         1
30.59         1
68.56         1
30.64         1
159.28        1
66.73         1
51.91         1
33.29         1
233.59        1
30.71         1
12.66         1
19.08         1
215.89        1
56.54         1
75.22         1
76.85         1
30.11         1
79.84         1
80.18         1
77.41         1
42.91         1
27.34         1
34.78         1
27.38         1
155.46        1
43.22         1
44.23         1
6.22          1
18.51         1
57.99         1
101.85        1
165.76        1
80.28         1
135.24        1
58.26         1
40.74         1
53.19         1
21.43         1
14.65         1
64.44         1
123.33        1
56.41         1
57.30         1
48.79         1
149.13        1
10.90         1
45.52         1
14.04         1
52.68         1
45.07         1
23.46         1
55.31         1
42.27         1
10.98         1
41.76         1
53.72         1
30.24         1
46.41         1
30.22         1
17.74         1
43.75         1
47.05         1
61.48         1
136.27        1
41.68         1
104.16        1
80.77         1
12.79         1
73.06         1
24.58         1
59.29         1
31.76         1
61.16         1
148.65        1
56.48         1
44.01         1
79.86         1
72.08         1
109.42        1
102.64        1
38.88         1
34.59         1
41.90         1
36.21         1
94.41         1
54.18         1
37.45         1
70.70         1
87.60         1
46.38         1
143.89        1
49.01         1
75.78         1
202.72        1
84.40         1
228.61        1
44.16         1
36.30         1
44.00         1
59.74         1
39.58         1
84.97         1
17.88         1
45.73         1
33.18         1
37.46         1
60.40         1
33.83         1
70.26         1
37.90         1
67.99         1
57.13         1
27.29         1
24.68         1
22.75         1
70.49         1
56.22         1
117.51        1
94.30         1
238.13        1
8.13          1
47.92         1
29.28         1
105.53        1
95.50         1
12.28         1
17.00         1
44.02         1
258.87        1
23.88         1
173.82        1
19.77         1
68.41         1
35.10         1
43.90         1
25.07         1
63.31         1
60.45         1
7.56          1
103.22        1
170.73        1
16.75         1
65.42         1
101.43        1
79.85         1
208.65        1
174.57        1
106.22        1
52.03         1
83.77         1
16.16         1
86.28         1
11.13         1
78.02         1
111.51        1
81.94         1
17.58         1
179.50        1
34.44         1
8.45          1
63.95         1
77.00         1
109.43        1
67.44         1
4.64          1
44.05         1
143.93        1
10.66         1
262.91        1
70.98         1
51.30         1
54.63         1
101.57        1
17.57         1
28.65         1
60.71         1
93.46         1
110.58        1
78.05         1
89.39         1
75.01         1
11.85         1
23.38         1
25.54         1
165.18        1
49.80         1
25.56         1
37.88         1
57.41         1
23.53         1
14.08         1
68.01         1
81.78         1
208.81        1
63.67         1
9.31          1
71.50         1
9.11          1
139.75        1
32.46         1
52.74         1

In [32]:
orders_temp["discount_amount"].astype(float)

0         0.00
1         0.00
2         0.00
3        30.17
4         0.00
         ...
25084     0.00
25085     0.00
25087     0.00
25088     0.00
25089    86.25
Name: discount_amount, Length: 25000, dtype: float64

In [33]:
check = (orders_temp["discount_amount"].round(2) != orders_temp["discount_amount"]) & orders_temp["discount_amount"].notna()
orders_temp.loc[check, "discount_amount"]

Series([], Name: discount_amount, dtype: float64)

### Check Finding: discount amount column is already a float and checks show that no values are over 2 decimal places. Manual checks show there are no other issues.

### Check: There are no missing discount amounts

In [34]:
orders_temp["discount_amount"].isna().sum()

np.int64(0)

## 1.10 shipping_cost

### Check and Finding: Shipping costs are one of four values, each of which are valid. There are no missing values either

In [35]:
orders_temp["shipping_cost"].value_counts(dropna=False)

shipping_cost
0.00    20871
3.99     2472
4.99     1258
6.99      399
Name: count, dtype: int64

## 1.11 order_total

In [36]:
orders_temp["order_total"].value_counts()

order_total
131.45    47
88.57     47
83.64     46
181.99    46
133.17    45
          ..
415.88     1
927.30     1
140.10     1
422.10     1
377.67     1
Name: count, Length: 15122, dtype: int64

### Issue 12 : order_total should be float values to two decimal places. However, there are values using the prefix of "£".

In [37]:
#orders_temp["order_total"].astype(float) generates error due to "£" sign

### Proposed Fix 12 : Replace the "£" symbol with empty string directly

In [38]:
orders_temp["order_total"] = orders_temp["order_total"].str.replace("£", "").astype(float)

In [39]:
orders_temp["order_total"]

0        208.08
1        223.48
2        109.14
3        271.56
4        591.92
          ...
25084    378.52
25085    357.98
25087    465.40
25088    391.11
25089    344.99
Name: order_total, Length: 25000, dtype: float64

### Issue 13 : order_total should be positive, even for returned orders.

In [40]:
check = orders_temp["order_total"].astype(float) < 0
orders_temp.loc[check, ["order_total", "status"]]

       order_total      status
126         -49.75    Returned
199        -200.73   delivered
211        -245.57  Processing
226        -358.70    Deliverd
523         -23.43   Delivered
...            ...         ...
24377       -83.64   Delivered
24429      -344.62   Delivered
24642      -119.84   Delivered
24702        -3.41   Delivered
24976      -117.00   Delivered

[85 rows x 2 columns]

### Proposed Fix 13 : The values appear to be correct but just have the wrong sign. To clean, take the absolute value of order_total.

In [41]:
check = (orders_temp["order_total"].astype(float).round(2) != orders_temp["order_total"].astype(float)) & orders_temp["order_total"].notna()
orders_temp.loc[check, "order_total"]

Series([], Name: order_total, dtype: float64)

### Check Finding: order_total column has been converted to a float and checks show that no values are over 2 decimal places. Manual checks show there are no other issues.

## 1.12 cross-column considerations

### Check and Finding: While individual column missing values were considered, here we check if there are rows with many NA values. The check finds no row with more than 3 NA values, and only 121 rows with 3 or more missing values. Hence there is no row with too little information to be relevant. No change suggested.

In [42]:
orders_temp[orders_temp.isna().sum(axis=1) > 2]

,order_id,customer_id,order_date,ship_date,status,payment_method,channel,discount_code,discount_amount,shipping_cost,order_total
109,ORD-201756,C5063,NaN,NaN,Delivered,Klarna,Online,NaN,0.0,0.0,184.48
213,ORD-203539,NaN,2026-02-09,NaN,Processing,Gift Card,Web,NaN,0.0,0.0,159.21
245,ORD-204918,C6096,10.05.26,NaN,Delivered,Klarna,WEB,NaN,0.0,0.0,NaN
1232,ORD-200171,C2863,NaN,NaN,Pending,gift card,App,NaN,0.0,0.0,1428.33
1324,ORD-213341,C5551,2025-05-25,NaN,Processing,PayPal,Web,NaN,0.0,0.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
23573,ORD-202685,NaN,2026-03-20 18:02:28,NaN,Complete,CARD,Web,NaN,0.0,0.0,99.55
23689,ORD-216775,C5815,NaN,NaN,Cancelled,Card,Web,NaN,0.0,0.0,276.64
23768,ORD-214465,NaN,30/10/2024,NaN,Processing,PayPal,Marketplace,NaN,0.0,0.0,630.73
24642,ORD-218666,NaN,2024-12-16,NaN,Delivered,Card,Web,NaN,0.0,0.0,-119.84
25049,ORD-205491,C1095,<NA>,NaN,Processing,Klarna,Web,NaN,0.0,0.0,181.99

In [43]:
orders_temp[orders_temp.isna().sum(axis=1) > 3]

Empty DataFrame
Columns: [order_id, customer_id, order_date, ship_date, status, payment_method, channel, discount_code, discount_amount, shipping_cost, order_total]
Index: []

# 2. Customers

In [44]:
customers.head()

,customer_id,first_name,last_name,email,phone,signup_date,date_of_birth,city,postcode,country,marketing_opt_in
0,C3082,Mia,Evans,mia.evans90@outlook.com,07720 937945,06/07/2025,1955/05/19,Wrexham,LL11 9SA,UK,no
1,C5810,Oliver,Robinson,oliver.robinson@outlook.com,07159 902747,01/01/2026,1968-12-19,Swansea,SA5 5SN,United Kingdom,No
2,C6231,LILY,Jones,lily.jones@hotmail.co.uk,07453 098924,2026-04-04,1973-02-03,Belfast,bt23ls,england,0
3,C5373,Leo,McDonald,leo.mcdonald@gmail.com,07929696950,2025-01-22,19/05/1991,Manchester,M5 4DE,UK,y
4,C3666,George,Thompson,george.thompson90@icloud.com,07625-269687,2025-12-02,1983-01-06,London,E5 9RS,United Kingdom,y

In [45]:
customers.duplicated().sum()

np.int64(0)

In [46]:
customers.isna().sum()

customer_id           0
first_name            0
last_name             0
email                97
phone               373
signup_date          69
date_of_birth       113
city                 90
postcode            147
country             110
marketing_opt_in    431
dtype: int64

## 2.1 customer_id

### Check and Finding: There should be no duplicate, missing, or incorrectly formatted customer ids. Check shows there are not.

In [47]:
customers["customer_id"].duplicated().sum()

np.int64(0)

In [48]:
pattern = r"C\d+"
check = customers["customer_id"].str.fullmatch(pattern, na = False)
check.all()

np.True_

## 2.2 first_name

### Issue 14 : Customer first name should be consistently capitalised.

In [49]:
customers["first_name"].value_counts()

first_name
Leo       150
Ella      145
Cerys     144
Dylan     141
Priya     140
         ...
zainab      1
RHYS        1
Noah        1
owen        1
cerys       1
Name: count, Length: 152, dtype: int64

In [50]:
customers["first_name"].str.strip().str.lower().value_counts()

first_name
leo          160
ella         155
priya        154
dylan        153
cerys        149
chloe        146
bethan       146
aisha        145
george       142
seren        141
freya        141
katarzyna    141
megan        140
liam         140
arthur       139
fiona        138
harry        137
ravi         136
callum       133
tomasz       132
niamh        131
lily         131
ivy          130
noah         130
gareth       130
mohammed     129
owen         129
amelia       129
sean         128
jack         125
ava          121
sophie       121
grace        119
zainab       117
oliver       116
connor       115
ethan        115
mia          114
isla         112
rhys         110
Name: count, dtype: int64

### Proposed Fix 14 : Strip and Lower first name to maintain consistent capitalisation. Re-capitalise the first letter if needed.

## 2.3 last_name

### Check and Finding: There should be no missing, or incorrectly formatted last names. There are none, and checks confirm all last names are valid last names with no other errors.

In [51]:
customers["last_name"].value_counts()

last_name
Evans        197
Singh        196
Price        194
Lewis        194
Ali          193
Taylor       191
Smith        190
O'Brien      185
Murphy       184
Johnson      183
Thompson     181
Hughes       179
Hall         179
Morgan       178
Nowak        176
Jones        176
Jenkins      174
Patel        174
Robinson     173
Roberts      171
Walker       171
McDonald     170
Thomas       170
Williams     169
Edwards      169
Green        167
Davies       162
Khan         162
Griffiths    160
Wood         152
Name: count, dtype: int64

## 2.4 email

### Issue 15 : Customer emails should be unique, there are several repeat emails. Emails appear to be in the format of [first name].[lastname] which has led to different people holding the same email.

In [52]:
customers["email"].value_counts()

email
oliver.ali@icloud.com             4
seren.evans@btinternet.com        4
bethan.mcdonald@hotmail.co.uk     3
priya.taylor@yahoo.co.uk          3
owen.murphy@gmail.com             3
                                 ..
priya.hughes78@outlook.com        1
amelia.singh74@yahoo.co.uk        1
grace.thompson@hotmail.co.uk      1
oliver.thomas81@btinternet.com    1
connor.jenkins@hotmail.co.uk      1
Name: count, Length: 4891, dtype: int64

In [53]:
customers.loc[customers["email"].duplicated() & customers["email"].notna()].sort_values("email")

,customer_id,first_name,last_name,email,phone,signup_date,date_of_birth,city,postcode,country,marketing_opt_in
1622,C2778,Aisha,Griffiths,aisha.griffiths@yahoo.co.uk,07363 496921,2026/04/04,1961-04-16,Wrexham,LL3 7HP,United Kingdom,No
2791,C5701,Aisha,Griffiths,aisha.griffiths@yahoo.co.uk,NaN,2023-08-18,1979-03-21,Exeter,EX10 9HH,United Kingdom,y
3081,C5493,Aisha,Johnson,aisha.johnson@outlook.com,+44 7140 165674,2026-07-20,1973/04/07,Manchester,M6 9JF,United Kingdom,1
3296,C6146,aisha,Jones,aisha.jones12@hotmail.co.uk,0773760,NaN,1993-08-15,Swansea,SA11 1YP,Wales,0
4503,C2455,Aisha,Jones,aisha.jones41@btinternet.com,0789064,2026-09-03,"August 31, 1981",London,NaN,Great Britain,No
...,...,...,...,...,...,...,...,...,...,...,...
3797,C6276,Tomasz,Walker,tomasz.walker@hotmail.co.uk,07555 453771,14.10.25,1955-01-18,Swansea,SA16 1LA,United Kingdom,Y
4661,C5384,Zainab,Green,zainab.green@outlook.com,07601 858749,2025-07-23,1991-11-11,Birmingham,B9 1JJ,United Kingdom,NaN
4127,C6211,zainab,Griffiths,zainab.griffiths@yahoo.co.uk,07619 522302,2024-01-12,22.11.59,Cardiff,CF13 9BS,United Kingdom,no
2822,C3212,Zainab,Hall,zainab.hall92@hotmail.co.uk,07325 409455,2024-02-10,1973-02-28,Bangor,LL6 5TY,United Kingdom,no
4953,C5500,Zainab,Nowak,zainab.nowak19@btinternet.com,07861491415,2026-07-07,1988/12/17,Bath,BA11 7PB,GB,Yes

In [54]:
customers[customers[["email", "date_of_birth"]].duplicated(keep=False)].sort_values("email")

,customer_id,first_name,last_name,email,phone,signup_date,date_of_birth,city,postcode,country,marketing_opt_in
2417,C3507,Aisha,Jones,aisha.jones12@hotmail.co.uk,0773760,2025-11-12,1993-08-15,Swansea,SA8 4ZX,UK,FALSE
3296,C6146,aisha,Jones,aisha.jones12@hotmail.co.uk,0773760,NaN,1993-08-15,Swansea,SA11 1YP,Wales,0
1205,C4599,Amelia,Lewis,amelia.lewis10@btinternet.com,07585130748,2025-02-11,1973-01-10,NaN,L10 6HX,United Kingdom,1
5280,C6315,AMELIA,Lewis,amelia.lewis10@btinternet.com,07585130748,2025-03-17,1973-01-10,Liverpool,L4 3AB,United Kingdom,no
687,C5721,Amelia,Nowak,amelia.nowak96@yahoo.co.uk,NaN,2025/04/17,1960-01-28,Bristol,BS19 6XN,NaN,No
...,...,...,...,...,...,...,...,...,...,...,...
1877,C1607,Tomasz,Walker,tomasz.walker@hotmail.co.uk,07555 453771,2025-09-04,1955-01-18,Swansea,SA2 2WR,UK,TRUE
3797,C6276,Tomasz,Walker,tomasz.walker@hotmail.co.uk,07555 453771,14.10.25,1955-01-18,Swansea,SA16 1LA,United Kingdom,Y
717,C3791,Tomasz,Khan,NaN,07840 523404,2024-03-11,NaN,Bangor,LL14 4SH,United Kingdom,0
1736,C4171,Tomasz,O'Brien,NaN,07916824765,2024-03-14,NaN,Liverpool,L1 1GJ,United Kingdom,no
4884,C1246,Bethan,Khan,NaN,07269 792595,2025-02-18,NaN,Newport,NP10 6UJ,Wales,yes

### Proposed Fix 15 : Duplicate emails dont necessarily mean the same customer. By using their date of birth we can find customers who have signed up twice. For these rows, we can keep only the row with the most recent sign up date and relabel or merge instances with the old customer id with the new one. The row with the most recent sign up date will have the most up to date information about the customer.

###Beyond this, the email is not relevant for any exploration and no further cleaning is needed.

## 2.5 phone

### Phone number is also not relevant for any exploration so can be dropped and any such errors are dropped too.

## 2.6 signup_date

### Issue 16: The signup date column has the same issues as other date columns. There are several non-NA values to represent unknowns and the formatting is inconsistent.

In [55]:
customers["signup_date"].value_counts()

signup_date
0000-00-00      12
TBC             12
unknown         12
2026-06-15      10
2024-01-30       9
                ..
2024/12/23       1
04.10.23         1
22/09/2026       1
11-10-2023       1
May 11, 2026     1
Name: count, Length: 2568, dtype: int64

### Proposed Fix 16:  There are several non-missing NA values that can be replaced with NA. This would keep the values in sign up date as date types and keep consistent formatting for unknown order dates.
###The remaining values are just in the wrong time formats. Get the values by their format and convert those into the correct format. Any remaining values not in a given format can be handled manually.

## 2.7 date_of_birth

### Issue 17: The date of birth column again has the same errors as in other date columns

In [56]:
customers["date_of_birth"].value_counts()

date_of_birth
1900-01-01    51
2031-04-12    51
0000-00-00    17
unknown       15
TBC           12
              ..
1958-12-01     1
1978-06-29     1
1964-06-17     1
1981-07-11     1
1967-02-11     1
Name: count, Length: 4515, dtype: int64

### Proposed Fix 17:  Same fix as other date columns

## 2.8 city

### Issue 18: The city values have inconsistent capitalisation and spelling.

In [57]:
customers["city"].value_counts(dropna=False)

city
Bristol        288
Aberystwyth    284
Sheffield      281
Newport        276
Bath           273
Glasgow        273
Exeter         266
Swansea        264
Bangor         255
Nottingham     254
Edinburgh      249
Leeds          249
Belfast        245
Liverpool      242
Wrexham        239
Birmingham     235
Port Talbot    231
Cardiff        226
Manchester     219
London         213
NaN             90
edinburgh       18
Birmingam       18
BIRMINGHAM      16
london          14
Edinburg        14
swansea         13
CARDIFF         13
Swanzea         13
manchester      11
Manchestor      10
cardiff          9
Londn            7
LONDON           6
Cardif           6
Name: count, dtype: int64

### Proposed Fix 18: Values can be stripped and lowered. Spelling mistakes can be fixed by manual assignments.

## 2.9 post_code

### Location data can be obtained from the city column. Post codes are otherwise not useful for further exploration and can be removed.

In [58]:
customers["postcode"].value_counts(dropna=False)

postcode
NaN         147
EH20 1PG      2
BT4 9RH       2
G14 3TU       2
SA18 9YG      2
           ...
NP11 1TT      1
G10 3RD       1
LL10 7YQ      1
ex169jd       1
SA14 5FD      1
Name: count, Length: 5166, dtype: int64

## 2.10 country

### Issue 19: The country values are very limited and often incorrect

In [59]:
customers["country"].value_counts()

country
United Kingdom    3174
UK                 948
GB                 318
U.K.               245
Great Britain      196
Wales              186
england            143
Name: count, dtype: int64

In [60]:
customers[["country", "city"]].value_counts()

country         city
United Kingdom  Bristol        171
                Aberystwyth    168
                Nottingham     166
                Sheffield      165
                Swansea        165
                              ...
Wales           london           1
england         Bristol          1
Wales           manchester       1
                swansea          1
england         Edinburg         1
Name: count, Length: 193, dtype: int64

### Proposed Fix 19: The country values can be replaced by mapping the city values to a country within the UK.

## 2.11 marketing_opt_in

### Issue 20: The marketing opt in values are inconsistent despite having the same meaning.

In [61]:
customers["marketing_opt_in"].value_counts(dropna=False)

marketing_opt_in
N        470
No       464
0        460
no       458
Y        456
FALSE    437
1        436
Yes      435
y        434
yes      432
NaN      431
TRUE     407
Name: count, dtype: int64

### Proposed Fix 20: Relabel all values to their respective boolean True/False values. NA values stay NA.

# 3. Order Items

In [62]:
order_items.head()

   order_item_id    order_id product_id quantity unit_price
0         521656  ORD-210489       P236        1      35.62
1         502093  ORD-201014       P196        1     132.05
2         538709  ORD-218719       P109        1     106.65
3         549040  ORD-223642       P184        2     275.89
4         533522  ORD-216198       P257        1      65.43

### Issue 21: The order items table has 250 duplicated rows.

In [63]:
order_items.duplicated().sum()

np.int64(250)

### Proposed Fix 21: Drop the 250 duplicated rows.

In [64]:
oi_temp = order_items.drop_duplicates().copy()

In [65]:
oi_temp.isna().sum()

order_item_id      0
order_id           0
product_id         0
quantity           0
unit_price       539
dtype: int64

## 3.1 order_item_id

### Check and Finding: The order_item id should be unique, not missing, and a single integer. Checks show no issues.

In [66]:
oi_temp["order_item_id"].duplicated().sum()

np.int64(0)

In [67]:
oi_temp["order_item_id"].value_counts()

order_item_id
502175    1
521656    1
502093    1
538709    1
549040    1
         ..
533147    1
520342    1
507869    1
513311    1
537944    1
Name: count, Length: 51903, dtype: int64

In [68]:
oi_temp["order_item_id"].astype(int)

0        521656
1        502093
2        538709
3        549040
4        533522
          ...
52148    522308
52149    542910
52150    531663
52151    543028
52152    502175
Name: order_item_id, Length: 51903, dtype: int64

## 3.2 order_id

### Check and Finding: The orderid should be in the format "ORD-[id number]" and not missing. It should also have a corresponding value in the orders table. Checks show no issues.

In [69]:
pattern = r"ORD-\d+"
check = oi_temp["order_id"].str.fullmatch(pattern, na = False)
check.all()

np.True_

In [70]:
oi_temp["order_id"].isin(orders["order_id"]).all()

np.True_

## 3.3 product_id

### Issue 22: Several product ids are incorrectly formatted with a lowercase P.

In [71]:
pattern = r"P\d+"
check = oi_temp["product_id"].str.fullmatch(pattern, na = False)
check.all()

np.False_

In [72]:
oi_temp[~check]

       order_item_id    order_id product_id quantity unit_price
157           501237  ORD-200588       p198        2     155.46
410           542820  ORD-220653       p112        1     133.17
686           538338  ORD-218539       p242        1      46.12
735           507255  ORD-203513       p203        1     121.91
829           537030  ORD-217920       p122        1     245.63
...              ...         ...        ...      ...        ...
51506         519650  ORD-209500       p150        1      49.69
51534         540060  ORD-219346       p152        1     104.27
51572         512341  ORD-206014       p201        1     121.20
51877         500307  ORD-200148       p257        4      65.43
51929         515706  ORD-207624       p115        1      92.72

[508 rows x 5 columns]

In [73]:
oi_temp["product_id"] = oi_temp["product_id"].str.upper()
check = oi_temp["product_id"].str.fullmatch(pattern, na = False)
check.all()

np.True_

### Proposed Fix 22: Capitalise the product id string

### Issue 23: The product id should exist within the products table, but 111 rows do not match this condition.

In [74]:
oi_temp["product_id"].isin(products["product_id"]).all()

np.False_

In [75]:
oi_temp[~oi_temp["product_id"].isin(products["product_id"])]

       order_item_id    order_id product_id quantity unit_price
503           515633  ORD-207587       P970        1      42.60
1036          507366  ORD-203563       P913        1      45.38
1074          528668  ORD-213877       P976        1     145.19
1198          542865  ORD-220675       P945        1     239.47
1287          533514  ORD-216194       P973        4     225.73
...              ...         ...        ...      ...        ...
49254         517565  ORD-208505       P970        1      59.18
49259         501095  ORD-200519       P955        1      97.59
50262         522546  ORD-210921       P958        2      48.60
50830         525675  ORD-212419       P925        1     184.48
50955         546900  ORD-222622       P948        1      88.57

[111 rows x 5 columns]

### Proposed Fix 23: The product id should exist within the products table, but it doesnt necessarily impact the order items table. Removing these rows would harm the order totals, and keeping them does not neccesarily harm exploration as long as they taken into account. So these values can be kept.

## 3.4 quantity

### Issue 24: Quantity has negative values and string representations of numbers

In [76]:
oi_temp["quantity"].value_counts()

quantity
1        38708
2         8719
3         2499
4          993
5          505
0          163
-1         107
one         80
250         31
-2          28
100         24
999         15
two         10
three        9
-3           7
-4           3
-5           2
Name: count, dtype: int64

### Proposed Fix 24: Map string values to integers and take absolute values of quantities

In [77]:
oi_temp["quantity"] = oi_temp["quantity"].replace({"one":1, "two":2, "three":3})

In [78]:
oi_temp.loc[oi_temp["quantity"].astype(int) < 0]

       order_item_id    order_id product_id quantity unit_price
1372          544329  ORD-221371       P124       -1     106.06
1708          514717  ORD-207158       P161       -1     246.25
2043          534672  ORD-216772       P158       -1     191.50
2085          505724  ORD-202794       P159       -2     310.13
2287          501382  ORD-200666       P175       -1      48.79
...              ...         ...        ...      ...        ...
51415         506691  ORD-203252       P231       -1      34.69
51755         549208  ORD-223717       P225       -1      66.90
51805         544717  ORD-221560       P218       -1      31.11
52066         529946  ORD-214477       P134       -1     188.89
52131         521100  ORD-210207       P131       -1     153.16

[147 rows x 5 columns]

In [79]:
oi_temp["quantity"] = oi_temp["quantity"].astype(int).abs()

In [80]:
oi_temp["quantity"].value_counts()

quantity
1      38895
2       8757
3       2515
4        996
5        507
0        163
250       31
100       24
999       15
Name: count, dtype: int64

### Issue 25: Several quantities are significantly higher than reasonable. Some values are 0 which would not make sense for an order.

In [81]:
oi_temp.loc[oi_temp["quantity"] > 5]

       order_item_id    order_id product_id  quantity unit_price
824           546183  ORD-222295       P209       250      63.17
1917          508802  ORD-204260       P134       250     188.89
2653          549025  ORD-223634       P190       100      42.60
2813          530505  ORD-214745       P260       999      11.10
5078          525098  ORD-212145       P146       999     112.19
...              ...         ...        ...       ...        ...
46193         523875  ORD-211566       P152       100     104.27
47669         535360  ORD-217110       P186       999     301.73
47986         538555  ORD-218643       P163       250     133.05
50661         546169  ORD-222284       P178       250        NaN
51748         510215  ORD-204963       P165       250     155.24

[70 rows x 5 columns]

###Proposed Fix 25: Replace with NA

## 3.5 unit_price

### Issue 26: Unit price values have "£" symbol

In [82]:
oi_temp["unit_price"].value_counts()

unit_price
202.06     356
153.16     353
83.64      352
184.48     352
97.59      347
          ...
£190.29      1
£142.34      1
£225.73      1
£81.56       1
1066.50      1
Name: count, Length: 451, dtype: int64

### Proposed Fix 26: Replace with empty string

In [83]:
oi_temp["unit_price"] = oi_temp["unit_price"].str.replace("£", "").astype(float)

### Check and Finding: Unit prices are otherwise correctly formatted and float values.

In [84]:
check = (oi_temp["unit_price"].round(2) == oi_temp["unit_price"])
oi_temp.loc[~check & oi_temp["unit_price"].notna(), "unit_price"]

Series([], Name: unit_price, dtype: float64)

# 4. Products

In [85]:
products.head()

,product_id,product_name,category,unit_price,cost_price,stock_qty,supplier,launch_date,is_active
0,P101,Forest Waterproof Jacket,outerwear,220.20,131.29,369,Alpine Supply Co,"March 14, 2025",N
1,P102,Storm Waterproof Jacket,Outerwear,190.29,111.93,286,Northern Gear,2022-07-12,FALSE
2,P103,Ridge Waterproof Jacket,Outerwear,77.19,46.15,243,BlueRidge Textiles,2023-04-11,0
3,P104,Peak Waterproof Jacket,Outer wear,75.01,39.89,268,TrekCo Ltd,2022-10-19,N
4,P105,Coastal Insulated Parka,Outerwear,77.66,33.31,332,Northern Gear,2025-02-16,N

In [86]:
products.duplicated().sum()

np.int64(1)

In [87]:
products_temp = products.drop_duplicates().copy()

In [88]:
products_temp.isna().sum()

product_id      0
product_name    0
category        0
unit_price      0
cost_price      0
stock_qty       0
supplier        0
launch_date     2
is_active       0
dtype: int64

## 4.1 product_id

### Check and Finding: products are correctly formatted, unique and not missing

In [89]:
products_temp["product_id"].duplicated().sum()

np.int64(0)

In [90]:
pattern = r"P\d+"
check = products_temp["product_id"].str.fullmatch(pattern, na = True)
check.all()

np.True_

## 4.2 product_name

### Check and Finding: product names return no issues, but should be stripped and lowered for consistency

In [91]:
with pd.option_context("display.max_rows", None):
    display(products_temp["product_name"].str.strip().str.lower().value_counts())

product_name
peak windbreaker             3
alpine trail runner          3
ridge sleeping bag           3
valley softshell jacket      2
coastal insulated parka      2
ridge head torch             2
coastal trekking poles       2
coastal beanie               2
alpine insulated bottle      2
highland walking boot        2
peak hiking sandal           2
valley down gilet            2
highland softshell jacket    2
trail sleeping mat           2
coastal sleeping mat         2
highland head torch          2
peak head torch              2
peak approach shoe           2
summit camping stove         2
alpine 2-person tent         2
summit water filter          2
summit neck gaiter           2
valley 45l trekking pack     2
valley duffel bag            2
alpine map case              2
highland liner gloves        2
highland merino base top     2
storm waterproof jacket      1
forest waterproof jacket     1
peak waterproof jacket       1
ridge waterproof jacket      1
summit down gilet            1
ridge down gilet             1
storm trail runner           1
alpine walking boot          1
highland windbreaker         1
forest windbreaker           1
highland winter boot         1
peak winter boot             1
trail winter boot            1
alpine hiking sandal         1
coastal hiking sandal        1
ridge hiking sandal          1
peak walking boot            1
trail walking boot           1
highland trail runner        1
peak down gilet              1
coastal 2-person tent        1
valley approach shoe         1
highland approach shoe       1
storm approach shoe          1
ridge winter boot            1
coastal approach shoe        1
valley camping stove         1
forest camping stove         1
coastal sleeping bag         1
peak sleeping bag            1
ridge 2-person tent          1
highland sleeping bag        1
storm camping stove          1
forest insulated parka       1
valley fleece jacket         1
coastal fleece jacket        1
ridge fleece jacket          1
storm windbreaker            1
summit softshell jacket      1
ridge softshell jacket       1
summit fleece jacket         1
alpine insulated parka       1
storm 25l daypack            1
summit 25l daypack           1
highland 25l daypack         1
peak water filter            1
coastal water filter         1
highland water filter        1
storm water filter           1
alpine sleeping mat          1
ridge camping stove          1
highland hydration vest      1
ridge hydration vest         1
valley hydration vest        1
ridge 45l trekking pack      1
forest 45l trekking pack     1
summit 45l trekking pack     1
peak 25l daypack             1
forest merino base top       1
trail merino base top        1
storm merino base top        1
coastal merino base top      1
forest thermal leggings      1
coastal thermal leggings     1
peak thermal leggings        1
highland thermal leggings    1
peak wool socks              1
storm wool socks             1
alpine wool socks            1
forest hydration vest        1
storm duffel bag             1
alpine duffel bag            1
coastal duffel bag           1
peak 45l trekking pack       1
summit liner gloves          1
valley liner gloves          1
peak liner gloves            1
trail wool socks             1
summit wool socks            1
trail neck gaiter            1
coastal neck gaiter          1
peak neck gaiter             1
peak trekking poles          1
storm trekking poles         1
storm beanie                 1
valley beanie                1
ridge beanie                 1
highland sun hat             1
ridge neck gaiter            1
trail liner gloves           1
alpine sun hat               1
coastal sun hat              1
ridge sun hat                1
peak sun hat                 1
forest insulated bottle      1
valley insulated bottle      1
ridge insulated bottle       1
storm insulated bottle       1
summit dry bag               1
valley dry bag               1
coastal dry bag              1
highland dry bag             1
highland map case            1
ridge map case               1
summit map case              1
trail map case               1
Name: count, dtype: int64

## 4.3 category

### Issue 27: Category labels have inconsistent formatting, spacing and capitalisation.

In [92]:
products_temp["category"].value_counts()

category
Camping             29
Outerwear           25
Accessories         24
Base Layers         22
Footwear            19
Backpacks           15
Foot wear            5
accessories          3
Accesories           3
camping              3
base layers          3
backpacks            3
Outer wear           2
Baselayers           2
outerwear            1
Camping & Hiking     1
footwear             1
OUTERWEAR            1
Back packs           1
Name: count, dtype: int64

### Proposed Fix 27: Strip, lower and relabel variations into the same category labels.

## 4.4 unit_price

### Issue 28: Some unit prices have "£" symbols and "," instead of "."

In [93]:
#products_temp["unit_price"].astype(float)
#returns error when converting 'could not convert string to float: '£172.97''

### Proposed Fix 28: replace symbols with their respective correct versions

In [94]:
products_temp["unit_price"] = products_temp["unit_price"].str.replace("£", "")

In [95]:
products_temp["unit_price"] = products_temp["unit_price"].str.replace(",", ".").astype(float)

### Check: unit prices are otherwise valid

In [96]:
check = (products_temp["unit_price"].round(2) != products_temp["unit_price"]) | (products_temp["unit_price"].astype(float) < 0)
products_temp.loc[check]

Empty DataFrame
Columns: [product_id, product_name, category, unit_price, cost_price, stock_qty, supplier, launch_date, is_active]
Index: []

## 4.5 cost_price

### Check and Finding: cost price can be converted to float and is formatted correctly

In [97]:
products_temp["cost_price"].astype(float)

0      131.29
1      111.93
2       46.15
3       39.89
4       33.31
        ...
158      4.64
159      4.70
160     14.63
161     28.05
162     14.42
Name: cost_price, Length: 163, dtype: float64

In [98]:
check = (products_temp["cost_price"].round(2) != products_temp["cost_price"]) | (products_temp["cost_price"].astype(float) < 0)
products_temp.loc[check]

Empty DataFrame
Columns: [product_id, product_name, category, unit_price, cost_price, stock_qty, supplier, launch_date, is_active]
Index: []

## 4.6 stock_qty

In [99]:
products_temp["stock_qty"].value_counts()

stock_qty
268    3
384    3
317    3
146    3
62     2
      ..
24     1
283    1
309    1
304    1
102    1
Name: count, Length: 134, dtype: int64

### Issue 29: Some stock quantities are negative

In [100]:
check = (products_temp["stock_qty"] < 0)
products_temp.loc[check]

,product_id,product_name,category,unit_price,cost_price,stock_qty,supplier,launch_date,is_active
15,P116,Valley Fleece Jacket,Outerwear,181.99,109.06,-23,Alpine Supply Co,2023/12/10,Y
17,P118,Ridge Fleece Jacket,Outerwear,185.02,111.59,-30,TrekCo Ltd,2025/04/09,Y
25,P126,Summit Down Gilet,Outerwear,225.73,88.50,-5,Summit Wholesale,2023-03-04,FALSE
35,P136,Peak Walking Boot,Footwear,88.57,57.43,-6,Alpine Supply Company,2025-06-19,TRUE
47,P148,Ridge Winter Boot,Foot wear,97.70,53.60,-22,TREKCO LTD,2022-08-27,TRUE
61,P162,Coastal Sleeping Bag,Camping,312.22,111.31,-16,Alpine Supply Co,"January 07, 2023",TRUE
94,P195,Valley 45L Trekking Pack,Backpacks,97.45,44.91,-24,Alpine Supply Co,2025-07-30,Y
107,P208,Highland Merino Base Top,Base Layers,45.76,18.95,-20,TrekCo Ltd,11.08.24,0
147,P248,Alpine Insulated Bottle,Accessories,39.83,15.61,-1,Alpine Supply Co,2023-05-23,Y

### Proposed Fix 29: The most likely situation is that these values are incorrectly negative and should be positive. Stock quantity has no bearing on anything else within the database. Absolute value should be taken

## 4.7 supplier

### Issue 30: Supplier names appear in many variations

In [101]:
products["supplier"].value_counts()

supplier
Alpine Supply Co          30
Northern Gear             30
TrekCo Ltd                27
BlueRidge Textiles        25
Summit Wholesale          23
Alpine supply co.          6
northern gear              4
Summit Wholesale Ltd       3
Northern Gear Ltd          3
BlueRidge Textiles Ltd     3
Trekco ltd                 2
Alpine Supply Company      2
summit wholesale           2
TrekCo Limited             2
TREKCO LTD                 1
Blue Ridge Textiles        1
Name: count, dtype: int64

### Proposed Fix 30: strip and lower values, and relabel variations to have one consistent supplier name

## 4.8 launch_date

### Issue 31: Launch data column has same date issues as other date columns

In [102]:
products["launch_date"].value_counts()

launch_date
2023-04-11    2
2025-08-03    2
2023-04-17    2
2022-08-15    2
2024-02-02    2
             ..
2024-09-03    1
2022-06-22    1
2025-01-03    1
2025-03-04    1
2023-06-12    1
Name: count, Length: 156, dtype: int64

### Proposed Fix 31: Clean column using the same methods

## 4.9 is_active

### Issue 32: is active has inconsistent labelling

In [103]:
products["is_active"].value_counts()

is_active
N        40
TRUE     31
0        25
FALSE    24
1        22
Y        22
Name: count, dtype: int64

### Proposed Fix 32: Relabel all values to boolean True/False values

# 5 returns

In [104]:
returns.head()

,return_id,order_item_id,order_id,return_date,reason,refund_amount,resolution
0,R7001,548180,ORD-223229,2025-10-08,Too Small,155.46,REFUND
1,R7002,502171,ORD-201051,2024-02-19,not waterproof,96.48,Refund
2,R7003,539059,ORD-218869,2025-07-29,Faulty,213.87,Refund
3,R7004,528860,ORD-213965,TBC,Too Small,586.67,refund
4,R7005,511660,ORD-205685,2026-09-30,arrived damaged,20.76,refund

In [105]:
returns.duplicated().sum()

np.int64(0)

In [106]:
returns.isna().sum()

return_id          0
order_item_id      0
order_id           0
return_date       38
reason           277
refund_amount     55
resolution         0
dtype: int64

## 5.1 return_id

In [107]:
returns["return_id"].head()

0    R7001
1    R7002
2    R7003
3    R7004
4    R7005
Name: return_id, dtype: object

### Check and Finding: Return id isnt duplicated, missing, or incorrectly formatted. No issues.

In [108]:
pattern = r"R\d+"
check = returns["return_id"].str.fullmatch(pattern, na = False)
check.all()

np.True_

## 5.2 order_item_id

### Check and Finding: order_item_id is correctly formatted, validm and all ids have a respective id in the order items table

In [109]:
returns["order_item_id"].head()

0    548180
1    502171
2    539059
3    528860
4    511660
Name: order_item_id, dtype: int64

In [110]:
returns["order_item_id"].astype(int) # runs with no errors, all ids are valid.

0       548180
1       502171
2       539059
3       528860
4       511660
         ...
2794    507671
2795    527210
2796    550817
2797    536628
2798    513522
Name: order_item_id, Length: 2799, dtype: int64

In [111]:
check = returns["order_item_id"].isin(order_items["order_item_id"])
returns.loc[~check]

Empty DataFrame
Columns: [return_id, order_item_id, order_id, return_date, reason, refund_amount, resolution]
Index: []

## 5.3 order_id

### Check and Finding: All order ids are in the correct format and have a respective value in the orders table

In [112]:
pattern = r"ORD-\d+"
check = returns["order_id"].str.fullmatch(pattern, na = False)
check.all()

np.True_

In [113]:
check = returns["order_id"].isin(order_items["order_id"])
returns.loc[~check]

Empty DataFrame
Columns: [return_id, order_item_id, order_id, return_date, reason, refund_amount, resolution]
Index: []

## 5.4 return_date

### Issue 33: Return date has the same formatting and non-NA missing values issues as previous date columns

In [114]:
returns["return_date"].value_counts()

return_date
2026-09-30            87
2025-12-09            11
September 30, 2026    11
unknown               10
2026-07-14            10
                      ..
2025/09/05             1
2025-03-06             1
12/01/2025             1
01 Jun 2026            1
2024-02-19             1
Name: count, Length: 1432, dtype: int64

### Proposed Fix 33: Fix date column in the same way as others.

## 5.5 reason

### Issue 34: Return reasons have different formatting and styles. There are also different reasons that relate to the same problem. As well as this, there are 277 NaN values.

In [115]:
returns["reason"].value_counts(dropna=False)

reason
NaN                         277
didn't fit                  140
wrong size                  131
TOO SMALL                   124
didnt fit                   124
Doesn't fit                 120
found cheaper               119
too big                     117
Too Small                   112
changed mind                111
no longer needed            104
too small                   104
bought by mistake           101
box crushed                  95
leaking                      88
zip broke                    88
Faulty                       87
looks different to photo     83
not waterproof               83
stitching came apart         78
not as described             78
colour different             77
damaged in transit           77
arrived damaged              75
faulty zip                   73
DAMAGED                      68
-                            25
other                        21
see email                    19
Name: count, dtype: int64

### Proposed Fix 34: Strip and lower values, replace values with more consistent category labelling. Relabel non-Na missing values too.

## 5.6 refund_amount

In [116]:
returns["refund_amount"].astype(float)

0       155.46
1        96.48
2       213.87
3       586.67
4        20.76
         ...
2794     36.54
2795     45.38
2796     45.76
2797    103.25
2798    128.01
Name: refund_amount, Length: 2799, dtype: float64

### Check and Finding: No refunds amount have incorrect formatting.

In [117]:
check = ((returns["refund_amount"].round(2) != returns["refund_amount"]) | (returns["refund_amount"].astype(float) < 0)) & returns["refund_amount"].notna()
returns.loc[check]

Empty DataFrame
Columns: [return_id, order_item_id, order_id, return_date, reason, refund_amount, resolution]
Index: []

## 5.7 Resolution

### Issue 35: resolution labels have variations of the same label

In [118]:
returns["resolution"].value_counts()

resolution
refund          580
REFUND          571
Store credit    568
Refund          543
Exchange        537
Name: count, dtype: int64

In [119]:
returns["resolution"].str.lower().str.strip().value_counts()

resolution
refund          1694
store credit     568
exchange         537
Name: count, dtype: int64

### Proposed Fix 35: strip and lower values

# 6 web_sessions

In [120]:
web_sessions.head()

,session_id,customer_id,session_timestamp,device,traffic_source,pages_viewed,session_duration_sec,converted
0,S909710,C3468,2024-11-05 20:21:08,Desktop,paid_search,1,62.0,0
1,S947222,NaN,2026-08-31 12:18:08,Mobile,Email,13,624.0,0
2,S926195,NaN,2025-06-17T12:02:46Z,Desktop,Google Ads,1,30.0,0
3,S901027,C4173,2026-07-23 13:02:00,mobile,social,1,42.0,0
4,S918483,NaN,2026-03-15 18:07:14,Mobile,paid_search,3,119.0,0

In [121]:
web_sessions.duplicated().sum()

np.int64(400)

In [122]:
web_temp = web_sessions.drop_duplicates().copy()

In [123]:
web_temp.isna().sum()

session_id                  0
customer_id             35736
session_timestamp           0
device                      0
traffic_source              0
pages_viewed                0
session_duration_sec     2426
converted                   0
dtype: int64

## 6.1 session_id

### Check and Finding: session id has no missing, duplicated or incorrectly formatted values. No issues.

In [124]:
web_temp["session_id"]

0        S909710
1        S947222
2        S926195
3        S901027
4        S918483
          ...
60395    S959989
60396    S907026
60397    S930182
60398    S913030
60399    S956940
Name: session_id, Length: 60000, dtype: object

In [125]:
web_temp["session_id"].duplicated().sum()

np.int64(0)

In [126]:
pattern = r"S\d+"
check = web_temp["session_id"].str.fullmatch(pattern, na = False)
check.all()

np.True_

## 6.2 customer_id

In [127]:
web_temp["customer_id"]

0        C3468
1          NaN
2          NaN
3        C4173
4          NaN
         ...
60395    C2023
60396      NaN
60397      NaN
60398      NaN
60399      NaN
Name: customer_id, Length: 60000, dtype: object

### Issue 36: Nearly 60% of rows have a missing customer id

In [128]:
web_temp["customer_id"].isna().mean()

np.float64(0.5956)

### Proposed Fix 36: The customer_id column can be left as is. It represents the customer id of a user who has logged onto that session, but the missing values represent that around 60% of users do not use an account.

### Check and Finding : Customer ids are correctly formatted and all exist within the customers table.

In [129]:
not_na_ids = web_temp.loc[web_temp["customer_id"].notna(), "customer_id"]
pattern = r"C\d+"
check = not_na_ids.str.fullmatch(pattern, na = False)
check.all()

np.True_

In [130]:
check = web_temp["customer_id"].isin(customers["customer_id"])
web_temp[~check & web_temp["customer_id"].notna()]

Empty DataFrame
Columns: [session_id, customer_id, session_timestamp, device, traffic_source, pages_viewed, session_duration_sec, converted]
Index: []

## 6.3 session_timestamp

### Issue 37: Session timestamp has several different formats for date and time

In [131]:
web_temp["session_timestamp"].value_counts()

session_timestamp
13/11/2025 04:13       2
20/04/2025 05:43       2
30/05/2025 17:59       2
07/09/2025 22:31       2
10/07/2025 07:50       2
                      ..
2026-07-30 09:03:13    1
2025-08-12 15:15:41    1
2025-05-13 07:58:50    1
28/02/2025 04:19       1
2024-11-07 22:17:59    1
Name: count, Length: 59961, dtype: int64

### Proposed Fix 37: Re-format each date using the same method as other date columns and create a seperate date column. Re-format timestamp, keeping it consistent in hour, minute (and seconds if needed) format and create a seperate timestamp column.

## 6.4 device

### Issue 38: device has many different variations of the same value. Inconsistent capitalisation and labels. Some labels might be better off under other labels.

In [132]:
web_temp["device"].value_counts()

device
Mobile     30534
Desktop    16825
Tablet      3569
MOBILE      1841
iPhone      1823
mobile      1795
desktop     1031
DESKTOP      997
PC           950
iPad         218
tablet       209
TABLET       208
Name: count, dtype: int64

In [133]:
web_temp["device"].str.strip().str.lower().value_counts()

device
mobile     34170
desktop    18853
tablet      3986
iphone      1823
pc           950
ipad         218
Name: count, dtype: int64

### Proposed Fix 38: Strip and lower values. Remap labels that could be part of other labels.

## 6.5 traffic_source

### Issue 39: Traffic source has inconsistent formatting, capitalisation and several variations of the same source.

In [134]:
web_temp["traffic_source"].value_counts()

traffic_source
organic           10371
paid_search        6527
social             4193
direct             3619
Organic            3608
email              3567
organic search     3557
Google Organic     3462
google_ads         1700
Paid Search        1679
Google Ads         1621
PPC                1602
referral           1459
none               1223
E-mail             1221
Email              1217
newsletter         1202
(direct)           1201
Direct             1185
Instagram           879
FB                  878
Social              843
instagram           842
Facebook            832
Referral            768
referral site       744
Name: count, dtype: int64

### Proposed fix 39: Strip and lower values. Remap labels that could be part of other labels and to have consistent formatting. Relabel non-missing NA values.

## 6.6 pages_viewed

In [135]:
web_temp["pages_viewed"].value_counts()

pages_viewed
1      22726
2       7684
3       6059
4       4745
5       3835
       ...
854        1
469        1
587        1
712        1
716        1
Name: count, Length: 149, dtype: int64

### Issue 40: some rows have negative pages viewed, which is impossible. Others are significantly higher than is likely to be reasonable

In [136]:
check = web_temp["pages_viewed"].notna() & (web_temp["pages_viewed"].astype(int) > 0)
web_temp[~check]

,session_id,customer_id,session_timestamp,device,traffic_source,pages_viewed,session_duration_sec,converted
1086,S905424,NaN,2024-05-11 01:31:21,Mobile,E-mail,-5,282.0,0
1673,S901663,NaN,2026-04-25 23:48:38,Mobile,newsletter,-2,31.0,0
2637,S949024,NaN,2026-05-14 20:29:57,Mobile,Referral,-6,179.0,FALSE
2828,S912735,C2770,2025-04-02 22:20:05,Mobile,email,-2,99.0,0
3746,S949325,NaN,14/05/2025 10:45,DESKTOP,paid_search,-8,320.0,0
...,...,...,...,...,...,...,...,...
58750,S944203,NaN,15/06/2026 16:38,Mobile,organic,-4,251.0,1
58794,S918529,C2746,2025-11-15 09:51:06,desktop,organic,-1,68.0,0
59300,S925005,NaN,2025-07-31 17:20:46,Desktop,paid_search,-5,128.0,0
59544,S937097,NaN,2025-09-09T02:06:58Z,Desktop,Google Ads,-1,64.0,0
60212,S939904,C4596,2026-07-08 17:37:38,Mobile,organic,-1,NaN,0

### Proposed Fix 40: Take the absolute value of these values.

In [137]:
web_temp["pages_viewed"] = web_temp["pages_viewed"].abs()

In [138]:
check = web_temp["pages_viewed"].notna() & (web_temp["pages_viewed"].astype(int) > 0)
web_temp[~check]

Empty DataFrame
Columns: [session_id, customer_id, session_timestamp, device, traffic_source, pages_viewed, session_duration_sec, converted]
Index: []

## 6.7 session_duration_sec

In [139]:
web_temp["session_duration_sec"].value_counts(dropna=False)

session_duration_sec
NaN         2426
45.0         561
68.0         541
66.0         540
61.0         536
            ...
119922.0       1
973.0          1
94111.0        1
173680.0       1
90166.0        1
Name: count, Length: 1507, dtype: int64

### Check and Finding: There are no negative session durations, and the column itself is already float. Missing values are not a significant issue and can be ignored aswell. Significant sessions can be flagged later after more careful inspection.

In [140]:
check = web_temp["session_duration_sec"].notna() & (web_temp["session_duration_sec"] > 0)
web_temp[~check & web_temp["session_duration_sec"].notna()]

Empty DataFrame
Columns: [session_id, customer_id, session_timestamp, device, traffic_source, pages_viewed, session_duration_sec, converted]
Index: []

## 6.8 converted

### Issue 41: There are many different labels for the same label.

In [141]:
web_temp["converted"].value_counts(dropna=False)

converted
0        48218
N         4920
FALSE     4751
1         1733
Y          206
TRUE       172
Name: count, dtype: int64

### Proposed Fix 41: Relabel values to boolean True/False values.

# 7 cross-table checks

## 7.1 order items unit price should match product price in product table

In [142]:
oi_temp.head()

   order_item_id    order_id product_id  quantity  unit_price
0         521656  ORD-210489       P236         1       35.62
1         502093  ORD-201014       P196         1      132.05
2         538709  ORD-218719       P109         1      106.65
3         549040  ORD-223642       P184         2      275.89
4         533522  ORD-216198       P257         1       65.43

In [143]:
merged_prices = oi_temp.merge(products_temp, how = "left", on = "product_id")

### Issue 42: Many unit prices are missing in order items table when they are present in products table. Also, unit prices in order items table appear to be mistyped whereas products has the correct unit price.

In [144]:
check = merged_prices["unit_price_x"].astype(float) == merged_prices["unit_price_y"].astype(float)
merged_prices[~check]

,order_item_id,order_id,product_id,quantity,unit_price_x,product_name,category,unit_price_y,cost_price,stock_qty,supplier,launch_date,is_active
50,537416,ORD-218101,P196,2,NaN,Valley 45L Trekking Pack,Backpacks,132.05,84.39,310.0,Summit Wholesale Ltd,2025-03-26,1
123,541743,ORD-220151,P246,2,NaN,Peak Sun Hat,Accessories,43.29,27.19,317.0,Northern Gear,2022-07-21,1
153,545240,ORD-221822,P203,1,1219.1,Storm Duffel Bag,backpacks,121.91,73.34,289.0,Northern Gear,20.10.24,FALSE
195,510166,ORD-204939,P158,2,NaN,Ridge 2-Person Tent,Camping,191.50,69.52,400.0,Alpine Supply Co,2024-06-07,FALSE
228,530162,ORD-214583,P172,2,NaN,Trail Sleeping Mat,Camping,103.25,65.78,70.0,Northern Gear,2024-09-29,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
51647,550446,ORD-224300,P145,1,NaN,Trail Winter Boot,Foot wear,97.59,61.90,251.0,BlueRidge Textiles Ltd,2023-11-22,Y
51650,521837,ORD-210575,P231,2,346.9,Summit Neck Gaiter,Base Layers,34.69,19.88,78.0,Northern Gear,2022-07-07,N
51723,529033,ORD-214052,P148,1,NaN,Ridge Winter Boot,Foot wear,97.70,53.60,-22.0,TREKCO LTD,2022-08-27,TRUE
51780,527240,ORD-213176,P236,2,NaN,Storm Trekking Poles,Accessories,35.62,14.90,75.0,Alpine Supply Co,11/08/2025,TRUE
51828,537334,ORD-218063,P161,1,NaN,Peak Sleeping Bag,Camping,246.25,117.38,299.0,TrekCo Ltd,02/06/2024,FALSE

### Proposed Fix 42: replace all missing/incorrect values for unit price in the order items table with the correct unit price in the products table.

### Issue 43: The old customer ids were removed from the customer table. The old ones need still exist in orders and web sessions

### Proposed Fix 43: Replace old customer ids with the most up to date customer id.

### Issue 44: There are many refund amounts that are higher than possible. Many are lower than possible but it is unclear whether this is due to full vs partial refunds.

In [145]:
ret_details = returns.merge(oi_temp, how="left", on="order_item_id")
ret_details[
        (ret_details["refund_amount"] > ret_details["quantity"] * ret_details["unit_price"]) |
        ((ret_details["unit_price"] > ret_details["refund_amount"]) )
    ]

,return_id,order_item_id,order_id_x,return_date,reason,refund_amount,resolution,order_id_y,product_id,quantity,unit_price
3,R7004,528860,ORD-213965,TBC,Too Small,586.67,refund,ORD-213965,P134,1,188.89
4,R7005,511660,ORD-205685,2026-09-30,arrived damaged,20.76,refund,ORD-205685,P229,1,41.52
5,R7006,542424,ORD-220474,2026-04-29,no longer needed,112.86,Refund,ORD-220474,P126,1,225.73
7,R7008,513659,ORD-206657,2025-01-30,TOO SMALL,16.39,Exchange,ORD-206657,P214,1,32.78
8,R7009,504446,ORD-202187,01 Jun 2026,too big,15.31,Refund,ORD-202187,P261,1,30.63
...,...,...,...,...,...,...,...,...,...,...,...
2783,R9784,540717,ORD-219659,2026-07-01,not waterproof,37.51,refund,ORD-219659,P104,1,75.01
2785,R9786,512992,ORD-206333,2025-08-24,not as described,4.90,REFUND,ORD-206333,P238,1,9.80
2791,R9792,511154,ORD-205433,2026-02-13,bought by mistake,221.31,Exchange,ORD-205433,P128,1,276.64
2793,R9794,506881,ORD-203337,"May 14, 2026",looks different to photo,46.27,Store credit,ORD-203337,P237,2,57.84
2798,R9799,513522,ORD-206590,2024-04-30,Too Small,128.01,REFUND,ORD-206590,P111,2,256.03

### Proposed fix: Cap the refund amount at the unit price.

###Issue 45: The cost price for 6 products are higher than what they are being sold for.

In [146]:
products_temp[products_temp["unit_price"] < products_temp["cost_price"]]

,product_id,product_name,category,unit_price,cost_price,stock_qty,supplier,launch_date,is_active
40,P141,Peak Hiking Sandal,Footwear,139.14,194.80,313,BlueRidge Textiles,2025-04-30,FALSE
81,P182,Storm Water Filter,Camping,250.06,350.08,103,BlueRidge Textiles,06-27-2024,FALSE
83,P184,Summit Water Filter,Camping,275.89,386.25,365,Alpine Supply Co,2022-09-02,0
128,P229,Peak Neck Gaiter,Base Layers,41.52,58.13,386,BlueRidge Textiles,06-13-2022,N
139,P240,Coastal Beanie,Accesories,44.87,62.82,250,BlueRidge Textiles,2024-01-05,FALSE
151,P252,Ridge Insulated Bottle,Accessories,19.56,27.38,200,summit wholesale,2024-11-15,TRUE