In [1]:
%cd /content
import os
if not os.path.exists("valley-outfitters-analysis"):
    !git clone https://github.com/LSRajan/valley-outfitters-analysis.git
%cd valley-outfitters-analysis
!git pull

import pandas as pd
pd.set_option("display.max_columns", None)

/content
Cloning into 'valley-outfitters-analysis'...
remote: Enumerating objects: 68, done.
remote: Counting objects: 100% (68/68), done.
remote: Compressing objects: 100% (49/49), done.
remote: Total 68 (delta 20), reused 57 (delta 14), pack-reused 0 (from 0)
Receiving objects: 100% (68/68), 3.91 MiB | 8.28 MiB/s, done.
Resolving deltas: 100% (20/20), done.
/content/valley-outfitters-analysis
Already up to date.

#0. Setup

In [2]:
import duckdb
con = duckdb.connect()
for t in ["orders", "customers", "order_items", "products", "returns", "web_sessions"]:
    con.sql(f"CREATE TABLE {t} AS SELECT * FROM 'data/clean/{t}.csv'")
con.sql("SHOW TABLES")

┌──────────────┐
│     name     │
│   varchar    │
├──────────────┤
│ customers    │
│ order_items  │
│ orders       │
│ products     │
│ returns      │
│ web_sessions │
└──────────────┘

In [3]:
con.query(
"""
SUMMARIZE orders
""")

┌─────────────────┬─────────────┬────────────┬────────────┬───────────────┬────────────────────────────┬────────────────────┬────────────────────┬────────────────────┬───────────────────┬───────┬─────────────────┐
│   column_name   │ column_type │    min     │    max     │ approx_unique │            avg             │        std         │        q25         │        q50         │        q75        │ count │ null_percentage │
│     varchar     │   varchar   │  varchar   │  varchar   │     int64     │          varchar           │      varchar       │      varchar       │      varchar       │      varchar      │ int64 │  decimal(9,2)   │
├─────────────────┼─────────────┼────────────┼────────────┼───────────────┼────────────────────────────┼────────────────────┼────────────────────┼────────────────────┼───────────────────┼───────┼─────────────────┤
│ order_id        │ VARCHAR     │ ORD-200000 │ ORD-224999 │         24966 │ NULL                       │ NULL               │ NULL               │ NULL               │ NULL              │ 25000 │            0.00 │
│ customer_id     │ VARCHAR     │ C1000      │ C9996      │          4984 │ NULL                       │ NULL               │ NULL               │ NULL               │ NULL              │ 25000 │            1.53 │
│ order_date      │ DATE        │ 2024-01-01 │ 2026-09-30 │          1015 │ 2025-11-03 07:06:28.357928 │ NULL               │ 2025-06-01         │ 2025-12-08         │ 2026-05-23        │ 25000 │            2.15 │
│ ship_date       │ DATE        │ 2024-01-03 │ 2026-10-06 │          1022 │ 2025-11-06 06:04:24.914148 │ NULL               │ 2025-06-03         │ 2025-12-11         │ 2026-05-26        │ 25000 │           13.57 │
│ status          │ VARCHAR     │ cancelled  │ shipped    │             6 │ NULL                       │ NULL               │ NULL               │ NULL               │ NULL              │ 25000 │            0.00 │
│ payment_method  │ VARCHAR     │ apple pay  │ paypal     │             5 │ NULL                       │ NULL               │ NULL               │ NULL               │ NULL              │ 25000 │            0.00 │
│ channel         │ VARCHAR     │ app        │ web        │             5 │ NULL                       │ NULL               │ NULL               │ NULL               │ NULL              │ 25000 │            0.00 │
│ discount_code   │ VARCHAR     │ bf25       │ welcome10  │             5 │ NULL                       │ NULL               │ NULL               │ NULL               │ NULL              │ 25000 │           76.26 │
│ discount_amount │ DOUBLE      │ 0.0        │ 469.31     │          3161 │ 8.521837999999995          │ 26.265168166149394 │ 0.0                │ 0.0                │ 0.0               │ 25000 │            0.00 │
│ shipping_cost   │ DOUBLE      │ 0.0        │ 6.99       │             4 │ 0.7571884000000084         │ 1.7417654241536489 │ 0.0                │ 0.0                │ 0.0               │ 25000 │            0.00 │
│ order_total     │ DOUBLE      │ 1.49       │ 2380.17    │         19121 │ 292.49923350582094         │ 259.3850980720408  │ 102.96347105990439 │ 220.41889707660874 │ 395.2163689484213 │ 25000 │            1.06 │
├─────────────────┴─────────────┴────────────┴────────────┴───────────────┴────────────────────────────┴────────────────────┴────────────────────┴────────────────────┴───────────────────┴───────┴─────────────────┤
│ 11 rows                                                                                                                                                                                                12 columns │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [4]:
con.query(
"""
SUMMARIZE customers
""")

┌──────────────────┬─────────────┬─────────────┬────────────┬───────────────┬────────────────────────────┬───────┬────────────┬────────────┬────────────┬───────┬─────────────────┐
│   column_name    │ column_type │     min     │    max     │ approx_unique │            avg             │  std  │    q25     │    q50     │    q75     │ count │ null_percentage │
│     varchar      │   varchar   │   varchar   │  varchar   │     int64     │          varchar           │ int32 │  varchar   │  varchar   │  varchar   │ int64 │  decimal(9,2)   │
├──────────────────┼─────────────┼─────────────┼────────────┼───────────────┼────────────────────────────┼───────┼────────────┼────────────┼────────────┼───────┼─────────────────┤
│ customer_id      │ VARCHAR     │ C1000       │ C6319      │          5634 │ NULL                       │  NULL │ NULL       │ NULL       │ NULL       │  5048 │            0.00 │
│ first_name       │ VARCHAR     │ aisha       │ zainab     │            40 │ NULL                       │  NULL │ NULL       │ NULL       │ NULL       │  5048 │            0.00 │
│ last_name        │ VARCHAR     │ ali         │ wood       │            29 │ NULL                       │  NULL │ NULL       │ NULL       │ NULL       │  5048 │            0.00 │
│ signup_date      │ DATE        │ 2023-06-01  │ 2026-10-28 │          1211 │ 2025-01-30 07:47:24.247073 │  NULL │ 2024-03-30 │ 2025-02-02 │ 2025-11-28 │  5048 │            1.86 │
│ date_of_birth    │ DATE        │ 1950-01-01  │ 2005-12-31 │          2972 │ 1977-08-10 10:24:13.831698 │  NULL │ 1963-03-31 │ 1977-06-23 │ 1991-12-27 │  5048 │            5.13 │
│ city             │ VARCHAR     │ aberystwyth │ wrexham    │            21 │ NULL                       │  NULL │ NULL       │ NULL       │ NULL       │  5048 │            1.68 │
│ country          │ VARCHAR     │ england     │ wales      │             4 │ NULL                       │  NULL │ NULL       │ NULL       │ NULL       │  5048 │            1.68 │
│ marketing_opt_in │ BOOLEAN     │ false       │ true       │             2 │ NULL                       │  NULL │ NULL       │ NULL       │ NULL       │  5048 │            8.06 │
└──────────────────┴─────────────┴─────────────┴────────────┴───────────────┴────────────────────────────┴───────┴────────────┴────────────┴────────────┴───────┴─────────────────┘

In [5]:
con.query(
"""
SUMMARIZE products
""")

┌──────────────┬─────────────┬───────────────────────┬─────────────────────────┬───────────────┬─────────────────────┬────────────────────┬────────────────────┬────────────────────┬────────────┬───────┬─────────────────┐
│ column_name  │ column_type │          min          │           max           │ approx_unique │         avg         │        std         │        q25         │        q50         │    q75     │ count │ null_percentage │
│   varchar    │   varchar   │        varchar        │         varchar         │     int64     │       varchar       │      varchar       │      varchar       │      varchar       │  varchar   │ int64 │  decimal(9,2)   │
├──────────────┼─────────────┼───────────────────────┼─────────────────────────┼───────────────┼─────────────────────┼────────────────────┼────────────────────┼────────────────────┼────────────┼───────┼─────────────────┤
│ product_id   │ VARCHAR     │ P101                  │ P263                    │           142 │ NULL                │ NULL               │ NULL               │ NULL               │ NULL       │   163 │            0.00 │
│ product_name │ VARCHAR     │ alpine 2-person tent  │ valley softshell jacket │           127 │ NULL                │ NULL               │ NULL               │ NULL               │ NULL       │   163 │            0.00 │
│ category     │ VARCHAR     │ accessories           │ outerwear               │             6 │ NULL                │ NULL               │ NULL               │ NULL               │ NULL       │   163 │            0.00 │
│ unit_price   │ DOUBLE      │ 7.15                  │ 312.22                  │           146 │ 105.93877300613492  │ 77.42063019613488  │ 45.558125          │ 81.2175            │ 155.0375   │   163 │            0.00 │
│ cost_price   │ DOUBLE      │ 3.44                  │ 181.15                  │           172 │ 52.097579617834384  │ 37.83889398423733  │ 21.345000000000002 │ 41.683749999999996 │ 76.291875  │   163 │            3.68 │
│ stock_qty    │ BIGINT      │ 1                     │ 400                     │           136 │ 196.62576687116564  │ 119.44610261844223 │ 93                 │ 192                │ 291        │   163 │            0.00 │
│ supplier     │ VARCHAR     │ alpine supply company │ trekco ltd              │             4 │ NULL                │ NULL               │ NULL               │ NULL               │ NULL       │   163 │            0.00 │
│ launch_date  │ DATE        │ 2022-01-02            │ 2025-08-28              │           152 │ 2023-12-06 00:00:00 │ NULL               │ 2023-01-19         │ 2023-12-11         │ 2024-10-23 │   163 │            1.23 │
│ is_active    │ BOOLEAN     │ false                 │ true                    │             2 │ NULL                │ NULL               │ NULL               │ NULL               │ NULL       │   163 │            0.00 │
└──────────────┴─────────────┴───────────────────────┴─────────────────────────┴───────────────┴─────────────────────┴────────────────────┴────────────────────┴────────────────────┴────────────┴───────┴─────────────────┘

In [6]:
con.query(
"""
SUMMARIZE order_items
""")

┌───────────────┬─────────────┬────────────┬────────────┬───────────────┬───────────────────┬────────────────────┬────────────────────┬───────────────────┬───────────────────┬───────┬─────────────────┐
│  column_name  │ column_type │    min     │    max     │ approx_unique │        avg        │        std         │        q25         │        q50        │        q75        │ count │ null_percentage │
│    varchar    │   varchar   │  varchar   │  varchar   │     int64     │      varchar      │      varchar       │      varchar       │      varchar      │      varchar      │ int64 │  decimal(9,2)   │
├───────────────┼─────────────┼────────────┼────────────┼───────────────┼───────────────────┼────────────────────┼────────────────────┼───────────────────┼───────────────────┼───────┼─────────────────┤
│ order_item_id │ BIGINT      │ 500001     │ 551903     │         55594 │ 525952.0          │ 14983.249847746632 │ 512973             │ 525961            │ 538921            │ 51903 │            0.00 │
│ order_id      │ VARCHAR     │ ORD-200000 │ ORD-224999 │         24966 │ NULL              │ NULL               │ NULL               │ NULL              │ NULL              │ 51903 │            0.00 │
│ product_id    │ VARCHAR     │ P101       │ P999       │           198 │ NULL              │ NULL               │ NULL               │ NULL              │ NULL              │ 51903 │            0.00 │
│ quantity      │ BIGINT      │ 1          │ 5          │             5 │ 1.363905554480356 │ 0.7498280055820618 │ 1                  │ 1                 │ 1                 │ 51903 │            0.45 │
│ unit_price    │ DOUBLE      │ 7.15       │ 312.22     │           146 │ 106.1252522060802 │ 77.12456831283723  │ 45.816633593037935 │ 81.26744447275995 │ 155.2066653141272 │ 51903 │            0.00 │
└───────────────┴─────────────┴────────────┴────────────┴───────────────┴───────────────────┴────────────────────┴────────────────────┴───────────────────┴───────────────────┴───────┴─────────────────┘

In [7]:
con.query(
"""
SUMMARIZE returns
""")

┌───────────────┬─────────────┬──────────────┬──────────────┬───────────────┬────────────────────────────┬───────────────────┬────────────────────┬───────────────────┬────────────────────┬───────┬─────────────────┐
│  column_name  │ column_type │     min      │     max      │ approx_unique │            avg             │        std        │        q25         │        q50        │        q75         │ count │ null_percentage │
│    varchar    │   varchar   │   varchar    │   varchar    │     int64     │          varchar           │      varchar      │      varchar       │      varchar      │      varchar       │ int64 │  decimal(9,2)   │
├───────────────┼─────────────┼──────────────┼──────────────┼───────────────┼────────────────────────────┼───────────────────┼────────────────────┼───────────────────┼────────────────────┼───────┼─────────────────┤
│ return_id     │ VARCHAR     │ R7001        │ R9799        │          3219 │ NULL                       │ NULL              │ NULL               │ NULL              │ NULL               │  2799 │            0.00 │
│ order_item_id │ BIGINT      │ 500010       │ 551898       │          3442 │ 526237.5209003215          │ 14813.23845563262 │ 513576             │ 526320            │ 539000             │  2799 │            0.00 │
│ order_id      │ VARCHAR     │ ORD-200005   │ ORD-224998   │          3084 │ NULL                       │ NULL              │ NULL               │ NULL              │ NULL               │  2799 │            0.00 │
│ return_date   │ DATE        │ 2024-01-31   │ 2026-09-30   │           833 │ 2025-11-23 07:20:48.333944 │ NULL              │ 2025-07-01         │ 2025-12-27        │ 2026-06-08         │  2799 │            2.43 │
│ reason        │ VARCHAR     │ changed mind │ size         │             6 │ NULL                       │ NULL              │ NULL               │ NULL              │ NULL               │  2799 │           11.47 │
│ refund_amount │ DOUBLE      │ 0.0          │ 312.22       │           482 │ 89.0953607871723           │ 71.1584950414694  │ 36.298705190009755 │ 65.25045404994036 │ 131.64993997893995 │  2799 │            1.96 │
│ resolution    │ VARCHAR     │ exchange     │ store credit │             3 │ NULL                       │ NULL              │ NULL               │ NULL              │ NULL               │  2799 │            0.00 │
└───────────────┴─────────────┴──────────────┴──────────────┴───────────────┴────────────────────────────┴───────────────────┴────────────────────┴───────────────────┴────────────────────┴───────┴─────────────────┘

In [8]:
con.query(
"""
SUMMARIZE web_sessions
""")

┌──────────────────────┬─────────────┬─────────────────────┬─────────────────────┬───────────────┬──────────────────────────┬────────────────────┬────────────────────────────┬────────────────────────────┬────────────────────────────┬───────┬─────────────────┐
│     column_name      │ column_type │         min         │         max         │ approx_unique │           avg            │        std         │            q25             │            q50             │            q75             │ count │ null_percentage │
│       varchar        │   varchar   │       varchar       │       varchar       │     int64     │         varchar          │      varchar       │          varchar           │          varchar           │          varchar           │ int64 │  decimal(9,2)   │
├──────────────────────┼─────────────┼─────────────────────┼─────────────────────┼───────────────┼──────────────────────────┼────────────────────┼────────────────────────────┼────────────────────────────┼────────────────────────────┼───────┼─────────────────┤
│ session_id           │ VARCHAR     │ S900000             │ S959999             │         68169 │ NULL                     │ NULL               │ NULL                       │ NULL                       │ NULL                       │ 60000 │            0.00 │
│ customer_id          │ VARCHAR     │ C1000               │ C6319               │          5336 │ NULL                     │ NULL               │ NULL                       │ NULL                       │ NULL                       │ 60000 │           59.56 │
│ session_timestamp    │ TIMESTAMP   │ 2024-01-01 00:03:08 │ 2026-09-30 23:09:45 │         64481 │ 2025-07-18 07:23:41.2653 │ NULL               │ 2024-11-28 15:48:22.745317 │ 2025-08-19 06:15:17.746957 │ 2026-03-06 17:58:18.773322 │ 60000 │            0.00 │
│ device               │ VARCHAR     │ desktop             │ tablet              │             3 │ NULL                     │ NULL               │ NULL                       │ NULL                       │ NULL                       │ 60000 │            0.00 │
│ traffic_source       │ VARCHAR     │ ads                 │ social              │             6 │ NULL                     │ NULL               │ NULL                       │ NULL                       │ NULL                       │ 60000 │            0.00 │
│ pages_viewed         │ BIGINT      │ 1                   │ 894                 │           125 │ 5.045966666666667        │ 27.598747832349066 │ 1                          │ 2                          │ 5                          │ 60000 │            0.00 │
│ session_duration_sec │ DOUBLE      │ 15.0                │ 199403.0            │          1533 │ 850.0287108764372        │ 10094.660127852787 │ 47.53777717104525          │ 93.13112904619992          │ 224.8469375121906          │ 60000 │            4.04 │
│ converted            │ BOOLEAN     │ false               │ true                │             2 │ NULL                     │ NULL               │ NULL                       │ NULL                       │ NULL                       │ 60000 │            0.00 │
└──────────────────────┴─────────────┴─────────────────────┴─────────────────────┴───────────────┴──────────────────────────┴────────────────────┴────────────────────────────┴────────────────────────────┴────────────────────────────┴───────┴─────────────────┘

##0.1 Views

Revenue and Refunds

In [9]:
con.query(
"""
CREATE OR REPLACE VIEW revenue AS
SELECT
  o.order_id,
  MAX(o.order_total) AS order_total,
  MAX(o.order_date) AS order_date,
  COUNT(r.return_id) AS num_items_returned,
  COALESCE(SUM(r.refund_amount), 0) AS total_refunded
FROM orders o
LEFT JOIN returns r
  ON o.order_id = r.order_id
  AND r.resolution = 'refund'
WHERE o.status != 'cancelled'
AND o.order_date IS NOT NULL
GROUP BY o.order_id"""
)

Customer Spending

In [10]:
con.query("""
CREATE OR REPLACE VIEW customers_spending AS
SELECT
  c.customer_id,
  MAX(c.signup_date) AS signup_date,
  MAX(c.date_of_birth) AS date_of_birth,
  MAX(c.city) AS city,
  MAX(c.country) AS country,
  MAX(c.marketing_opt_in) AS marketing_opt_in,
  COUNT(o.order_id) AS num_orders,
  ROUND(SUM(o.order_total), 2) AS total_spent,
  MIN(o.order_date) AS first_order_date,
  MAX(o.order_date) AS last_order_date
FROM customers c
JOIN orders o
  ON c.customer_id = o.customer_id
  AND o.status != 'cancelled'
GROUP BY c.customer_id
""")

Profits by Order

In [11]:
con.query(
"""
CREATE OR REPLACE VIEW order_profit AS
SELECT
  o.order_id,
  MAX(o.order_date) AS order_date,
  MAX(order_total) AS order_total,
  ROUND(SUM(oi.quantity * (oi.unit_price - p.cost_price)), 2) AS profit
FROM orders o
JOIN order_items oi
  ON o.order_id = oi.order_id
  AND o.status != 'cancelled'
  AND o.order_date IS NOT NULL
JOIN products p
  ON oi.product_id = p.product_id
  AND p.cost_price IS NOT NULL
GROUP BY o.order_id
"""
)

#1. General Revenue

###1.1 How much have refunds impacted revenue?

In [12]:
con.query("""
SELECT
  ROUND(SUM(order_total), 2) AS total_revenue,
  ROUND(SUM(total_refunded), 2) AS total_refunded,
  ROUND(SUM(total_refunded) / SUM(order_total)*100, 2) AS pct_refunded
FROM revenue
""")

┌───────────────┬────────────────┬──────────────┐
│ total_revenue │ total_refunded │ pct_refunded │
│    double     │     double     │    double    │
├───────────────┼────────────────┼──────────────┤
│    6568230.54 │       147104.7 │         2.24 │
└───────────────┴────────────────┴──────────────┘

**Finding:** The company has generated approximately £6.7m in revenue of which  2% (2.26%) was refunded. Refunds have a small impact on revenue so gross revenue can be used in exploration.

###1.2 How have revenue and volume changed over time? Is revenue driven by number of orders or by spending per order?

In [13]:
con.query("""
SELECT
  YEAR(order_date) AS 'year',
  MONTH(order_date) AS 'month',
  COUNT(order_id) AS num_orders,
  ROUND(SUM(order_total), 2) AS revenue,
  ROUND(SUM(order_total) / COUNT(order_id), 2) AS avg_order_revenue,
FROM revenue
WHERE order_date IS NOT NULL
GROUP BY year, month
ORDER BY year, month
""").df()

    year  month  num_orders    revenue  avg_order_revenue
0   2024      1          74   18109.50             244.72
1   2024      2          66   18629.03             282.26
2   2024      3         133   34844.48             261.99
3   2024      4         147   39088.04             265.91
4   2024      5         165   48807.33             295.80
5   2024      6         247   82357.66             333.43
6   2024      7         298   79305.85             266.13
7   2024      8         243   67732.95             278.74
8   2024      9         328   92486.60             281.97
9   2024     10         304   85260.66             280.46
10  2024     11         608  170162.18             279.87
11  2024     12         657  190795.06             290.40
12  2025      1         397  112311.26             282.90
13  2025      2         367   98613.44             268.70
14  2025      3         486  139794.21             287.64
15  2025      4         489  144119.02             294.72
16  2025      5         655  184537.27             281.74
17  2025      6         714  211100.52             295.66
18  2025      7         785  225004.94             286.63
19  2025      8         777  216419.67             278.53
20  2025      9         803  228420.76             284.46
21  2025     10         830  236332.35             284.74
22  2025     11        1462  422730.40             289.15
23  2025     12        1376  403742.21             293.42
24  2026      1         772  226403.36             293.27
25  2026      2         731  221497.98             303.01
26  2026      3        1163  337806.01             290.46
27  2026      4        1061  316913.61             298.69
28  2026      5        1237  358801.62             290.06
29  2026      6        1237  364870.30             294.96
30  2026      7        1376  383536.67             278.73
31  2026      8        1196  346791.16             289.96
32  2026      9        1508  460904.44             305.64

**Finding:** Since the average order cost has only increased gradually, the primary source of revenue gain has been from the increase in the number of orders, which itself appears to peak around the last few months of each year.

The number of orders has gradually increased since the beginning of the company in January 2024. It generally sees an increase throughout the year, which could be attributed to seasonal trends or growth in the company.

The average revenue per order saw an initial growth through 2024 with both dips and peaks in various month. Perhaps due to smaller sample sizes. From 2025 onwards, the average has stabilised with possible a small increase in the overall average.

Overall, the revenue in the most recent months (late 2026) is more than 10x larger than the revenue in the earliest months of 2024. Most of 2025 saw revenue of over 200,000 but saw peaks in winter months where a larger number of orders were made. Most months of 2026 have earned revenues of over 300,000 but the final months of the year are not yet recorded.

In [14]:
con.query("""
SELECT
  MONTH(order_date) AS 'month',
  COUNT(order_id) AS num_orders,
  ROUND(SUM(order_total), 2) AS revenue,
  ROUND(SUM(order_total) / COUNT(order_id), 2) AS avg_order_revenue,
FROM revenue
WHERE order_date IS NOT NULL
GROUP BY month
ORDER BY month
""")

┌───────┬────────────┬───────────┬───────────────────┐
│ month │ num_orders │  revenue  │ avg_order_revenue │
│ int64 │   int64    │  double   │      double       │
├───────┼────────────┼───────────┼───────────────────┤
│     1 │       1243 │ 356824.12 │            287.07 │
│     2 │       1164 │ 338740.45 │            291.01 │
│     3 │       1782 │  512444.7 │            287.57 │
│     4 │       1697 │ 500120.67 │            294.71 │
│     5 │       2057 │ 592146.22 │            287.87 │
│     6 │       2198 │ 658328.48 │            299.51 │
│     7 │       2459 │ 687847.46 │            279.73 │
│     8 │       2216 │ 630943.78 │            284.72 │
│     9 │       2639 │  781811.8 │            296.25 │
│    10 │       1134 │ 321593.01 │            283.59 │
│    11 │       2070 │ 592892.58 │            286.42 │
│    12 │       2033 │ 594537.27 │            292.44 │
├───────┴────────────┴───────────┴───────────────────┤
│ 12 rows                                  4 columns │
└────────────────────────────────────────────────────┘

**Finding:** Average order revenue remains stable across months, however earlier months see much less orders than other months. Later months are missing 2026 data so the revenue and order metrics are misleading. General trend suggests larger amounts of orders in later months.

As mentioned previously, its possible that this trend is due to growth in the company rather than seasonal trends.

###1.3 How have profits changed over time? Is any change in profit due to change in the number of orders or the average profit per order.

In [15]:
con.query(
"""
SELECT
  YEAR(order_date) AS 'year',
  MONTH(order_date) AS 'month',
  COUNT(order_id) AS num_orders,
  ROUND(SUM(order_total), 2) AS revenue,
  ROUND(SUM(order_total) / COUNT(order_id), 2) AS avg_order_revenue,
  ROUND(SUM(profit), 2) AS profit,
  ROUND(SUM(profit) / COUNT(order_id), 2) AS avg_order_profit,
FROM order_profit
GROUP BY year, month
ORDER BY year, month
"""
).df()

,year,month,num_orders,revenue,avg_order_revenue,profit,avg_order_profit
0,2024,1,73,18063.99,247.45,9120.97,124.94
1,2024,2,66,18629.03,282.26,9307.88,141.03
2,2024,3,131,34456.22,263.02,16716.43,127.61
3,2024,4,142,38400.36,270.43,20227.71,142.45
4,2024,5,165,48807.33,295.80,24570.68,148.91
5,2024,6,241,81400.74,337.76,42118.06,174.76
6,2024,7,291,78846.61,270.95,37260.75,128.04
7,2024,8,235,66566.10,283.26,33219.65,141.36
8,2024,9,323,89902.59,278.34,44396.12,137.45
9,2024,10,301,84799.12,281.72,43880.41,145.78
10,2024,11,600,169124.09,281.87,85909.04,143.18
11,2024,12,647,188708.23,291.67,93745.54,144.89
12,2025,1,393,111753.35,284.36,56518.79,143.81
13,2025,2,363,98014.62,270.01,51059.99,140.66
14,2025,3,481,139077.27,289.14,68857.63,143.16
15,2025,4,480,142169.50,296.19,70587.37,147.06
16,2025,5,643,181879.58,282.86,87472.03,136.04
17,2025,6,704,208707.88,296.46,104340.09,148.21
18,2025,7,767,221554.92,288.86,112698.52,146.93
19,2025,8,763,213874.73,280.31,107318.95,140.65
20,2025,9,787,225001.04,285.90,111591.49,141.79
21,2025,10,819,234931.07,286.85,118988.87,145.29
22,2025,11,1438,418700.28,291.17,210357.62,146.28
23,2025,12,1351,399428.11,295.65,202530.90,149.91
24,2026,1,752,223373.13,297.04,110601.88,147.08
25,2026,2,717,219018.82,305.47,106946.03,149.16
26,2026,3,1142,334021.45,292.49,167371.01,146.56
27,2026,4,1046,314865.21,301.02,155256.24,148.43
28,2026,5,1218,355288.57,291.70,177565.86,145.78
29,2026,6,1216,359770.22,295.86,180213.60,148.20
30,2026,7,1364,381930.66,280.01,194057.32,142.27
31,2026,8,1180,344481.77,291.93,168741.32,143.00
32,2026,9,1490,457445.31,307.01,226445.34,151.98

**Finding:** The average profit per order has remained relatively consistent between 140-150. At most the average has slightly increased across time. Otherwise, profit is driven by the number of orders as is closely tied to the overall revenue.

In [16]:
con.query(
"""
SELECT
  MONTH(order_date) AS 'month',
  COUNT(order_id) AS num_orders,
  ROUND(SUM(order_total), 2) AS revenue,
  ROUND(SUM(order_total) / COUNT(order_id), 2) AS avg_order_revenue,
  ROUND(SUM(profit), 2) AS profit,
  ROUND(SUM(profit) / COUNT(order_id), 2) AS avg_order_profit,
FROM order_profit
GROUP BY month
ORDER BY month
"""
).df()

,month,num_orders,revenue,avg_order_revenue,profit,avg_order_profit
0,1,1218,353190.47,289.98,176241.64,144.70
1,2,1146,335662.47,292.90,167313.90,146.00
2,3,1754,507554.94,289.37,252945.07,144.21
3,4,1668,495435.07,297.02,246071.32,147.52
4,5,2026,585975.48,289.23,289608.57,142.95
5,6,2161,649878.84,300.73,326671.75,151.17
6,7,2422,682332.19,281.72,344016.59,142.04
7,8,2178,624922.60,286.92,309279.92,142.00
8,9,2600,772348.94,297.06,382432.95,147.09
9,10,1120,319730.19,285.47,162869.28,145.42
10,11,2038,587824.37,288.43,296266.66,145.37
11,12,1998,588136.34,294.36,296276.44,148.29

**Finding:** As before, the average profit per order has remained relatively consistent between 140-150. There does not appear to be any seasonality to the profits.

The profit would remain consistent regardless of seasonal changes in revenue if the difference is in overall volume not in particular high profit items seeing a larger proportion of overall sales. This is the likey explanation for the consistency in profit.

#2. Customers

###2.1 What percentage are repeat customers? What impact does this have on revenue?

In [17]:
con.query("""
SELECT
 (CASE
  WHEN num_orders > 1 THEN 'repeat'
  ELSE'one-time' END) AS repeat_customer,
 COUNT(customer_id) AS num_customers,
 ROUND(COUNT(customer_id)/ SUM(COUNT(customer_id)) OVER() * 100, 2) AS percentage_of_customers,
 SUM(num_orders) AS num_orders,
 ROUND(SUM(num_orders)/ SUM(SUM(num_orders)) OVER () * 100, 1) AS percentage_of_orders,
 ROUND(SUM(num_orders) / num_customers, 2) AS avg_orders_per_customer,
 ROUND(SUM(total_spent), 2) AS total_revenue,
 ROUND(SUM(total_spent) / SUM(num_orders), 2) AS average_order_total,
 ROUND(SUM(total_spent) / num_customers, 2) AS revenue_per_customer,
 ROUND(SUM(total_spent) / SUM(SUM(total_spent)) OVER () * 100, 1) AS percentage_of_revenue
FROM customers_spending
GROUP BY repeat_customer
ORDER BY num_customers DESC
""")

┌─────────────────┬───────────────┬─────────────────────────┬────────────┬──────────────────────┬─────────────────────────┬───────────────┬─────────────────────┬──────────────────────┬───────────────────────┐
│ repeat_customer │ num_customers │ percentage_of_customers │ num_orders │ percentage_of_orders │ avg_orders_per_customer │ total_revenue │ average_order_total │ revenue_per_customer │ percentage_of_revenue │
│     varchar     │     int64     │         double          │   int128   │        double        │         double          │    double     │       double        │        double        │        double         │
├─────────────────┼───────────────┼─────────────────────────┼────────────┼──────────────────────┼─────────────────────────┼───────────────┼─────────────────────┼──────────────────────┼───────────────────────┤
│ repeat          │          3771 │                   81.66 │      21738 │                 96.2 │                    5.76 │     6296711.7 │              289.66 │              1669.77 │                  96.3 │
│ one-time        │           847 │                   18.34 │        847 │                  3.8 │                     1.0 │     241003.69 │              284.54 │               284.54 │                   3.7 │
└─────────────────┴───────────────┴─────────────────────────┴────────────┴──────────────────────┴─────────────────────────┴───────────────┴─────────────────────┴──────────────────────┴───────────────────────┘

**Finding:** Repeat customers make up 80% of customers so far but make up 96% of all revenue.
Repeat customers have slightly higher order totals on average, but order significantly more often (5.8 vs 1.0) on average.

Converting one-time buyers to repeat customers should be a priority, as this is where most of the revenue lies.

### 2.2 What impact does opting into marketing have on revenue? What drives change, an increase in orders? Higher spending?

In [94]:
con.query("""
SELECT
  marketing_opt_in,
  COUNT(customer_id) AS num_customers,
  ROUND(num_customers/SUM(COUNT(customer_id)) OVER () *100, 1) AS percent_total_customers,
  ROUND(SUM(total_spent), 2) AS total_revenue,
  SUM(num_orders) AS total_orders,
  ROUND(SUM(total_spent)/SUM(num_orders), 2) AS average_spend_per_order,
  ROUND(AVG(total_spent), 2) AS average_spent_per_customer,
  ROUND(AVG(num_orders), 1) AS average_num_orders,
  ROUND(SUM(total_spent)/SUM(SUM(total_spent)) OVER() *100, 1) AS percent_total_revenue,
  ROUND(SUM(num_orders)/SUM(SUM(num_orders)) OVER() *100, 1) AS percent_total_orders,
FROM customers_spending
GROUP BY marketing_opt_in
ORDER BY marketing_opt_in DESC
""").df()

,marketing_opt_in,num_customers,percent_total_customers,total_revenue,total_orders,average_spend_per_order,average_spent_per_customer,average_num_orders,percent_total_revenue,percent_total_orders
0,True,2254,48.8,3380720.72,11545.0,292.83,1502.54,5.1,51.7,51.1
1,False,1993,43.2,2664256.86,9278.0,287.16,1341.52,4.7,40.8,41.1
2,<NA>,371,8.0,492737.81,1762.0,279.65,1328.13,4.7,7.5,7.8

**Finding:** Customers who opt in spend and order more on average. They represent a slightly higher proportion of revenue and orders than their proportion of total customers. Both average spend per order and average number of orders contribute to the larger share of revenue from customers who opt in. However, this difference can be attributed more to the number of orders than average spend per order.

Around 49% (vs 43% customers who opted out) of customers have opted in to marketing, and these customers represent 52% of revenue (vs 41%). Customers who have opted in have spent over £150 more on average (£1502 vs £1341) and order more often (5.1 vs 4.7).

###2.3 Revenue Concentration. How much do different customer spending groups contribute to the overall revenue?

In [95]:
con.query(
"""
WITH percentile_x10_grouping AS(
  SELECT
    * ,
    NTILE(10) OVER (ORDER BY total_spent DESC) AS percentile_group_x10
  FROM customers_spending
  WHERE total_spent IS NOT NULL
)
SELECT
  percentile_group_x10,
  SUM(num_orders) AS num_orders,
  ROUND(SUM(total_spent), 2) AS total_revenue,
  ROUND(SUM(num_orders)/SUM(SUM(num_orders)) OVER()*100, 1) AS percent_total_orders,
  ROUND(SUM(SUM(num_orders)) OVER (ORDER BY percentile_group_x10) / SUM(SUM(num_orders)) OVER () * 100, 1) AS cumulative_percent_orders,
  ROUND(SUM(total_spent)/SUM(SUM(total_spent)) OVER()*100, 1) AS percent_total_revenue,
  ROUND(SUM(SUM(total_spent)) OVER (ORDER BY percentile_group_x10) / SUM(SUM(total_spent)) OVER () * 100, 1) AS cumulative_percent_revenue
FROM percentile_x10_grouping
GROUP BY percentile_group_x10
ORDER BY percentile_group_x10
"""
)

┌──────────────────────┬────────────┬───────────────┬──────────────────────┬───────────────────────────┬───────────────────────┬────────────────────────────┐
│ percentile_group_x10 │ num_orders │ total_revenue │ percent_total_orders │ cumulative_percent_orders │ percent_total_revenue │ cumulative_percent_revenue │
│        int64         │   int128   │    double     │        double        │          double           │        double         │           double           │
├──────────────────────┼────────────┼───────────────┼──────────────────────┼───────────────────────────┼───────────────────────┼────────────────────────────┤
│                    1 │       9146 │    2849397.43 │                 40.5 │                      40.5 │                  43.6 │                       43.6 │
│                    2 │       2895 │     993587.31 │                 12.8 │                      53.3 │                  15.2 │                       58.8 │
│                    3 │       2225 │     721565.38 │                  9.9 │                      63.2 │                  11.0 │                       69.8 │
│                    4 │       1854 │     560363.72 │                  8.2 │                      71.4 │                   8.6 │                       78.4 │
│                    5 │       1618 │     442211.68 │                  7.2 │                      78.6 │                   6.8 │                       85.2 │
│                    6 │       1362 │     346450.16 │                  6.0 │                      84.6 │                   5.3 │                       90.5 │
│                    7 │       1134 │     263849.79 │                  5.0 │                      89.6 │                   4.0 │                       94.5 │
│                    8 │       1000 │     191261.03 │                  4.4 │                      94.1 │                   2.9 │                       97.4 │
│                    9 │        767 │      120584.3 │                  3.4 │                      97.5 │                   1.8 │                       99.3 │
│                   10 │        573 │      48444.59 │                  2.5 │                     100.0 │                   0.7 │                      100.0 │
├──────────────────────┴────────────┴───────────────┴──────────────────────┴───────────────────────────┴───────────────────────┴────────────────────────────┤
│ 10 rows                                                                                                                                         7 columns │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

**Finding:** The top 10% of customers contribute 44% of total revenue and 40% of orders, accounting for £2.8m in sales and over 9000 orders. The top 30% account for 63% of orders and nearly 70% of the total revenue. The greater percentage of revenue than orders implies that these groups spend more than other groups. However, their majority share of the revenue is primarily due to the volume of orders, as seen previously.

On the other hand, the bottom 50% of customers account for only 21% of orders and less than 15% of overall revenue. These customers spend less per order and order much less.

High impact customers should be a focus of the company. Retaining these customers is key for revenue.

#3. Products

### 3.1 How do different product categories perform? Does number of orders or spend drive performance?

In [19]:
con.query(
"""
SELECT
  p.category,
  COUNT(DISTINCT oi.order_id) AS num_orders,
  ROUND(SUM(oi.quantity * oi.unit_price), 2) AS total_spent,
  ROUND(SUM(oi.quantity * (oi.unit_price - p.cost_price)), 2) AS total_profit,
  ROUND(total_profit/total_spent*100, 2) AS margin,
  ROUND(total_spent/SUM(SUM(oi.quantity * oi.unit_price)) OVER ()*100, 1) AS percentage_overall_revenue,
  ROUND(total_profit/SUM(SUM(oi.quantity * (oi.unit_price - p.cost_price))) OVER ()*100, 1) AS percentage_overall_profit,
  ROUND(total_spent/num_orders, 2) AS average_category_spend,
  ROUND(total_profit/num_orders, 2) AS average_order_profit
FROM order_items oi
JOIN products p
  ON p.product_id = oi.product_id
  AND p.cost_price IS NOT NULL
JOIN orders o
  ON o.order_id = oi.order_id
  AND o.status != 'cancelled'
GROUP BY p.category
ORDER BY total_spent DESC
"""
)

┌─────────────┬────────────┬─────────────┬──────────────┬────────┬────────────────────────────┬───────────────────────────┬────────────────────────┬──────────────────────┐
│  category   │ num_orders │ total_spent │ total_profit │ margin │ percentage_overall_revenue │ percentage_overall_profit │ average_category_spend │ average_order_profit │
│   varchar   │   int64    │   double    │    double    │ double │           double           │          double           │         double         │        double        │
├─────────────┼────────────┼─────────────┼──────────────┼────────┼────────────────────────────┼───────────────────────────┼────────────────────────┼──────────────────────┤
│ camping     │       7832 │  2056780.71 │   1102396.99 │   53.6 │                       31.2 │                      33.2 │                 262.61 │               140.76 │
│ outerwear   │       7316 │  1777167.13 │    888135.65 │  49.97 │                       27.0 │                      26.7 │                 242.92 │                121.4 │
│ footwear    │       6350 │  1109074.52 │    524542.18 │   47.3 │                       16.8 │                      15.8 │                 174.66 │                82.61 │
│ backpacks   │       5002 │   785350.46 │    369550.52 │  47.06 │                       11.9 │                      11.1 │                 157.01 │                73.88 │
│ base layers │       6702 │   448702.53 │    229369.35 │  51.12 │                        6.8 │                       6.9 │                  66.95 │                34.22 │
│ accessories │       7166 │   412588.29 │    206367.94 │  50.02 │                        6.3 │                       6.2 │                  57.58 │                 28.8 │
└─────────────┴────────────┴─────────────┴──────────────┴────────┴────────────────────────────┴───────────────────────────┴────────────────────────┴──────────────────────┘

**Finding:** The margin for each category remains similar at around 50%, so the difference in average order profit is due to the pricing of the item not necessarily due to profitability.

While most categories have somewhat similar number of orders (around 7000 excluding backpacks), most of the revenue is tied to only a few categories. Camping and Outerwear combined represent almost 60% (58.2%) of revenue and almost 60% (59.9%) of profits. Footwear and backpacks combine for just less than 30% of revenue and profits. Whereas base layers and accessories only see around £400k in revenue and £200k in profit, accounting for less than 15% of both revenue and profit.

### 3.2 How do different products perform? Does number of orders or spend drive performance?

In [20]:
con.query(
"""
SELECT
  p.product_id, p.product_name,
  COUNT(DISTINCT oi.order_id) AS num_orders,
  ROUND(SUM(oi.quantity * oi.unit_price), 2) AS total_revenue,
  ROUND(SUM(oi.quantity * (oi.unit_price - p.cost_price)), 2) AS total_profit,
  ROUND(total_profit/total_revenue*100, 2) AS margin,
  ROUND(total_revenue/SUM(SUM(oi.quantity * oi.unit_price)) OVER ()*100, 1) AS percentage_overall_revenue,
  ROUND(total_profit/SUM(SUM(oi.quantity * (oi.unit_price - p.cost_price))) OVER ()*100, 1) AS percentage_overall_profit,
  ROUND(total_revenue/num_orders, 2) AS average_product_revenue,
  ROUND(total_profit/num_orders, 2) AS average_purchase_profit
FROM order_items oi
JOIN products p
  ON p.product_id = oi.product_id
  AND p.cost_price IS NOT NULL
JOIN orders o
  ON o.order_id = oi.order_id
  AND o.status != 'cancelled'
GROUP BY p.product_id, p.product_name
ORDER BY total_revenue DESC
"""
)

┌────────────┬──────────────────────────┬────────────┬───────────────┬──────────────┬────────┬────────────────────────────┬───────────────────────────┬─────────────────────────┬─────────────────────────┐
│ product_id │       product_name       │ num_orders │ total_revenue │ total_profit │ margin │ percentage_overall_revenue │ percentage_overall_profit │ average_product_revenue │ average_purchase_profit │
│  varchar   │         varchar          │   int64    │    double     │    double    │ double │           double           │          double           │         double          │         double          │
├────────────┼──────────────────────────┼────────────┼───────────────┼──────────────┼────────┼────────────────────────────┼───────────────────────────┼─────────────────────────┼─────────────────────────┤
│ P174       │ alpine sleeping mat      │        302 │      125783.0 │      56278.5 │  44.74 │                        1.9 │                       1.7 │                   416.5 │                  186.35 │
│ P186       │ coastal water filter     │        300 │     124312.76 │     73270.08 │  58.94 │                        1.9 │                       2.2 │                  414.38 │                  244.23 │
│ P159       │ highland sleeping bag    │        282 │     123121.61 │     57422.08 │  46.64 │                        1.9 │                       1.7 │                   436.6 │                  203.62 │
│ P128       │ peak down gilet          │        312 │     122274.88 │     72121.14 │  58.98 │                        1.9 │                       2.2 │                  391.91 │                  231.16 │
│ P166       │ summit camping stove     │        288 │      117240.2 │     47497.45 │  40.51 │                        1.8 │                       1.4 │                  407.08 │                  164.92 │
│ P155       │ alpine 2-person tent     │        299 │     115232.92 │     73422.96 │  63.72 │                        1.7 │                       2.2 │                  385.39 │                  245.56 │
│ P162       │ coastal sleeping bag     │        275 │     114896.96 │     73934.88 │  64.35 │                        1.7 │                       2.2 │                  417.81 │                  268.85 │
│ P127       │ valley down gilet        │        282 │     104131.17 │     59675.33 │  57.31 │                        1.6 │                       1.8 │                  369.26 │                  211.61 │
│ P161       │ peak sleeping bag        │        310 │     103178.75 │     53996.53 │  52.33 │                        1.6 │                       1.6 │                  332.83 │                  174.18 │
│ P111       │ ridge softshell jacket   │        308 │      102412.0 │      61568.0 │  60.12 │                        1.6 │                       1.9 │                  332.51 │                   199.9 │
│  ·         │           ·              │         ·  │          ·    │         ·    │    ·   │                         ·  │                        ·  │                     ·   │                     ·   │
│  ·         │           ·              │         ·  │          ·    │         ·    │    ·   │                         ·  │                        ·  │                     ·   │                     ·   │
│  ·         │           ·              │         ·  │          ·    │         ·    │    ·   │                         ·  │                        ·  │                     ·   │                     ·   │
│ P234       │ coastal trekking poles   │        290 │       7797.08 │      3116.45 │  39.97 │                        0.1 │                       0.1 │                   26.89 │                   10.75 │
│ P178       │ peak head torch          │        284 │       7485.25 │      3388.26 │  45.27 │                        0.1 │                       0.1 │                   26.36 │                   11.93 │
│ P227       │ trail liner gloves       │        303 │        6924.9 │       3985.2 │  57.55 │                        0.1 │                       0.1 │                   22.85 │                   13.15 │
│ P249       │ storm insulated bottle   │        296 │       5702.61 │      2069.74 │  36.29 │                        0.1 │                       0.1 │                   19.27 │                    6.99 │
│ P250       │ forest insulated bottle  │        280 │        4758.0 │       2074.8 │  43.61 │                        0.1 │                       0.1 │                   16.99 │                    7.41 │
│ P260       │ summit map case          │        311 │        4517.7 │       2604.8 │  57.66 │                        0.1 │                       0.1 │                   14.53 │                    8.38 │
│ P238       │ coastal beanie           │        311 │        4429.6 │      2562.84 │  57.86 │                        0.1 │                       0.1 │                   14.24 │                    8.24 │
│ P256       │ highland dry bag         │        290 │       3433.92 │      2085.44 │  60.73 │                        0.1 │                       0.1 │                   11.84 │                    7.19 │
│ P212       │ highland merino base top │        271 │       3169.71 │      1453.86 │  45.87 │                        0.0 │                       0.0 │                    11.7 │                    5.36 │
│ P259       │ ridge map case           │        280 │       2924.35 │      1026.59 │   35.1 │                        0.0 │                       0.0 │                   10.44 │                    3.67 │
├────────────┴──────────────────────────┴────────────┴───────────────┴──────────────┴────────┴────────────────────────────┴───────────────────────────┴─────────────────────────┴─────────────────────────┤
│ 157 rows (20 shown)                                                                                                                                                                          10 columns │
└─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

**Finding:** Products on both end of the spectrum in terms of total revenue both see a similar number of orders. The more expensive products see similar demand so see a larger proportion of the total revenue.

 Profit margins are more variable than categories, with values around generally between 40-60. However products on both ends see similar variation, so again the difference is likely primarily due to pricing and not profitability or demand.

#4. Revenue Losses

###4.1 How have refunds changed over time? Has their impact on revenue changed?

In [21]:
con.query("""
SELECT
  MONTH(order_date) AS 'month',
  COUNT(order_id) AS num_orders,
  ROUND(SUM(order_total), 2) AS revenue,
  ROUND(SUM(total_refunded)) AS total_refuned,
  ROUND(SUM(total_refunded)/SUM(order_total) * 100, 1) AS percent_revenue_refunded,
  ROUND(SUM(CASE WHEN total_refunded > 0 THEN 1 ELSE 0 END)/COUNT(order_id) * 100, 1) AS percent_orders_with_refunded
FROM revenue
WHERE order_date IS NOT NULL
GROUP BY month
ORDER BY month
""")

┌───────┬────────────┬───────────┬───────────────┬──────────────────────────┬──────────────────────────────┐
│ month │ num_orders │  revenue  │ total_refuned │ percent_revenue_refunded │ percent_orders_with_refunded │
│ int64 │   int64    │  double   │    double     │          double          │            double            │
├───────┼────────────┼───────────┼───────────────┼──────────────────────────┼──────────────────────────────┤
│     1 │       1243 │ 356824.12 │        8328.0 │                      2.3 │                          6.7 │
│     2 │       1164 │ 338740.45 │        7873.0 │                      2.3 │                          7.8 │
│     3 │       1782 │  512444.7 │       10943.0 │                      2.1 │                          6.5 │
│     4 │       1697 │ 500120.67 │       12506.0 │                      2.5 │                          7.3 │
│     5 │       2057 │ 592146.22 │       11582.0 │                      2.0 │                          6.5 │
│     6 │       2198 │ 658328.48 │       16942.0 │                      2.6 │                          7.6 │
│     7 │       2459 │ 687847.46 │       15571.0 │                      2.3 │                          6.9 │
│     8 │       2216 │ 630943.78 │       14016.0 │                      2.2 │                          7.3 │
│     9 │       2639 │  781811.8 │       15849.0 │                      2.0 │                          6.5 │
│    10 │       1134 │ 321593.01 │        7599.0 │                      2.4 │                          6.7 │
│    11 │       2070 │ 592892.58 │       11345.0 │                      1.9 │                          6.1 │
│    12 │       2033 │ 594537.27 │       14550.0 │                      2.4 │                          7.1 │
├───────┴────────────┴───────────┴───────────────┴──────────────────────────┴──────────────────────────────┤
│ 12 rows                                                                                        6 columns │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────┘

**Finding:** Refunds are stable across months, with consistent percentage of revenue being refunded and consistent amount of orders with refunds present.

### 4.2 What were the reasons for returns? What impact did each reason have on revenue

In [22]:
con.query("""
SELECT
  COALESCE(reason, 'unknown') AS reason,
  COUNT(return_id) AS num_returns,
  ROUND(SUM(refund_amount), 2) AS total_return_amount,
  ROUND(AVG(refund_amount), 2) AS average_refund_amount,
  ROUND(COUNT(return_id) / SUM(COUNT(return_id)) OVER() *100, 1) AS percent_of_returns,
  ROUND(SUM(refund_amount) / SUM(SUM(refund_amount)) OVER() *100, 1) AS percent_total_return_amount
FROM returns
GROUP BY reason
ORDER BY total_return_amount DESC
""")

┌─────────────────┬─────────────┬─────────────────────┬───────────────────────┬────────────────────┬─────────────────────────────┐
│     reason      │ num_returns │ total_return_amount │ average_refund_amount │ percent_of_returns │ percent_total_return_amount │
│     varchar     │    int64    │       double        │        double         │       double       │           double            │
├─────────────────┼─────────────┼─────────────────────┼───────────────────────┼────────────────────┼─────────────────────────────┤
│ size            │         972 │            83644.87 │                 87.77 │               34.7 │                        34.2 │
│ faulty product  │         497 │            44124.32 │                  89.5 │               17.8 │                        18.0 │
│ changed mind    │         334 │            29507.19 │                 90.51 │               11.9 │                        12.1 │
│ faulty delivery │         315 │             27399.6 │                 88.39 │               11.3 │                        11.2 │
│ unknown         │         321 │            25924.08 │                 83.63 │               11.5 │                        10.6 │
│ misleading      │         238 │            21568.74 │                 93.37 │                8.5 │                         8.8 │
│ mistake         │         101 │            10046.37 │                100.46 │                3.6 │                         4.1 │
│ other           │          21 │              2262.5 │                107.74 │                0.8 │                         0.9 │
└─────────────────┴─────────────┴─────────────────────┴───────────────────────┴────────────────────┴─────────────────────────────┘

**Finding:** The most common reason for returns is size, representing over 34% of returns and over 34% of the amount refunded. The next most common reason is a faulty product which represents around 18% of returns and 18% of the amount refunded. Around 11% of returns and amount returned is due to faulty delivery.

No particular reason results in a disproportionate amount refunded. The amount of revenue refunded by any given reason is due to the frequency of that reason.

### 4.3 What were the resolutions for returns? What impact did each have on revenue?

In [23]:
con.query("""
SELECT
  resolution,
  COUNT(return_id) AS num_returns,
  ROUND(SUM(refund_amount), 2) AS total_return_amount,
  ROUND(AVG(refund_amount), 2) AS average_refund_amount,
  ROUND(COUNT(return_id) / SUM(COUNT(return_id)) OVER() *100, 1) AS percent_of_returns,
  ROUND(SUM(refund_amount) / SUM(SUM(refund_amount)) OVER() *100, 1) AS percent_total_return_amount
FROM returns
GROUP BY resolution
ORDER BY total_return_amount DESC
""")

┌──────────────┬─────────────┬─────────────────────┬───────────────────────┬────────────────────┬─────────────────────────────┐
│  resolution  │ num_returns │ total_return_amount │ average_refund_amount │ percent_of_returns │ percent_total_return_amount │
│   varchar    │    int64    │       double        │        double         │       double       │           double            │
├──────────────┼─────────────┼─────────────────────┼───────────────────────┼────────────────────┼─────────────────────────────┤
│ refund       │        1694 │           151655.14 │                 91.14 │               60.5 │                        62.0 │
│ store credit │         568 │            47057.73 │                 84.64 │               20.3 │                        19.2 │
│ exchange     │         537 │             45764.8 │                 87.34 │               19.2 │                        18.7 │
└──────────────┴─────────────┴─────────────────────┴───────────────────────┴────────────────────┴─────────────────────────────┘

**Finding:** Around 60% (1694) of returns were resolved by refunding the customer, while 40% (1105) were either exchanged for store credit or item exchange. The average refund amount for store credit or exchanges (£84 and £87) were lower than refunds (£91), and directly redirect the money back into the company.

A possible suggestion would be to increase the number of returns which are resolved either by store credit or exchanges. Both size and faulty product are reasons for which exchanges are direct solutions rather than refunds.

How do return rates differ across product categories?

In [59]:
con.query(
"""
SELECT
  p.category,
  COUNT(oi.order_item_id) AS num_items,
  COUNT(r.return_id) AS num_returns,
  ROUND(COUNT(r.return_id) / COUNT(oi.order_item_id)*100, 1) AS return_percent,
  ROUND(SUM(r.refund_amount), 2) AS return_amount,
  ROUND(COUNT(oi.order_item_id) / SUM(COUNT(oi.order_item_id)) OVER()*100, 2) AS percent_total_items,
  ROUND(SUM(r.refund_amount) / SUM(SUM(r.refund_amount)) OVER()*100, 2) AS percent_total_return_amount
FROM order_items oi
JOIN products p
  ON p.product_id = oi.product_id
LEFT JOIN returns r
  ON r.order_item_id = oi.order_item_id
JOIN orders o
  ON oi.order_id = o.order_id
  AND o.status != 'cancelled'
GROUP BY p.category
"""
)

┌─────────────┬───────────┬─────────────┬────────────────┬───────────────┬─────────────────────┬─────────────────────────────┐
│  category   │ num_items │ num_returns │ return_percent │ return_amount │ percent_total_items │ percent_total_return_amount │
│   varchar   │   int64   │    int64    │     double     │    double     │       double        │           double            │
├─────────────┼───────────┼─────────────┼────────────────┼───────────────┼─────────────────────┼─────────────────────────────┤
│ footwear    │      7489 │         456 │            6.1 │      42456.02 │               15.57 │                       17.41 │
│ base layers │      7962 │         484 │            6.1 │      17859.96 │               16.55 │                        7.32 │
│ backpacks   │      5521 │         287 │            5.2 │      25036.79 │               11.48 │                       10.27 │
│ outerwear   │      8503 │         482 │            5.7 │      62536.07 │               17.68 │                       25.65 │
│ accessories │      8843 │         534 │            6.0 │      16166.43 │               18.38 │                        6.63 │
│ camping     │      9789 │         548 │            5.6 │      79783.58 │               20.35 │                       32.72 │
└─────────────┴───────────┴─────────────┴────────────────┴───────────────┴─────────────────────┴─────────────────────────────┘

**Finding:** Return rates are very similar across categories, ranging between 5.2% - 6.1%. There are no concerns of a particular category being  resposible for a disproportionate number of returns. The difference in the total returned for each category is primarily due to the number of orders and pricing of the items.

# Web Activity

###5.1 Do customer conversion rates differ across devices?

In [58]:
con.query(
"""
SELECT
  device,
  COUNT(session_id) AS num_sessions,
  ROUND(SUM(converted)/COUNT(converted)*100,1) AS converted_percent,
  ROUND(COUNT(session_id) / SUM(COUNT(session_id)) OVER ()*100, 2) AS percent_all_sessions
FROM web_sessions
GROUP BY device
"""
)

┌─────────┬──────────────┬────────────────┬──────────────────────┐
│ device  │ num_sessions │ converted_rate │ percent_all_sessions │
│ varchar │    int64     │     double     │        double        │
├─────────┼──────────────┼────────────────┼──────────────────────┤
│ mobile  │        35993 │            3.7 │                59.99 │
│ tablet  │         4204 │            3.5 │                 7.01 │
│ desktop │        19803 │            3.3 │                33.01 │
└─────────┴──────────────┴────────────────┴──────────────────────┘

**Finding:** Conversion rates are similar across devices, with rates between 3.3%-3.7%. 60% of sessions are from mobile devices, of which 3.7% are converted to a sale.

###5.2 Are customer conversion rates similar across the traffic source?

In [63]:
con.query(
"""
SELECT
  traffic_source,
  COUNT(session_id) AS num_sessions,
  ROUND(COUNT(session_id) / SUM(COUNT(session_id)) OVER ()*100, 2) AS percent_total_sessions,
  ROUND(SUM(converted)/COUNT(converted) * 100,1) AS converted_percent
FROM web_sessions
GROUP BY traffic_source
"""
)

┌────────────────┬──────────────┬────────────────────────┬───────────────────┐
│ traffic_source │ num_sessions │ percent_total_sessions │ converted_percent │
│    varchar     │    int64     │         double         │      double       │
├────────────────┼──────────────┼────────────────────────┼───────────────────┤
│ ads            │         4923 │                   8.21 │               2.3 │
│ direct         │         7228 │                  12.05 │               4.9 │
│ organic        │        20998 │                   35.0 │               3.0 │
│ paid search    │         8206 │                  13.68 │               2.9 │
│ email          │         7207 │                  12.01 │               7.8 │
│ social         │         8467 │                  14.11 │               1.5 │
│ referral       │         2971 │                   4.95 │               3.2 │
└────────────────┴──────────────┴────────────────────────┴───────────────────┘

**Finding:** Email ads have the highest conversion with almost 8% conversion rate. Second is direct traffic with 4.9%. The most common source of traffic is organic representing 35% off traffic with 3% conversion. Regular ads and paid search ads both underperform this benchmark and have less than 3% conversion.

It is important to consider that this measures conversion for the instance the user visits the website. It does not consider following visits which may result in higher long-term conversion.

Paid searches appear when a customer is searching for the item itself, so the company should expect this to be higher than regular organic searches. Ads should also be a concern and should be higher conversion than organic. Although both may have a wider impact than first time visit conversion.

Email and direct have the highest conversion. This is to be expected given we have already found that marketing-opt-in customers spend and order more. Also, if a customer is visiting the site directly, it is presumably with greater intent to purchase an item than regular browsing.

###5.3 Do signed-in customers convert more often than otherwise?

In [66]:
con.query("""
SELECT
  CASE WHEN customer_id IS NULL THEN 'False' ELSE 'True' END AS signed_in,
  COUNT(session_id) AS num_sessions,
  ROUND(COUNT(session_id) / SUM(COUNT(session_id)) OVER ()*100, 1) AS percent_total_sessions,
  ROUND(SUM(converted)/COUNT(converted) * 100,1) AS converted_percent
FROM web_sessions
GROUP BY signed_in
ORDER BY signed_in DESC
"""
)

┌───────────┬──────────────┬────────────────────────┬───────────────────┐
│ signed_in │ num_sessions │ percent_total_sessions │ converted_percent │
│  varchar  │    int64     │         double         │      double       │
├───────────┼──────────────┼────────────────────────┼───────────────────┤
│ True      │        24264 │                   40.4 │               3.6 │
│ False     │        35736 │                   59.6 │               3.5 │
└───────────┴──────────────┴────────────────────────┴───────────────────┘

**Finding:** Signed-in customers convert only 0.1% more often than otherwise. Around 40% of sessions are from customers who have signed in. In general, signing in does not appear to have any impact on conversion.